### ISSUE TITLE
Typo in example complex actions

### ISSUE THREAD

**Issue by JunhongXu** [allenai/ai2thor#10]
Hello

I just found a typo in this example. Instead of 
```
event = controller.step(dict(
    action='PutObject',
    receptacleObjectid=receptacle_object_id,
    objectId=mug_object_id), raise_for_failure=True)
```

it should be 
```
event = controller.step(dict(
    action='PutObject',
    receptacleObjectId=receptacle_object_id,
    objectId=mug_object_id), raise_for_failure=True)
```
the id in receptacleObjectId should be uppercase. 

In addition, I could not run this example, maybe the microwave is not visible at the final position?

**Comment by ekolve** [comment]
Thank you for find this.  The example has been updated to fix the typo as well as the orientation of the agent so that it can see the mug as visible.
