### ISSUE TITLE
About argument "gpu_index" not works

### ISSUE THREAD

**Issue by RupertLuo** [allenai/ai2thor#1006]
I set controller's gpu_index = 5. But it doesn't seem to work. it will only occupy the GPU-memory of the first card.

**Comment by ekolve** [comment]
The `gpu_index` param only works with the new `CloudRendering` platform.  If you would like to try it out, you can start the controller as follows:

```python
from ai2thor.platform import CloudRendering
import ai2thor.controller

c = ai2thor.controller.Controller(platform=CloudRendering, gpu_index=2)
```

The benefit of the new platform is that X11 is no longer required, but you will need to have libvulkan installed (this is checked when the Controller is initialized).
