### ISSUE TITLE
Room navigation (room tour) using ai2thor 

### ISSUE THREAD

**Issue by yqi19** [allenai/ai2thor#1034]
Hi, thanks for the amazing simulator! 
We are working on  ai2thor to collect dataset now, and I want to find out that how can I guide the agent to navigate around each scene, and take pictures in front of different scenarios.
Is there some quick way to solve this?
Thanks!

**Comment by mattdeitke** [comment]
Looks like this is the same as https://github.com/allenai/ai2thor/discussions/1035, let's use that one :)
