### ISSUE TITLE
SetObjectPoses leads to discarding of objects

### ISSUE THREAD

**Issue by RishiHazra** [allenai/ai2thor#1057]
Hi,

I'm running this [code file](https://github.com/allenai/ai2thor/blob/main/ai2thor/controller.py#L938) from the ALFRED codebase (specifically this function)

```python
def restore_scene(self, object_poses, object_toggles, dirty_and_empty):
        '''
        restore object locations and states
        '''
        super().step(dict(
            action='Initialize',
            gridSize=constants.AGENT_STEP_SIZE / constants.RECORD_SMOOTHING_FACTOR,
            cameraY=constants.CAMERA_HEIGHT_OFFSET,
            renderImage=constants.RENDER_IMAGE,
            renderDepthImage=constants.RENDER_DEPTH_IMAGE,
            renderClassImage=constants.RENDER_CLASS_IMAGE,
            renderObjectImage=constants.RENDER_OBJECT_IMAGE,
            visibility_distance=constants.VISIBILITY_DISTANCE,
            makeAgentsVisible=False,
        ))
        if len(object_toggles) > 0:
            super().step((dict(action='SetObjectToggles', objectToggles=object_toggles)))

        if dirty_and_empty:
            super().step(dict(action='SetStateOfAllObjects',
                               StateChange="CanBeDirty",
                               forceAction=True))
            super().step(dict(action='SetStateOfAllObjects',
                               StateChange="CanBeFilled",
                               forceAction=False))
        super().step((dict(action='SetObjectPoses', objectPoses=object_poses)))
```

 which accesses AI2Thor controller.py line ([self.last_event = self.server.receive()](https://github.com/allenai/ai2thor/blob/e40b5f9138387d0a0aa5dc996ed57f5903f10912/ai2thor/controller.py#L938)) to provide the metadata of objects amongst other things 
```
self.last_event.metadata["objects"]
```
However, the [referenced line](https://github.com/allenai/ai2thor/blob/e40b5f9138387d0a0aa5dc996ed57f5903f10912/ai2thor/controller.py#L938) leads to the discarding of certain objects whenever **action='SetObjectPoses'**. As in, the number of objects before and after running this line is always different. Moreover, there is a pattern in the discarded objects -- objects like Microwave, GarbageCan, Shelf, etc. get dropped. This consistently happens for all FloorPlans. 

I believe this issue is arising in the Thor env rather than the Alfred codebase. I'm unable to narrow it down further. Any help is greatly appreciated. Thanks !!!

**Comment by winthos** [comment]
Could you double check exactly what parameters you are passing in to `SetObjetPoses`? If a moveable or pickupable sim objects is not specified in the dict, it [is removed from the scene as per our documentation.](https://ai2thor.allenai.org/ithor/documentation/objects/set-object-states/#set-object-poses
)

**Comment by RishiHazra** [comment]
Hi,

I just resolved the issue and was going to type the update when I found your comment. You're right -- the issue was I was only passing the pickupable objects and not the moveable objects, hence objects like Microwave, CoffeeMachine, GarbageCan were dropped. Now it is resolved. Will go ahead and close the issue.
