### ISSUE TITLE
https://ai2thor-cover.allenai.org points to missing GitHub pages

### ISSUE THREAD

**Issue by pauls-ai2** [allenai/ai2thor#1064]
https://ai2thor-cover.allenai.org/

<img width="1276" alt="Screen Shot 2022-08-26 at 10 08 12 AM" src="https://user-images.githubusercontent.com/39743357/186957167-7361ef9c-81cf-47a2-be4d-828117091e53.png">

If this subdomain is no longer being used, we should remove the DNS entry for it. Leaving it up as is would be a security vulnerability, where someone could create a page on that subdomain and mimic a legit AI2 site.

**Comment by mattdeitke** [comment]
Yes, please remove it. We are not using it.

**Comment by pauls-ai2** [comment]
I deleted the subdomain in Route 53 on the `halodev` AWS account. It was pointing to `allenai.github.io`, in case we need to recreate it.
