### ISSUE TITLE
Can not teleport to customed positions not in reachable positions list

### ISSUE THREAD

**Issue by Tom-Huang** [allenai/ai2thor#1065]
Hello, thank you for developing and maintaining the great simulator. It helps my research a lot. 
I was trying to add a "drone" or "arm" robot to the scene and use "Teleport" action to move the robot, but the agent doesn't change its position. I wonder if it is because the simulator doesn't support teleporting to positions other than the reachable positions generated with the following code:
```python
positions = controller.step(
    action="GetReachablePositions"
).metadata["actionReturn"]
print(positions)
```
The full code to reproduce the result is as follows:
```python
from ai2thor.controller import Controller

controller = Controller(
    agentMode="arm",
    visibilityDistance=1.5,
    scene="FloorPlan1",
    gridSize=0.1,
    movementGaussianSigma=0,
    rotateStepDegrees=90,
    rotateGaussianSigma=0,
    renderDepthImage=True,
    renderInstanceSegmentation=False,
    width=1080,
    height=720,
    fieldOfView=90
)

# get reachable positions (which I think is generated based on the gridSize)
positions = controller.step(
    action="GetReachablePositions"
).metadata["actionReturn"]
print(positions)

# teleport to one of the reachable positions works
tmp = positions[2]
new_pos_1 = dict(x=tmp['x'], y=tmp['y'], z=tmp['z'])
event = controller.step(
    action="Teleport",
    position=new_pos_1,
    rotation=dict(x=0, y=0, z=0),
    horizon=0
)

# teleport to a customed position shifted from one of the reachable positions doesn't change the agent position
new_pos_2 = dict(x=tmp['x'] + 0.09, y=tmp['y'], z=tmp['z'])
event = controller.step(
    action="Teleport",
    position=new_pos_2,
    rotation=dict(x=0, y=0, z=0),
    horizon=0
)

```

As you can see from the code, I first get a list of reachable positions as introduced in the documentation. Later, I take one position out of the list (new_pos_1) and teleport to it. The teleport succeeds. After that, I take the same position, add 0.15m (not gridSize) to its x component (new_pos_2) and then try to teleport. This time teleport fails.
My question is, can we teleport to position other than the grid point calculated from the gridSize? Could you provide an example for it. Thank you very much!
(side note: my version of AI2THOR is '4.3.0')

**Comment by mattdeitke** [comment]
Please make sure to pass in `snapToGrid=False`, as in:

```python
from ai2thor.controller import Controller
controller = Controller(snapToGrid=False)
```
Otherwise, it will only try to use the grid of positions.

**Comment by Tom-Huang** [comment]
Wow, impressive response speed! It works, thanks a lot!
