### ISSUE TITLE
Access environment w/o vision?

### ISSUE THREAD

**Issue by neubig** [allenai/ai2thor#107]
Hello! We're very interested in the general idea of acting in virtual environments, but not very interested in trying to solve vision, or dealing with the ambiguity of vision extractions. I was wondering: is there any way to access the environment, bypassing the vision component and just getting the gold-standard recognition results?

**Comment by roozbehm** [comment]
In the metadata, we send the list of objects, their position, whether they are visible or not, and their state (open/close, etc). So you can you use that and ignore the images. More information about the metadata is available at: [https://ai2thor.allenai.org/tutorials/event-metadata](url)

**Comment by neubig** [comment]
Great, thank you!
