### ISSUE TITLE
'Digest mismatch' with controller.start()

### ISSUE THREAD

**Issue by nina124** [allenai/ai2thor#11]
Ubuntu16.04 
Following the installation guide, install ai2thor with pip, then 'Digest mismatch' Exeption raised in `controller.start()`
> thor-201712211442-Linux64: [|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%   1.4 MiB/s]  of 0.0MB
Exception                                 Traceback (most recent call last)
<ipython-input-4-a4f5716a9338> in <module>()
----> 1 controller.start()
/usr/local/lib/python2.7/dist-packages/ai2thor/controller.pyc in start(self, port, start_unity, player_screen_width, player_screen_height, x_display)
    513             env['DISPLAY'] = ':' + x_display
    514 
--> 515         self.download_binary()
    516 
    517         self.server = ai2thor.server.Server(
/usr/local/lib/python2.7/dist-packages/ai2thor/controller.pyc in download_binary(self)
    487                 url,
    488                 self.build_name(),
--> 489                 BUILDS[platform.system()]['sha256'])
    490 
    491             z = zipfile.ZipFile(io.BytesIO(zip_data))
/usr/local/lib/python2.7/dist-packages/ai2thor/downloader.pyc in download(url, build_name, sha256_digest)
     25     pbar.finish()
     26     if m.hexdigest() != sha256_digest:
---> 27         raise Exception("Digest mismatch for url %s" % url)
     28 
     29     return b''.join(file_data)
Exception: Digest mismatch for url http://s3-us-west-2.amazonaws.com/ai2-thor/builds/thor-201712211442-Linux64.

**Comment by nina124** [comment]
Problem solved

**Comment by ekolve** [comment]
What was the cause of the issue? You should only get that error if there was a problem with the download.

**Comment by nina124** [comment]
@ekolve Yes, there was a problem with my network connection.

**Comment by jsdd25** [comment]
@nina124 Hello! I have encountered the same problem. I have tried many times. But, I still encounter the problem of 'Digest mismatch'. Could you give me some suggestions? My e-mail is 773903267@qq.com. Thank you very much!

**Comment by ekolve** [comment]
What version of python are you using and what version of ai2thor? Its possible that the download is timing out and you don't receive the entire package.  I can send you a direct link to the package and where to unzip it to.

**Comment by jsdd25** [comment]
Thank you all! I have solved this problem.

**Comment by jiafei1224** [comment]
Hi, can share with me how to fixed this issue? Thank you

**Comment by QLV5645-QLJ** [comment]
> What version of python are you using and what version of ai2thor? Its possible that the download is timing out and you don't receive the entire package. I can send you a direct link to the package and where to unzip it to.

I also encounter the same issue. Could tell me where to unzip it?

**Comment by ekolve** [comment]
run the following:
```
import ai2thor._builds
print(ai2thor._builds.BUILDS)
```
Find the url for your platform.  For example, the latest OSX build url is:
http://s3-us-west-2.amazonaws.com/ai2-thor/builds/thor-202001071627-OSXIntel64.zip

Run the following:
```
mkdir -p $HOME/.ai2thor/releases/thor-202001071627-OSXIntel64
cd $HOME/.ai2thor/releases/thor-202001071627-OSXIntel64
wget http://s3-us-west-2.amazonaws.com/ai2-thor/builds/thor-202001071627-OSXIntel64.zip
unzip thor-202001071627-OSXIntel64.zip
```
Swap Linux64 with OSXIntel64 if you are on Linux.  Hopefully that gets it working for you.
