### ISSUE TITLE
Question related to TeleportFull x,y,z position

### ISSUE THREAD

**Issue by phongnhhn92** [allenai/ai2thor#110]
Hello, I am trying to generate scene data from different viewpoints from AI2Thor and I found the function TeleportFull very useful. However, I don't understand how to define that x,y,z, rotation, horizon parameters since I don't know where is the origin point of the scene. My goal is to create a camera flying around the room scene (at a distance z to the floor) and gather RGB images along with other information such as depth, objectID, segmented mask, ... Can anyone help me with this? Thanks a lot!

**Comment by ekolve** [comment]
Currently, the TeleportFull applies gravity to the agent after telporting to stick the agent to the ground.  So flying around at different heights won't work out of the box.  To get an approximation of where you can navigate to with the agent, you can run this code:

```python
controller = ai2thor.controller.BFSController()
controller.start()
controller.search_all_closed('FloorPlan28') # replace with whatever scene you want
print(controller.grid_points)
```

That will run a BFS across the scene searching for points that the agent can navigate to. When you TeleportFull, rotation can be any value from 0.0 - 360.0 and horizon can be any value from  -180.0 to 180.0.

**Comment by HuynhLam** [comment]
Hi,
In addition to @phongnhhn92 , how can we get the camera intrinsic parameter of the camera?
Thanks.

**Comment by roozbehm** [comment]
We have exposed the camera projection matrix, but it is possible to get it. Please refer to [](https://docs.unity3d.com/ScriptReference/Camera-projectionMatrix.html) .

**Comment by phongnhhn92** [comment]
Hello, I have made a few modifications on the Ai2Thor unity source code and get the projection matrix but when I try to move the agent left and right or rotate, the obtained matrix remains the same which is very weird. Would you mind to take a look and help me to fix this?
AgentManager.cs
`
[Serializable]
public class ObjectMetadata
{
	public string name;
	public Vector3 position;
	public Vector3 rotation;
	public float cameraHorizon;
        //TODO
        public Matrix4x4 projectionMatrix;
        public Matrix4x4 projectionMatrix_inverse;
	public bool visible;
	public bool receptacle;
	public int receptacleCount;
	public bool openable;
	public bool pickupable;
	public bool isopen;
	public string[] receptacleObjectIds;
	public PivotSimObj[] pivotSimObjs;
	public float distance;
	public String objectType;
	public string objectId;
	public float[] bounds3D;
	public string parentReceptacle;
}
`
BaseFPSAgentController
`
public virtual MetadataWrapper generateMetadataWrapper()
		{
			ObjectMetadata agentMeta = new ObjectMetadata();
			agentMeta.name = "agent";
			agentMeta.position = transform.position;
			agentMeta.rotation = transform.eulerAngles;
			agentMeta.cameraHorizon = m_Camera.transform.rotation.eulerAngles.x;
            //TODO
            agentMeta.projectionMatrix = m_Camera.projectionMatrix;
            agentMeta.projectionMatrix_inverse = m_Camera.projectionMatrix.inverse;

			if (agentMeta.cameraHorizon > 180) {
				agentMeta.cameraHorizon -= 360;
			}

			MetadataWrapper metaMessage = new MetadataWrapper();
			metaMessage.agent = agentMeta;
			metaMessage.sceneName = UnityEngine.SceneManagement.SceneManager.GetActiveScene().name;
			metaMessage.objects = generateObjectMetadataForTag("SimObj", false);
			metaMessage.collided = collidedObjects.Length > 0;
			metaMessage.collidedObjects = collidedObjects;
			metaMessage.screenWidth = Screen.width;
			metaMessage.screenHeight = Screen.height;

			return metaMessage;
		}
`
The `m_Camera` is define on the BaseFPSAgentController.cs

**Comment by roozbehm** [comment]
I believe that's the intrinsic matrix which stays the same. It does not include the rotation or translation of the camera.

**Comment by phongnhhn92** [comment]
> I believe that's the intrinsic matrix which stays the same. It does not include the rotation or translation of the camera.

Sorry but I am kinda confused here, so the returned projectionMatrix (4x4 matrix) contains only intrinsic parameters? From what I have learned so far about pinhole camera model, the projection matrix is the result of matrix multiplication between Intrinsic (K) and Extrinsic matrix ([R  t]). Then how can the return projectionMatrix as I got from above post remains the same when I move my agent around the room? 
![image](https://user-images.githubusercontent.com/11288381/54112729-7a52c400-43ef-11e9-87fd-8fa3418f0111.png)

This is the code I used to get the projectionMatrix from my modified AI2Thor:

`
import ai2thor.controller
controller = ai2thor.controller.Controller()
controller.local_executable_path = '/home/storm/ai2thor/unity/builds/thor-local-Linux64'
controller.start()
# can be any one of the scenes FloorPlan###
controller.reset('FloorPlan30')
controller.step(dict(action='Initialize', gridSize=0.25))

event = controller.step(dict(action='MoveLeft'))
print(event.metadata['agent']['projectionMatrix'])

event2 = controller.step(dict(action='MoveRight'))
print(event.metadata['agent']['projectionMatrix'])
`

**Comment by roozbehm** [comment]
This page shows how the matrix is computed. It does include  R and t: https://docs.unity3d.com/ScriptReference/Camera-projectionMatrix.html

**Comment by shsjxzh** [comment]
Hi @phongnhhn92 ,
I also want to write a interface for the intrinsic matrix, but after I tried your code and rebuild it to linux version and run it, I always get a "self reference loop" error. I have tried several ways to fix it, like giving the "JsonConvert" function a new JsonSerializerSetting in "AgentManager.cs" to preserve the reference, but it does not work. I am wondering how can I fix this problem?

**Comment by tmanh** [comment]
> Hello, I have made a few modifications on the Ai2Thor unity source code and get the projection matrix but when I try to move the agent left and right or rotate, the obtained matrix remains the same which is very weird. Would you mind to take a look and help me to fix this?
> AgentManager.cs
> ![image](https://user-images.githubusercontent.com/11288381/53588025-94410b00-3b94-11e9-99ff-4d306b0ebf40.png)
> BaseFPSAgentController.cs
> ![image](https://user-images.githubusercontent.com/11288381/53588048-acb12580-3b94-11e9-82c0-771085334d5e.png)
> I suspect that the `m_Camera` are init every single time the agent made an action so that the projectionMatrix remains the same.

I tried to compile the code to compute the intrinsic parameters (I am using Ubuntu 18.04). However, I cannot use Matrix4x4 even though it is implemented in UnityEngine. It seems like it could not import the UnityEngine.CoreModule.dll properly (where Matrix4x4 is implemented). Do you have any suggestion?

**Comment by ruinianxu** [comment]
@tmanh 
Hi,

I am trying to download unity 2019.4.20 from [archive](https://unity3d.com/get-unity/download/archive) via unity hub. But there is no respond after clicking the green button of unity hub. Could you please give me some suggestions on how to install unity editor 2019.4.20 in ubuntu? Really appreciate your kind help.

Thanks

**Comment by tmanh** [comment]
Hi,

Have you tried to chose the installation method in the box which is next to the operating system box? If you chose the installation method, the download will start automatically. You don’t need the green button anyway.

Yours sincerely,
Anh M. Truong.

**Comment by ruinianxu** [comment]
@tmanh 
Hi,

Thank you so much for your reply. I've figured it out how to install specific version of Unity editor in Linux. May I ask if you ever met any problems when you initialize the controller with local executable file? I explored different ways like giving local_executable_path when initializing the controller or first initialize the controller, then change its local_executable_path and run controller.start(). None of them worked for me. If it is ok, could you provide me with your code for initializing the controller?

Really appreciate your precious time and kind help.

**Comment by tmanh** [comment]
Hi,

First, you have to create a virtual environment to work with ai2thor. Then, you need to build ai2thor from source code. Something like 

‘’’
cd ai2thor
pip install invoke
invoke local-build 
‘’’

After that, you can run it as below:

‘’’
import ai2thor.controller

local_executable_path = ‘path_to_local_file’
controller = ai2thor.controller.Controller(local_executable_path= local_executable_path)
controller.step(dict(action=‘ChangeResolution’, x=600, y=600), raise_for_failure=True)

controller.reset(scene=‘scene_name’)
event = controller.step(dict(action=‘Initialize’), renderDepthImage=True, grid_size=0.25)
‘’’

This is the code I used with ai2thor version 2.4.0. It may not work for other versions.

**Comment by ruinianxu** [comment]
@tmanh 
Thank you so much for your reply. I followed the entire same way as you but was stuck at the step of initializing controller. I will keep exploring. Really appreciate your help.
