### ISSUE TITLE
High-level action support

### ISSUE THREAD

**Issue by angmavrogiannis** [allenai/ai2thor#1147]
Hi, first of all thank you for building such a great simulation platform!

I am working on a task planning project and want to use the simulator for a simple demonstration of breaking a high-level task down to a set of mid-level actions (e.g. add egg to pan --> grab egg, crack egg, grab cracked_egg, put cracked_egg on pan). Is there a simple way to do that without worrying about the exact location of the objects and the agent? In other words, I'm asking if there's some high-level API-like usage in the form of:

`grab(egg)`
`crack(egg)`
`put(egg, pan)`

Thank you!

**Comment by Ma-Zijing** [comment]
Same question. I think we need to implement the high-level action by ourselves ; ;
