### ISSUE TITLE
How to programmatically change object locations?

### ISSUE THREAD

**Issue by beduffy** [allenai/ai2thor#116]
Currently have placed agent low on the ground with objects on the ground in unity editor and it works perfectly by doing `controller.local_executable_path = build_file_path`

However, for each different placement of the objects we have to create a new unity build file. Is there a way we could manipulate the locations of the objects within Python code so that we could have random placements of objects in any x, y, z coordinate? Or is this 100x easier in the unity editor and C# code?

**Comment by winthos** [comment]
It would be 100x easier to create the random placement functionality in the Unity Editor. The Actions called via the Python code are really just executing C# functions, so either way to create new custom functions you would need to first implement it on the C# side.

**Comment by beduffy** [comment]
Thanks a lot, I'll try this!

closing.
