### ISSUE TITLE
Hi! Will Unity's latest pricing policy affect the future updates of the AI2thor platform?

### ISSUE THREAD

**Issue by yang9004-sudoer** [allenai/ai2thor#1163]
Will Unity's latest pricing policy affect the future updates of the AI2thor platform?

**Comment by Lucaweihs** [comment]
Hi @yang9004-sudoer , while the recent updates to Unity's pricing model are a bit perplexing, they should not impact AI2-THOR as AI2-THOR is a freely available open-source project that makes no revenue (Unity's new pricing scheme only kicks in when a game as >$200k in revenue).
