### ISSUE TITLE
interact.py Issue 

### ISSUE THREAD

**Issue by ibrahimyousri** [allenai/ai2thor#1175]
Thank you all for this amazing work!
The interact.py doesn't work do you have the final version of it or any script like the [demo page](https://ai2thor.allenai.org/demo/)

**Comment by winthos** [comment]
There is no explicit interact action that works exactly the way the demo page works. The demo is an independent set of controls built just for exploring the scenes in the browser.

You can find how to use the python controller to interact within THOR at our [documentation site here.](https://ai2thor.allenai.org/ithor/documentation)

**Comment by ibrahimyousri** [comment]
Thanks for the clarification
