### ISSUE TITLE
Problem for saving images in the scene

### ISSUE THREAD

**Issue by WangJuan6** [allenai/ai2thor#1177]
Dear author,
your work is excellent. I want to know if is there any method to save all images in the house at once. I try to access the image by teleporting the agent to the all reachable position, but this method is too slow. Can you help me to solve this problem?
Thanks
Juan

**Comment by garfieldnate** [comment]
I don't think you're going to get a faster solution than that; teleport the agent to every position, turn to look in all directions and save the picture. To make the rendering faster you can always reduce the width/height of the unity window, or you could set `quality` to `Low` or `Very Low`. You can use this to get a feel for the house layout, but it will never be fast enough for you to get a realtime feed of every view of the house after every action.

I have tried adding extra cameras to the scene, as well, and in my experience this was pretty slow.

**Comment by WangJuan6** [comment]
Thanks for your try and reply, I will attempt to change the quality, thanks again.
