### ISSUE TITLE
How to build the Unity framework on MacOSX

### ISSUE THREAD

**Issue by aliang8** [allenai/ai2thor#122]
Hi all,

I am working on a project that requires some Unity development. I followed the instructions on the README for installing Unity and building it: `pip install invoke; invoke local-build`. However, I am running into this issue. Would greatly appreciate it if someone could take a look at the issue. 

![image](https://user-images.githubusercontent.com/16139634/53850463-5de6ff80-3f89-11e9-9e7c-3a659222c35b.png)

I cloned the repository, installed Unity Editor version 2017.3.1 and ran the command above in the directory. 

Running on MacBook Pro 2018

**Comment by Lucaweihs** [comment]
Hi Anthony,

Some questions:
1. It seems to be suggesting that the `/Applications/Unity-2017.3.1f1/Unity.app/Contents/MacOS/Unity` file does not exist on your computer. Can you double check that it does? If it doesn't, where have you installed Unity?
2. Are you able run the scenes from the editor? (I.e. open the editor, search for one of the floor plans, say FloorPlan1, and hit the play button).

**Comment by aliang8** [comment]
The file does not exist on my computer. 

![image](https://user-images.githubusercontent.com/16139634/53907742-cf6f8e00-401b-11e9-86b8-1e99abc80f68.png)

I believe this is where my Unity is installed.

I am able to play the scenes from the editor. Here's a screenshot of that.

![image](https://user-images.githubusercontent.com/16139634/53908655-d4cdd800-401d-11e9-959e-2640f8d080ab.png)

**Comment by Lucaweihs** [comment]
Great, can you try renaming `/Applications/Unity` to `/Applications/Unity-2017.3.1f1` and rerunning invoke?

**Comment by aliang8** [comment]
Sure. I'm getting this now.

![image](https://user-images.githubusercontent.com/16139634/53910203-570bcb80-4021-11e9-822d-e13150e5dfbb.png)

This is what's inside the Unity folder.

![image](https://user-images.githubusercontent.com/16139634/53910232-6559e780-4021-11e9-823b-ed63ec0da484.png)

**Comment by Lucaweihs** [comment]
Do you have the Unity application closed before running `invoke`?

**Comment by aliang8** [comment]
Oh no I didn't. So I closed it and reran. 

![image](https://user-images.githubusercontent.com/16139634/53913966-8bd05080-402a-11e9-826f-a6aa52249597.png)

It prints those three lines and tries to open Unity, but Unity doesn't respond (the GUI doesn't open). Also I don't see the /unity/build folder created. Sorry for all the questions! Really appreciate it.

**Comment by Lucaweihs** [comment]
Sure thing. You wont see the GUI open when running `invoke` but for some reason unity does require that you don't have it already open when you build from the command line. Ok, lets see if you can build some scenes from the editor:

1. Open the build settings (File / Build Settings)

2. In the project tab in unity, go to Assets / Scenes and select all the files there.

3. Drag the selected files to `Scenes in Build` in the build settings window previously opened.
![screen shot 2019-03-06 at 1 20 14 pm](https://user-images.githubusercontent.com/628838/53914591-d219b580-4012-11e9-9804-0406b2ed551a.png)
<img width="613" alt="screen shot 2019-03-06 at 1 22 30 pm" src="https://user-images.githubusercontent.com/628838/53914629-ef4e8400-4012-11e9-8016-bf3c3e3a7bbf.png">

4. Hit Build & Run in the build settings window.

Let me know if this produces any errors.

**Comment by aliang8** [comment]
Nope doesn't produce any errors. 

![image](https://user-images.githubusercontent.com/16139634/53918974-8bd64d80-4036-11e9-971b-11adab6fcb75.png)

**Comment by Lucaweihs** [comment]
That's somewhat surprising. One more thing to try:

1. Delete the `build.log` file in the top level directory.
2. Rerun `invoke local-build` (being sure to have unity closed of course).
3. Upload the new `build.log` file here.

**Comment by aliang8** [comment]
Thanks! Here is the log. Also I want to confirm one thing. I am trying to add actions as described in https://github.com/allenai/ai2thor/issues/121#issuecomment-470226688 and make changes to `DiscreteRemoteFPSAgentController.cs`. That would require me to build the framework locally right? Thanks!

[build.log](https://github.com/allenai/ai2thor/files/2942989/build.log)

**Comment by Lucaweihs** [comment]
Strange, everything looks good in the log. @ekolve , any ideas?

To be clear, you're trying to build from the latest commit of the master branch without any changes correct? 

Yes, if you want to add new actions you'll have to make changes to `DiscreteRemoteFPSAgentController.cs` and build locally.

**Comment by ekolve** [comment]
Did you look in the unity/builds/ directory after running local-build? There should be new directory with the locally built version in there.

**Comment by aliang8** [comment]
I see the directory that you are referring to. thor-local-OSXIntel64.app <- I have this file in there.

**Comment by ekolve** [comment]
You should be able to start up the environment by running the following:

```python
env = ai2thor.controller.Controller()
env.local_executable_path = 'unity/builds/thor-local-OSXIntel64.app/Contents/MacOS/thor-local-OSXIntel64'
env.start()
env.reset('FloorPlan1')
env.step(dict(action='Initialize',gridSize=0.25))

```

**Comment by aliang8** [comment]
Awesome! Thank you it works.
