### ISSUE TITLE
Ways to speed up ai2thor rendering?

### ISSUE THREAD

**Issue by beduffy** [allenai/ai2thor#123]
From the ai2thor paper:

```
"AI2-THOR can be run in a single-threaded or multithreaded
fashion, where each python thread has an independent
Unity process and game state. On an Intel(R)
Core(TM) i7-4770 CPU @3.40GHz and NVIDIA Titan X
(Maxwell), a typical interaction, including all steps of sending
a command and receiving a response, takes 0.07 seconds (13 actions per second). When running 8 simultaneous threads, each thread can perform 7 actions per second.
On an Intel(R) Xeon(R) CPU E5-2696 v4 @2.20GHz and a
Titan X (Pascal), we achieve 22 actions per second for one
thread, and 15 actions per second for 8 threads. The resolution
for images is 300 × 300. Changing the resolution
affects the performance."
```

With 22 FPS we are only gonna get max 2 million steps a day for a RL agent. With 8 threads (*15) = 120 FPS => 10 million steps a day

Are there any tips to speed this up? 

E.g. not rendering unity, turning off segmentation/object classes (but I need it for some tasks), smaller resolution than 300x300 (I know this is the minimum, but could we hack it?), speeding up the python Flask interface, speeding up the C# Unity code?

The reason I bring this up is because House3D report 1000+ FPS and habitat-api reports 10,000+ FPS on a single GPU and it is hard to iterate quickly on A3C hyperparams if solving the task requires 10-50 million steps.

**Comment by roozbehm** [comment]
We have made some modifications which speed up the rendering a bit. It will be in our next release. The reason that those frameworks achieve this level of performance is mainly lack of physics and interaction and also lack of high quality texture/lighting/etc. Rendering a static set of objects is not that expensive. The main bottleneck is physics and interaction. RL approaches that require millions of iterations might not be the right approach for these types of tasks.

**Comment by etendue** [comment]
I tried to not start unity engine in ai2thor environment, the environment was simply blocked/stuck.

**Comment by beduffy** [comment]
Ok thank you, I'll work on changing to more sample efficient algorithms or increasing my compute, looking forward to the next release!

Closing this issue

**Comment by ekolve** [comment]
Here are two things you can do to increase increase speed:

1) Pass a quality setting to the Controller. 
```python
c = ai2thor.controller.Controller(quality='Low')
```
Take a look here for valid settings:

https://github.com/allenai/ai2thor/blob/master/ai2thor/_quality_settings.py

2) don't render the image
```python
c = ai2thor.controller.Controller(quality='Low')
c.start()
c.reset('FloorPlan28')
c.step(dict(action='Initialize', gridSize=0.25, render image=False))
```
If you do that you will only receive the metadata.
