### ISSUE TITLE
how to generate scene dumps like the icra 2017 paper?

### ISSUE THREAD

**Issue by YunlianMoon** [allenai/ai2thor#125]
Does anyone know how to use this thor framework to generate scene dumps described in icra 2017 paper? (https://github.com/yushu-liu/icra2017-visual-navigation)

**Comment by jkulhanek** [comment]
I created a python script that can do that. Can send it to you if you are interested.

**Comment by YunlianMoon** [comment]
@jkulhanek  thank you for your help, I'd like to get it, my mail is (yunlianmoon@gmail.com).

**Comment by YunlianMoon** [comment]
@jkulhanek could you send me your  python script, please?

**Comment by jkulhanek** [comment]
Email sent.

**Comment by YunlianMoon** [comment]
@jkulhanek  thank you very much.

**Comment by wcarvalho** [comment]
Could you also send me your python script? (wcarvalh@umich.edu)

**Comment by masteryolo24** [comment]
Could you also send me your python script? (duc.tran@sotatek.com)

**Comment by jkulhanek** [comment]
Please look at my repo for the script: https://github.com/jkulhanek/a2cat-vn-pytorch/blob/master/environments/gym_ai2thor/_register_downloads.py .

**Comment by masteryolo24** [comment]
@jkulhanek Can you update link 
![Screenshot from 2019-05-03 20-27-22](https://user-images.githubusercontent.com/26140925/57140395-e2b39580-6de1-11e9-9347-ed53b2dcc397.png)

**Comment by jkulhanek** [comment]
Sorry, can you try it now?

**Comment by masteryolo24** [comment]
thanks for your help @jkulhanek
