### ISSUE TITLE
what does event.metadata['agent']['position']['y'] means?

### ISSUE THREAD

**Issue by YunlianMoon** [allenai/ai2thor#126]
I know  event.metadata['agent']['position']['x'] and event.metadata['agent']['position']['z'] are coordinate, but what is the event.metadata['agent']['position']['y']?

**Comment by roozbehm** [comment]
y is the axis perpendicular to the ground plane.

**Comment by YunlianMoon** [comment]
thanks

**Comment by YunlianMoon** [comment]
@roozbehm  thanks
