### ISSUE TITLE
Unity downloader stopped working after update

### ISSUE THREAD

**Issue by jkulhanek** [allenai/ai2thor#131]
Hi,
after yesterday's update, the package will not download the correct version of unity server automatically. It will fail with exception 'None type is not iterable'.

Please fix this in `controller.py`, where the method build_url is supposed to return an URL. It instead returns nothing causing this error.

**Comment by jkulhanek** [comment]
#132

**Comment by ekolve** [comment]
Fixed.  Sorry about that.  1.0.1 has been pushed to pypi.
