### ISSUE TITLE
randomInitialize was removed?

### ISSUE THREAD

**Issue by HuynhLam** [allenai/ai2thor#144]
Hi,
Does current release remove the randomInitialize action?
Thanks.

**Comment by Zzmonica** [comment]
And the new version doesn't have the scene file which  contains the meta file of rooms.

**Comment by roozbehm** [comment]
For object randomization, please refer to "Object Position Randomization" section of the [Documentation](http://ai2thor.allenai.org/documentation/actions).

**Comment by roozbehm** [comment]
@Zzmonica Do you mean the scene grid points?

**Comment by Zzmonica** [comment]
When I open the ai2thor-master in unity3D,I can't see the scene like the last version.

**Comment by Zzmonica** [comment]
The `ai2thor-master/unity/Assets/Scenes` file.
Thanks!

**Comment by winthos** [comment]
@Zzmonica that directory has moved, please look in ai2thor-master/unity/Assets/Physics/Physics Scenes to find the scene files

**Comment by winthos** [comment]
@Zzmonica We just pushed an update that moves the scene files back to their old filepath, so they can now be found in  `ai2thor-master/unity/Assets/Scenes`.

**Comment by roozbehm** [comment]
@HuynhLam You can use `GetReachablePositions` and `Teleport` actions for randomization of the agent. The former provides you with the list of possible locations for the agent. You can select one of them at random and teleport the agent to that location.

**Comment by Zzmonica** [comment]
Thanks! I have found it. But it seems that many objects  lose the animation, like apple, tomato, bread and etc. They don't have their state to be sliced? And the actions are simplized.

**Comment by winthos** [comment]
yes, many objects can no longer change states in the new version due to a rework of how animations and state changes work within the infrastructure. We are working on adding back all those state changes and introducing new ones in a new update sometime in the future. Previously the state changes were in look only (a mesh was swapped between a full apple vs a sliced apple) but we are looking to add collision and to each individual slice of an object once it is "sliced." 

For example, previously you would get `apple->sliced apple`. The new version of "slice" will get `apple -> apple slice A, apple slice B, apple slice C` with each apple slice being its own unique, manipulatable object.

As far as actions being simplified, are there any specific actions you mean? Many actions have been expanded to have increased range of functionality, like more objects being usable as receptacles, or being able to place an object in a receptacle and then pick up the receptacle to move them together.

**Comment by Zzmonica** [comment]
Action space has been expanded , you did an awesome job! Looking forward to your animation part of jobs, by the way, the animator of each object  are null in unity3D, maybe you can add it as well.

**Comment by winthos** [comment]
We could add back in the animator components, but note that any code that uses that logic like in [this response](https://github.com/allenai/ai2thor/issues/121) will no longer work in THOR version 1.0 

Objects no longer use animator components to track their animation state, and instead will be "destroyed" when a destructive state change is used on them, and instead replaced with a new object (ie: apple -> apple slice A, apple slice B, apple slice C). Objects that have a state change but are not "destroyed," like opening a drawer or cabinet, also no longer use animation components to track their open/close state.

**Comment by Zzmonica** [comment]
How can I define the "destroy" kind of actions? Like slice action. Any other interactive actions can be applied on objects? Like toast, water and etc, And how can we define it ?

**Comment by Zzmonica** [comment]
1. Hi, here are some questions.How can I define the "destroy" kind of actions? Like slice action.
2. Are there exist other state on object? Like dirty bowl ?
3. Any other interactive actions can be applied on objects? Like toast, fry, watering, tidy ? And how can we define it ?
Thanks a lot~

**Comment by winthos** [comment]
@Zzmonica , in response:

1) The "Slice" action does not currently exist. A future update will add new destructive, state change actions along with the objects and other assets needed for them to work. Currently we are actively working on creating this functionality.

2) These other states will come with the state change update, which again is actively being worked on.

3) These actions do not exist at this time, but will also be included in the state change update. We hope to be able to cut apart food objects, turn on/off appliances like the microwave, toaster, etc. 

As of right now, the current version of the framework supports a few state change objects like open/close on all drawers, cabinets, microwaves, etc. Additionally every scene has a light switch that can be used to turn the lights on and off in a realistic and noticeable way. 

Please refer to [our documentation page](http://ai2thor.allenai.org/documentation/object-types) to see which object types are able to open/close or turn on/off.

**Comment by mattdeitke** [comment]
Closing as this appears to be solved. Feel free to re-open if there are any related follow-ups :)
