### ISSUE TITLE
What is the 'start_unity' parameter?

### ISSUE THREAD

**Issue by toandx** [allenai/ai2thor#151]
I have read your code and have tried set start_unity=False in controller.start() and set controller.killing_unity=True but it always run and waiting for return self.last_event. I do not have root or docker in my server. Help me!!!

**Comment by ekolve** [comment]
You do not want to pass ```start_unity=False```.  That should only be used when you are developing with the Unity Editor.  ai2thor requires that a X server (with opengl) be running in order to render the scenes.

**Comment by mattdeitke** [comment]
Closing as this appears to be solved. Feel free to re-open if there are any follow-ups :)
