### ISSUE TITLE
Missing bounding boxes (class_detection2D) for SinkBasins, CounterTops, TableTops

### ISSUE THREAD

**Issue by MohitShridhar** [allenai/ai2thor#171]
The 2D bounding boxes for `SinkBasin`, `CounterTop`, `TableTop` are missing in certain scenes. 

Cases:
- FloorPlan28 - 'Sink|-00.60|+00.93|-03.39|SinkBasin’
- FloorPlan23 - 'CounterTop|-00.30|+00.95|-02.79'
- FloorPlan17 - 'CounterTop|-01.00|+00.95|-00.67'

For example, in this frame:
https://pasteboard.co/IbGfJpH.png

`class_detection2D` doesn't have `SinkBasin`:
https://pasteboard.co/IbGgJ0S.png

**Comment by mattdeitke** [comment]
Merging with #102 as they appear to be related.
