### ISSUE TITLE
Get instance_detections2D for only some steps

### ISSUE THREAD

**Issue by wcarvalho** [allenai/ai2thor#178]
I've found that initializing the controller with `renderObjectImage=True` slows down the rendering by 4x (from ~400 fps to ~100fps). Is there a way to not initialize the controller with renderObjectImage but have it render with the step function, similar to `event = controller.step(dict(action='GetReachablePositions'))
`? For example, `event = controller.step(dict(action='GetInstanceDetections2D'))
`

**Comment by wcarvalho** [comment]
bump

**Comment by ekolve** [comment]
At the moment, this isn't possible without a code change, but it should be a fairly simple change to add.  What I am thinking is that there will be an additional parameter that can be passed for all actions to indicate whether you want the instanceDetections2d for that step().

**Comment by wcarvalho** [comment]
If it's a simple code change, I am happy to do it myself. Could you give me some guidance on what files/functions I would need to look at? This would be tremendously helpful for my research.

**Comment by wcarvalho** [comment]
bump

**Comment by ekolve** [comment]
Take a look at how renderImage parameter works:

https://github.com/allenai/ai2thor/blob/master/unity/Assets/Scripts/AgentManager.cs#L609

Setting renderImage to false, prevents the image from getting sent.  The following parameters exist for controlling the other images that can get sent:

renderObjectImage
renderDepthImage
renderClassImage

If you can toggle those in the same place that renderImage is set, then you can include/exclude that image in the payload that gets sent back to python. From the python side, you would do something like this:

```python
event = controller.step(action=dict(action='MoveAhead', renderObjectImage=False, renderDepthImage=False, renderClassImage=False))
```

**Comment by ekolve** [comment]
This is now possible.  You can pass ```renderObjectImage=True``` to any action and the ObjectImage will be enabled, but only for that action.

**Comment by mattdeitke** [comment]
Closing as this appears to be solved. Feel free to re-open if there are any related follow-ups :)
