### ISSUE TITLE
Digest mismatch for url error with controller.start()

### ISSUE THREAD

**Issue by jiafei1224** [allenai/ai2thor#222]
Exception: Digest mismatch for url http://s3-us-west-2.amazonaws.com/ai2-thor/builds/thor-201712211442-Linux64.zip

This error occur when i try to run controller.start()
alternative i try to download the link but also failed.

Anyone can help me pls.

**Comment by ekolve** [comment]
Closing based on email to ai2thor list that this was resolved.
