### ISSUE TITLE
Can this camera set as down to top (ceiling view)?

### ISSUE THREAD

**Issue by zisuina** [allenai/ai2thor#228]

**Comment by roozbehm** [comment]
Please refer to the following issue: [](https://github.com/allenai/ai2thor/issues/124)

**Comment by winthos** [comment]
You can also try this undocumented action:

`event = controller.step(dict(action='ToggleMapView'))`

I can't guarantee it will work because it is not officially supported, but it might be enough for your purposes.

**Comment by mattdeitke** [comment]
Merging with #445
