### ISSUE TITLE
Multi Agent run OpenObject action

### ISSUE THREAD

**Issue by mikezhang95** [allenai/ai2thor#229]
When I run this command in multi agent setting,  I got the following error, 

AttributeError: 'MultiAgentEvent' object has no attribute 'instance_detections2D'

Do I need to implement an 'instance_detections2D' attribute by myself?

**Comment by ekolve** [comment]
Given the following code - assuming you have 2 agents:
```python
multi_agent_event = controller.step(action=<someaction>)
# instance_detections2d for agent1
multi_agent_event.events[0].instance_detections2D

#instance_detections2d for agent2
multi_agent_event.events[1].instance_detections2D
```

**Comment by ekolve** [comment]
Closing as issue appears to be resolved.

**Comment by Frost-99** [comment]
Hi,
I got the same error when trying to perform OpenObject action in multi agent setting. OpenObject in single agent setting is fine.
