### ISSUE TITLE
Is there a way to get semantic segmented inputs? 

### ISSUE THREAD

**Issue by parsa-m** [allenai/ai2thor#23]
Hi 

Is there a way to get semantic segmented inputs or is only the rgb image available? 

Thanks

**Comment by roozbehm** [comment]
We intentionally did not focus on proxy tasks such as object detection, segmentation, etc. and we want to encourage researchers to focus on the high-level end tasks. However, if we feel the community needs such annotations, we can provide them within a few weeks.

**Comment by parsa-m** [comment]
It would be great if it could be made available thanks

**Comment by danielgordon10** [comment]
We are working on adding this to newer versions. If you want to try adding it yourself, look at https://bitbucket.org/Unity-Technologies/ml-imagesynthesis

**Comment by ekolve** [comment]
This is now available.  Here is an example for how to enable it:

```python
controller.reset('FloorPlan28')
event = controller.step(dict(action='Initialize', renderObjectImage=True, renderClassImage=True))
event.instance_segmentation_frame # segmented by distance object
event.class_segmentation_frame # segmented by class
```

For additional documentation see: http://ai2thor.allenai.org/tutorials/event-metadata

**Comment by parsa-m** [comment]
Great thanks
