### ISSUE TITLE
Teleport and TeleportFull moves the agent out of the scene!

### ISSUE THREAD

**Issue by hqm** [allenai/ai2thor#234]
When I try to use the Teleport or TeleportFull actions, no matter what y value I set, the agent y position always ends up with the value -39.24

event = controller.step(dict (action='Teleport', x=0.0,y=0.0,z=0.0))
>>> event.metadata['agent']['position']
{'x': 0.0, 'y': -39.24, 'z': 0.0}

This puts the agent somewhere outside the room and cannot be moved back

Running ai2thor release version 2.01, on MacBook OSX Mojave 10.14.5

**Comment by hqm** [comment]
It looks like the problem was a zero value for y property, if I give it a value of y=1.0, then the agent seems to be happy to appear in the scene. I guess y=0 is an illegal value inside the floor or something?

**Comment by winthos** [comment]
Yes, if a Y value is low enough, the Agent will clip into the ground geometry of the scene and cause it to fall through the floor, which explains the extreme negative Y value you got originally.

The Teleport actions can be used to warp the Agent out of bounds as there are no restrictions imposed on the x, y, z values. This is why it is suggested to use the Teleport actions in tandem with the GetReachablePositions action to ensure you don't clip out of bounds.

**Comment by mattdeitke** [comment]
Closing this as it appears to be solved by using `GetReachablePositions` or using an event's metadata to access the `y` value for Teleport.

If there are any follow-ups, feel free to re-open :)
