### ISSUE TITLE
Boundary Box and Visibility issues in Scenes 1 and 401

### ISSUE THREAD

**Issue by rkruegs123** [allenai/ai2thor#235]
This issue is likely applicable to other scenes, but these are the ones I have come across it in. The issue is the following:

In Floorplan1 I cannot get the boundary boxes or shelves to be visible and/or get boundary boxes. For example, 'CounterTop|-00.08|+01.15|00.00' can be visible but I cannot get a boundary box for it with instance_detections2D. Another example is 'Shelf|+01.80|+00.87|-02.56' which I cannot get to be visible OR get a boundary box for.

I have a related problem in Floorplan401. For objectID 'Plunger|+00.36|+00.00|+02.47' I can get a boundary box with event.instance_detections2D, but it does not appear visible.

I should note that for all instances I checked that the visibility distance was achieved, there were no obstructing objects (which should especially not be the case for a shelf or countertop), and that it is within the camera's viewport.

As a summary, I have three examples. One in which visibility is achieved but a boundary box is not provided, a second in which neither visibility nor a boundary box is achieved, and a third where visibility is not achieved but a boundary box is provided.

I can provide more evidence if need be.

**Comment by rkruegs123** [comment]
Correction - the shelf is sometimes visible, but not always in the conditions that it should be.

**Comment by winthos** [comment]
The boundary box/instance_detections2D issue with objects like Countertops and Shelves has a fix in development at the moment, so in a future release that should be fixed.

As for the plunger, could you provide some more information about that so we can take a look on our end? The agent's position coordinates and camera angle would be good so we can replicate the exact image that you were looking at.

**Comment by rkruegs123** [comment]
{'bounds3D': None,
 'cameraHorizon': 60.0000076,
 'currentTime': 0.0,
 'distance': 0.0,
 'isopen': False,
 'istoggled': False,
 'name': 'agent',
 'objectId': None,
 'objectType': None,
 'openable': False,
 'parentReceptacle': None,
 'parentReceptacles': None,
 'pickupable': False,
 'pivotSimObjs': None,
 'position': {'x': -0.75, 'y': 0.9016162, 'z': 2.5},
 'receptacle': False,
 'receptacleCount': 0,
 'receptacleObjectIds': None,
 'rotation': {'x': 0.0, 'y': 90.0, 'z': 0.0},
 'toggleable': False,
 'visible': False}

The plunger is not visible but has a boundary box and mask. Thank you - please let me know if you need more information.

**Comment by winthos** [comment]
hmm, what version of THOR are you using to generate that? The list of object metadata attributes looks out of date compared to the most up to date version. For example, pivotSimObjs should not be showing up at all if you are on the current release. Depending on your version, the Plunger object may or may not be fully compatible with the new Visibility system.

Please let me know if you are getting these results and you are on the current version of THOR. Testing on my end with those exact position/rotation/cameraHorizon values for the Agent has the Plunger as visible = true.

**Comment by rkruegs123** [comment]
You are right - I was using an earlier version. Thank you.
