### ISSUE TITLE
Is there a way to obtain depth map from the Scene

### ISSUE THREAD

**Issue by roxanneluo** [allenai/ai2thor#24]
Hi,

The api provides us access to the color image. I'm wondering whether we can access the depth map, too.

**Comment by danielgordon10** [comment]
We are working on adding this to newer versions. If you want to try adding it yourself, look at https://bitbucket.org/Unity-Technologies/ml-imagesynthesis

**Comment by eric-yyjau** [comment]
I think there's some problem about the depth frame (event.depth_frame).
As shown below:
- Original frame
<img src="https://user-images.githubusercontent.com/17765629/42866798-2cd327e6-8aa0-11e8-8127-83d6e9deb805.png" width="200" height="200" />
- Depth frame 
<img src="https://user-images.githubusercontent.com/17765629/42866792-27610120-8aa0-11e8-94b4-926c50a6f37c.png" width="200" height="200" />

**Comment by danielgordon10** [comment]
Can you post your code? It looks OK when I try it.
Make sure to rescale your depth values before displaying them to be 0-255 and of type np.uint8 rather than floats.

**Comment by eric-yyjau** [comment]
Thank you for your reply.
- The code:
```python
import ai2thor.controller
from PIL import Image

controller = ai2thor.controller.Controller()
controller.start()

controller.reset('FloorPlan28')
event = controller.step(dict(action='Initialize', renderDepthImage=True, gridSize=0.25))
event = controller.step(dict(action='TeleportFull', renderDepthImage=True, x=-1.25, y=1.00, z=-1.5, rotation=90, horizon=30.0))
img = Image.fromarray(event.depth_frame / 20) # rescale image
print(event.depth_frame.shape)
img.show(title='Depth') 
```
I rescaled the array and show with PIL.

**Comment by tinytangent** [comment]
This bug is still not fixed on AI2Thor for Mac OS.

**Comment by FutureXiang** [comment]
## BUG FIX: depth_frame values error on AI2THOR for MacOS :

- You need to **download the data** zip of the exact same version **on Linux64**.  
For example, `thor-201909171243-OSXIntel64.zip` refers to `thor-201909171243-Linux64.zip`.

- Then unzip the file and **replace** all the files on **MacOS** @
`~/.ai2thor/releases/thor-201909171243-OSXIntel64/thor-201909171243-OSXIntel64.app/Contents/Resources/Data/*`
**with** those for **Linux64** @
`thor-201909171243-Linux64_Data/*`.

For example, `thor-201909171243-Linux64.zip` can be downloaded [here](http://s3-us-west-2.amazonaws.com/ai2-thor/builds/thor-201909171243-Linux64.zip).
You can replace the version code in the link for previous versions.

**Comment by ekolve** [comment]
Closing - the issue with depth on MacOS is fixed with the most recent release.
