### ISSUE TITLE
Set all containers to "open"

### ISSUE THREAD

**Issue by JSR694** [allenai/ai2thor#241]
Hi there,

I want to open all of the containers in a scene, before running
experiments in it.  Is there an easy way to do this, maybe modifying a
config file somewhere?  Right now my strategy is to manually move the
agent to each closed container and open it.

Thanks!

Jack

**Comment by winthos** [comment]
Hello! 
A new function that allows all objects with different states to be set on initialization is in the works. Please expect it in the next release, which should be relatively soon. For now, you will have to manually move to each container.

**Comment by JSR694** [comment]
Thanks, I appreciate the prompt response!

**Comment by ekolve** [comment]
Instead of moving to each container, you can also pass the parameter 
```
forceVisible=True
```
with the action:
```python
controller.step(action=dict(action='OpenObject', objectId=<objectId>, forceVisible=True))
```
