### ISSUE TITLE
How to not render RGB images?

### ISSUE THREAD

**Issue by rkruegs123** [allenai/ai2thor#247]
Is there a way to still get the instance masks, cv2img, scene, etc, when using headless mode?

---

As a follow up to the above issue, will there be any functionality in the future that returns the masks/images/etc, but just does render the images?

I am trying to find a way to get some speed up. I get significant speed up in headless mode, but still want the information that you get from the images. If rendering the images is a bottleneck, I think it would be useful to have a feature that allows you to bypass that.

Just a thought. Please let me know if this functionality exists or if there are plans for it in the future.

**Comment by ekolve** [comment]
When running in headless mode Unity doesn't render anything so there is no way to get the masks.

**Comment by rkruegs123** [comment]
Gotcha - thank you.

**Comment by rkruegs123** [comment]
As a follow up to the above issue, will there be any functionality in the future that returns the masks/images/etc, but just does _render_ the images?

I am trying to find a way to get some speed up. I get significant speed up in headless mode, but still want the information that you get from the images. If _rendering_ the images is a bottleneck, I think it would be useful to have a feature that allows you to bypass that.

Just a thought. Please let me know if this functionality exists or if there are plans for it in the future.

**Comment by ekolve** [comment]
You can experiment with setting the renderImage parameter to True/False on a per action basis:

```python
controller.step(action=dict(action='MoveAhead', renderImage=False)) # don't send the image
controller.step(action=dict(action='MoveRight', renderImage=True)) # send the image
```

**Comment by mattdeitke** [comment]
Closing as this appears solved :)
