### ISSUE TITLE
Controller.stop() in Thor versions >= 2.0.0

### ISSUE THREAD

**Issue by rkruegs123** [allenai/ai2thor#248]
I have recently upgraded to thor 2.0.1 from version 1.x.x and controller.stop() is not working. Is this a known issue? Are there any workarounds?

**Comment by roozbehm** [comment]
Could you explain more? What errors do you get?

**Comment by ekolve** [comment]
I am able to reproduce this - I should have a fix for this shortly.

**Comment by ekolve** [comment]
I just released version 2.0.2 to address this - please upgrade to confirm that resolves your issue.

**Comment by rkruegs123** [comment]
All set - thank you!
