### ISSUE TITLE
How can I get the .h5 file for all scenes

### ISSUE THREAD

**Issue by Savager-xiao** [allenai/ai2thor#249]
How can I get the .h5 file for all scenes just like this:
bathroom_02.h5
bedroom_04.h5
kitchen_02.h5
living_room_08.h5

**Comment by roozbehm** [comment]
We have released them in [this page](https://github.com/allenai/savn). Note that they do not include interactions.

**Comment by xjz89982** [comment]
> We have released them in [this page](https://github.com/allenai/savn). Note that they do not include interactions.

@roozbehm Hello roozbehm, thanks for the work you have done. Does the h5 file only contain image information? Is something else like position of the agent , or which objects are visible available ?

**Comment by roozbehm** [comment]
yes, the files include object visibility and agent position.

**Comment by ekolve** [comment]
Closing as issue appears to be resolved.
