### ISSUE TITLE
Any tips to toggle the visibility of objects?

### ISSUE THREAD

**Issue by SamsonYuBaiJian** [allenai/ai2thor#251]
My goal is to obtain 100% visibility/no occlusion of a target object from a certain angle, and I would like to make all other objects in the scene invisible to do so.

Removing all other objects from the scene with the RemoveFromScene action might lead to a pickupable target object  falling out of frame, so it doesn't work very well.

Thank you.

**Comment by winthos** [comment]
By all other objects, do you mean the environmental structures as well? For example, if there was a Tomato object on the counter that you want to have no occlusion to, would you want the counter that it is sitting on, the floor, walls etc, to all turn invisible so that it's just the tomato and the skybox of the scene rendered?

**Comment by Lucaweihs** [comment]
Hi Samson,

Try the following

```
controller.step({"action":"EmphasizeObject", "objectId":OBJECT_ID_OF_THE_TARGET_OBJECT"})
```

This should hide all other objects in the scene and mask the target object with the magenta color (so you can figure out which pixels correspond to the object by comparing the frame to `numpy.array([[[255, 0, 255]]])`. You can then run

```
controller.step({"action":"UnemphasizeAll"})
```

which will undo the `EmphasizeObject` action or you can run

```
controller.step({"action":"UnmaskObject", "objectId":OBJECT_ID_OF_THE_TARGET_OBJECT"})
```

which will remove the magenta mask of the target object so you can get the actual pixel values corresponding to it.

**Comment by SamsonYuBaiJian** [comment]
Thank you guys for the help! @winthos That was my initial plan, but the solution provided by @Lucaweihs works well for me too. This issue can be closed.
