### ISSUE TITLE
Invisible agent and using multiple ThirdPartyCamera

### ISSUE THREAD

**Issue by Bilel12** [allenai/ai2thor#265]
Hi, 

Please if someone can help me:
1- I want to make the agent invisible. 
2- Using multiple ThirdPartyCameras-> simple example.

Thanks in advance.

**Comment by roozbehm** [comment]
You can use the following command at initialization to make the agent invisible: 
`self.controller.step({"action": "Initialize", "makeAgentsVisible": False,})`

We will add an example for ThirdPartyCameras to the documentation soon.

**Comment by Bilel12** [comment]
Another question please, are the x, y ,z coordinates in meter scale ? 

event= controller.step(dict(action='AddThirdPartyCamera',thirdPartyCameraId=0, rotation=dict(x=30.0, y=30, z=0.0), position=dict(x=-1.25, y=1.5759992, z=-1.00)))

**Comment by roozbehm** [comment]
yes, they are in meters.
