### ISSUE TITLE
Screen Resolution

### ISSUE THREAD

**Issue by Bilel12** [allenai/ai2thor#267]
Hi,

Please, how to modify the screen resolution as any type I want  "width* height" 
for example 900 x 800 ?
thanks in advance

**Comment by roozbehm** [comment]
You can do the following after `reset` function:
`    controller.step({'action': 'ChangeQuality', 'quality': 'High'})
    controller.step({"action": "ChangeResolution", "x": 900, "y": 800})
`
Note that rendering higher resolution images is slower.
