### ISSUE TITLE
Is there a way I can get contact force experienced by the object in the scene?

### ISSUE THREAD

**Issue by gsp-27** [allenai/ai2thor#279]
When the agent interacts with the object, it exerts certain force on the object. Is there a way I can get the force experienced by the object?

In MuJoCo we can simulate contact forces using ```sensors``` functionality, is there something in the similar vein.

Many thanks

**Comment by winthos** [comment]
the only interactions that apply force to objects are the `Throw`, `Push`, and `Pull` actions. The `moveMagnitude` parameter in each of those actions is effectively the amount of newtons being applied during the Throw/Push/Pull. There is not currently a way to expose the force that the object would experience say, after being thrown and bouncing around or even hitting another object.

**Comment by gsp-27** [comment]
Thanks for the information.

But is there any possibility that suppose if a robotics hand/gripper comes in contact with the object, then if required the contact force can also be accessed?

Many thanks
