### ISSUE TITLE
Physics broken in room 223

### ISSUE THREAD

**Issue by YangZhang4065** [allenai/ai2thor#28]
Hi, part of the walls are not physical entities in FloorPlan 223. And the result is that the agent could move freely through the wall without any obstacles. This happens when the agent keeps moving ahead right after default initialization.

Minimum code to reproduce the error (on my ubuntu machine):
```python
import ai2thor.controller

GRID_SIZE=0.5

controller = ai2thor.controller.Controller()
controller.start()
controller.reset('FloorPlan223')
controller.step(dict(action='Initialize', gridSize=GRID_SIZE))
for i in range(10):
    controller.step(dict(action='MoveAhead'))
```

**Comment by ekolve** [comment]
Could you send me the following? Immediately after calling Initialize:
```python
event = controller.step(dict(action='Initialize', gridSize=GRID_SIZE))
print(event.metadata['agent']['position') # Add this to the 
```
and at the point just prior to passing through the wall from the 'MoveAhead' action print out the agent position again and send that. If you can capture grab the image as well that would be helpful.

I checked all the walls for that and couldn't find any part that was missing a collider - as well I used a different agent to manually control the movement and explored the entire room and couldn't find a spot that allowed me to pass through.

**Comment by YangZhang4065** [comment]
Sure. Here are the images&locations of the agents upon initialization, before crossing the wall and after crossing the wall.

```python
import ai2thor.controller
from matplotlib import pyplot as plt

GRID_SIZE=0.5

controller = ai2thor.controller.Controller()
controller.start()
controller.reset('FloorPlan223')
event=controller.step(dict(action='Initialize', gridSize=GRID_SIZE))
#initialization
print(event.metadata['agent']['position'])

{'y': 1.0, 'z': -0.5, 'x': -1.0}

plt.imshow(event.frame, interpolation='nearest')
plt.show()

```

![image](https://user-images.githubusercontent.com/8459167/35824040-6430fa70-0a66-11e8-989f-7c8d559b8859.png)

```python
#two steps before acrossing the wall
for i in range(5):
   event=controller.step(dict(action='MoveAhead'))
print(event.metadata['agent']['position'])

{'x': -1.0, 'y': 0.9800000190734863, 'z': 2.0}

plt.imshow(event.frame, interpolation='nearest')
plt.show()
```

![image](https://user-images.githubusercontent.com/8459167/35823797-9d6ba52a-0a65-11e8-94ca-18c806ac3234.png)

```python
#right before acrossing the wall
event=controller.step(dict(action='MoveAhead'))
print(event.metadata['agent']['position'])

{'x': -1.0, 'y': 0.7721520662307739, 'z': 2.5}

plt.imshow(event.frame, interpolation='nearest')
plt.show()
```

![image](https://user-images.githubusercontent.com/8459167/35823939-0c3faf3c-0a66-11e8-8885-0c1ccc1fdeb9.png)

```python
#right after acrossing the wall
event=controller.step(dict(action='MoveAhead'))
print(event.metadata['agent']['position'])

{'x': -1.0, 'y': -5450.7158203125, 'z': 3.0}

plt.imshow(event.frame, interpolation='nearest')
plt.show()
```

![image](https://user-images.githubusercontent.com/8459167/35823953-1a042a62-0a66-11e8-8121-4871d26e914e.png)

**Comment by ekolve** [comment]
Hmm, I can't seem to get the agent to cross through.  Can you confirm which version of ai2thor you are using?

**Comment by ekolve** [comment]
Okay, I am able to reproduce this now.

**Comment by ekolve** [comment]
Issue is fixed with latest release, please upgrade to version 0.0.14

**Comment by YangZhang4065** [comment]
Thank you!
