### ISSUE TITLE
How to make things unbreakable?

### ISSUE THREAD

**Issue by jiafei1224** [allenai/ai2thor#282]
Is there any way to make an object such as an egg unbreakable when it is being dropped from a certain height?

**Comment by winthos** [comment]
There is not currently a way to prevent the automatic breaking when using `Drop/Throw` actions. If you use the `PutObject` action, no force will actually be applied and the egg won't break. We will look into adding an option to make all objects unbreakable in a future release.

**Comment by roozbehm** [comment]
We have added a new action in our latest release to make objects unbreakable. For example, the following command makes all eggs unbreakable:
`controller.step(dict(action = 'MakeObjectsOfTypeUnbreakable', objectType = "Egg")`

**Comment by mattdeitke** [comment]
Closing as this appears to be solved :)
