### ISSUE TITLE
How to build local-build for Ubuntu 18.04?

### ISSUE THREAD

**Issue by SamsonYuBaiJian** [allenai/ai2thor#283]
Hi there, how do I build local builds for Ubuntu 18.04 after I've changed the scene(s)?

I've inserted an object, changed the property structure to that of AI2-THOR's objects, and used "Build And Run" in Windows 10 Unity 2018.3.6f1.

![Capture](https://user-images.githubusercontent.com/36767958/63417510-fee04e80-c433-11e9-88c8-76859c12c11d.JPG)

**Comment by jiafei1224** [comment]
Same issue. Please help.

**Comment by xjz89982** [comment]
@SamsonYuBaiJian Hello, how did you solve this problem? Thanks.

**Comment by SamsonYuBaiJian** [comment]
@xjz89982 Hi there, so the best way would be to download Unity Hub and the compatible version of Unity Editor for Linux. Then, you build it with the Linux build option. This will give you a file in the form of "build_file.x86_64". After this, you can just follow the AI2-THOR Unity Development instructions, like:
controller = ai2thor.controller.Controller()
controller.local_executable_path = "/path/to/file/build_file.x86_64"
controller.start()

If you would prefer to build on Windows, the same instructions apply but you still build with the Linux build option. This is not recommended, since AI2-THOR works better on Linux, and you would have to transfer the builds around, which takes some time.

**Comment by xjz89982** [comment]
@SamsonYuBaiJian Thanks for your reply. So i should make my change and then just build it in Unity Editor, in another words, don't need to run the command `invoke local-build` right? This command makes me confused.

Besides, does the version of Unity Editor matter? I want to install 2018.3.6f1 version for Linux by Unity Hub, but everytime i try to install, i got a message "The server is currently unresponsive", eventhough my internet connection looks good. Now there is a Unity Editor version 2018.3.0f2 in my pc, which is downloaded by standalone installer. If i try to open ai2thor with it, i get a warning:
`The saved project (2018.3.6f1) does not match the launched editor (2018.3.0f2).
This may require re-import. Please be aware that opening in an older version is unsupported.
Note that if a build target installation is missing, this may also cause a re-import.
If you proceed, some packages may be updated. For a list of any changes made to your Project’s packages, see the Logs/Packages-Upgrade.log file in your Project folder.`

**Comment by SamsonYuBaiJian** [comment]
@xjz89982 Yeah you don't need to run the command `invoke local-build`, you just have to build for Linux in the Unity Editor.

For the Unity Editor version issue, I haven't encountered it before and haven't tried a different version, so I'm not sure whether the re-import will raise any issues.

You can try getting Unity Hub from https://forum.unity.com/threads/unity-hub-v-1-6-0-is-now-available.640792/?_ga=2.150645878.110175512.1576169181-313789176.1576169181 and getting the past versions from https://unity3d.com/get-unity/download/archive by clicking on the "Unity Hub" option.

**Comment by xjz89982** [comment]
@SamsonYuBaiJian OK, thank you for your help. I really appreciate it. Have a nice day. :)
