### ISSUE TITLE
Field of View for the ThirdPartyCamera

### ISSUE THREAD

**Issue by Bilel12** [allenai/ai2thor#284]
Hi,

Is there a way to change the FieldOfView for the ThirdPartyCamera?
I know that FieldOfView parameter is for the agent’s camera only.

Thanks in advance,

**Comment by winthos** [comment]
currently you cannot change FOV when adding a third party camera. We will add this option in a future release.

**Comment by ekolve** [comment]
FOV can now be specified for a thirdpartycamera: https://ai2thor.allenai.org/ithor/documentation/actions/miscellaneous-actions/#addthirdpartycamera
