### ISSUE TITLE
Is there a way to find the shortest path within this env?

### ISSUE THREAD

**Issue by juny116** [allenai/ai2thor#29]
Hello I'm student who is trying to train a navigation agent based on the shortest path algorithms like A*.
How can I use those algorithms within this env? Any algorithm would be fine.
Moreover If it is possible, can I get a simple sample code for BFSController? 
Thanks

**Comment by ekolve** [comment]
You can use the BFSController as follows:

```python
import ai2thor.controller
controller = ai2thor.controller.BFSController()
controller.start()
controller.search_all_closed('FloorPlan1') # provide the scene name you want a grid for here
print(controller.grid_points)
```
grid_points is a list of dictionaries with x,y,z values for the points on the grid.  Currently, the grid_size is hardcoded in controller.py#search_all_closed to 0.25 - but if you take a look at the code you can either extract it out or if needed I can make a change to accept a grid_size parameter.

Calling the method ```controller.build_graph()``` will return a Networkx graph (you must pip install networkx or this will fail).

Depending on how you would like to traverse the graph the method: controller.shortest_plan(graph, agent, target) may work for you.  Though, it basically just calls this method on the networkx graph:
```python
import networkx as nx
# graph is the structure returned from controller.build_graph()
# this will return a sequence of points indicating the shortest path
nx.shortest_path(graph, controller.key_for_point(agent['position']), controller.key_for_point(target['position']))
```
key_for_point just turns the x,y,z point into a string/key for the graph.

Let me know if you have any issues with this.

**Comment by shamanez** [comment]
What is the Y coordinate in the dictionary? Is it the height of the person?

**Comment by uiyo** [comment]
search_all_close() will report error when append unreachable(agent collide) point to grid_points. Any solution?
