### ISSUE TITLE
Setting individual object locations

### ISSUE THREAD

**Issue by SamsonYuBaiJian** [allenai/ai2thor#292]
Hi there, I would like to set the locations of individual objects for specific tasks.

I've seen a similar thread here: https://github.com/allenai/ai2thor/issues/116, which mentions that I have to do it in with C# scripts in Unity.

Could you provide some guidance as to which script(s) should be edited in Unity to do so?

Thank you.

**Comment by winthos** [comment]
This feature is still being actively developed, but if you want to make your own version you will need to create a new function in the `PhysicsRemoteFPSAgentController.cs` script. 

For a quick overview, all actions that the Agent can perform are just functions that take a `ServerAction` as a parameter. The name of the function in c# corresponds to the string name used from python. For example, using `MoveAhead` from python:

```event = controller.step(dict(action='MoveAhead'))```

This calls a function of the same name MoveAhead(ServerAction action): https://github.com/allenai/ai2thor/blob/master/unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs#L1610

To make your own custom action, you will need to add it to that PhysicsRemoteFPSAgentController script.

**Comment by SamsonYuBaiJian** [comment]
Hi there, how do I then register the new custom action?

The AI2-THOR controller (controller.step) does not recognise my new action in PhysicsRemoteFPSAgentController.cs.

Thank you.

**Comment by SamsonYuBaiJian** [comment]
Thank you!
