### ISSUE TITLE
Trainning on server

### ISSUE THREAD

**Issue by jiafei1224** [allenai/ai2thor#293]
How to train on server while still display the unity window?

**Comment by roozbehm** [comment]
Can you explain what exactly you are planning to do? You can use VNC to connect to the machine.

**Comment by jiafei1224** [comment]
I would like to train the RL model with Ai2thor env on a remote server without a GUI?

**Comment by roozbehm** [comment]
You should start the X server on the remote machine. [This script](https://gist.github.com/roozbehm/7abfaa3db4520da229ac79f38f8994b0) is an example of how to start the X server. Make sure to run as root if you want to use this script.

**Comment by sjtuytc** [comment]
I did as you told but still encountered problem.
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  84
  Current serial number in output stream:  85
Can you help me?

**Comment by sjtuytc** [comment]
@roozbehm

**Comment by michaelyu0906** [comment]
You could run a xserver with --use-display-device=None option, details in https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-on-Amazon-Web-Service.md.
@sjtuytc

**Comment by JethroJC** [comment]
@sjtuytc Hi, did you solve it? I run X server using the proposed script and meet the same error as you.

**Comment by sjtuytc** [comment]
> @sjtuytc Hi, did you solve it? I run X server using the proposed script and meet the same error as you.
No I didn't.

**Comment by ekolve** [comment]
We have just released a mini-framework to make running with Docker much simpler.  You can take a look at https://github.com/allenai/ai2thor-docker.  You need to have a Nvidia GPU and docker installed - if you have that all the X server configuration is done for you.

**Comment by mattdeitke** [comment]
Merging with #105.
