### ISSUE TITLE
Position meaning

### ISSUE THREAD

**Issue by rkruegs123** [allenai/ai2thor#294]
How do you relate the position of objects to the screen size? How large is the "grid"?

**Comment by winthos** [comment]
Could you provide more information about your question? Is this related to 3D to 2D projections?

**Comment by mattdeitke** [comment]
This issue may be solved in https://github.com/allenai/ai2thor/issues/445#issuecomment-673782904, but it's hard to say. If there are any follow-ups, feel free to re-open :)
