### ISSUE TITLE
Topdown View Floorplan21

### ISSUE THREAD

**Issue by rkruegs123** [allenai/ai2thor#295]
The topdown view of floorplan 21 does not work.

**Comment by rkruegs123** [comment]
FloorPlan 26 has the same issue.

**Comment by winthos** [comment]
Could you provide some more details? Does the action fail completely or does the topdown image just look incorrect? If you could include screenshots that would be helpful to debug the issue.

**Comment by Tushar-N** [comment]
![FloorPlan26](https://user-images.githubusercontent.com/4995097/72933883-43944c80-3d28-11ea-9c5f-2c97fd5ac22b.png)

^ This is what Floorplan26 looks like. FloorPlan21 looks fine to me.

**Comment by mattdeitke** [comment]
Merging ToggleMapView discussion with #445. I believe this issue should be solved though :)
