### ISSUE TITLE
Cannot move with object on the receptacle

### ISSUE THREAD

**Issue by jaejaywoo** [allenai/ai2thor#301]
Hi,

I was playing around with the environment and realized that when receptacles like plate or pan have an object (such as egg or potato) placed on them, the 'Pickup' action for picking up those receptacles works but moving around with them through 'Move' or 'Rotate' actions are not possible. The only action that works is 'MoveBack' action, and it happens over multiple floorplans in the Kitchen scene. I've tried the floorplan 2, 3, and 4, and they all had the same issue. Is there any way to fix this issue?

Thank you.

**Comment by winthos** [comment]
we have just pushed a new release (2.1.1) that fixes this issue. Please update it it should be resolved!
