### ISSUE TITLE
Unity WebGL

### ISSUE THREAD

**Issue by jiafei1224** [allenai/ai2thor#304]
Hi, am i able to export build of the room to do a Unity WebGL? Some like the Ai2thor demonstration WebGL, but for only one room.

**Comment by AlvaroHG** [comment]
Yes, you can do that by calling the `webgl-build` invoke task under the root directory:
```
invoke webgl-build --scenes=FloorPlan8_physics
````
The `scenes` parameter can take a comma separated list of the rooms you want on your build. The build will be under `./unity/builds/` directory, which can also be configured by the `directory` parameter of the invoke task.
