### ISSUE TITLE
Rotation angle

### ISSUE THREAD

**Issue by jiafei1224** [allenai/ai2thor#305]
Is there a way to rotate left or rotate right at a degree instead of just a straight 90 degree rotation?

**Comment by roozbehm** [comment]
You can use `TeleportFull` action and pass in any rotation angle.

**Comment by jiafei1224** [comment]
Is there any other approach besides teleportfull?

**Comment by roozbehm** [comment]
No, not at the moment. What is the issue with TeleportFull?

**Comment by jiafei1224** [comment]
It will hang after moving for awhile

**Comment by jiafei1224** [comment]
When rotated to an angle and start moving, there is a chance to get struck into an object.

**Comment by winthos** [comment]
The latest release version 2.4.0 allows for degrees of rotation not restricted to 90 degrees.
