### ISSUE TITLE
Inserting prefab into scene at runtime

### ISSUE THREAD

**Issue by SamsonYuBaiJian** [allenai/ai2thor#309]
Hi, I would like to insert object prefabs at runtime in positions that do not overlap with existing SimObjs in the scene, regardless of whether the receptacles make sense, by only checking for collisions.

I'm using PhysicsSceneManager's AddToObjectsInScene method to insert prefabs into the scene at runtime, but it spawns at (0,0,0) without checking for collisions, e.g.
`GameObject go = Instantiate (Resources.Load (prefab)) as GameObject;`
`physicsSceneManager.AddToObjectsInScene(go.GetComponent<SimObjPhysics>());`

I have tried adapting PhysicsRemoteFPSAgentController's getReachablePositions method to get reachable positions for my target objects, but it is not working out. I'm not very experienced with Unity.

Do you have any suggestions for this matter?

Thank you.

**Comment by winthos** [comment]
The `AddToObjectsInScene` method is a helper function used on the backend of the framework, It can't make objects appear using collision checks. What you are doing is instantiated a prefab which defaults to placing it the world origin. Currently there is no functionality to spawn in objects to a scene that are not already in the scene and also have it respect collisions.

We are looking to add this functionality in a future release, but in the meantime you would need to write custom scripts in Unity to achieve this. You can take a look at the `InitialRandomSpawn` function in the `PhysicsRemoteFPSAgentController` script [here](https://github.com/allenai/ai2thor/blob/master/unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs#L3684) and follow the calls to get an idea about how to position objects with respect to collision.
