### ISSUE TITLE
Randomize only one object

### ISSUE THREAD

**Issue by jiafei1224** [allenai/ai2thor#315]
Is it possible to randomize the position of one object? And how many different version does randomseed goes?

**Comment by winthos** [comment]
It's not currently possible to randomize a single object. As for the randomseed... I guess it technically has as many variations as there are ints to parameterize so 2.14 billion?

**Comment by ekolve** [comment]
This should be possible using [InitialRandomSpawn](https://ai2thor.allenai.org/ithor/documentation/objects/object-randomization/#initial-random-spawn) by passing in all but the single objectId you want to randomize to the `excludeObjectIds` parameter.

**Comment by ekolve** [comment]
closing - issue appears to be resolved.
