### ISSUE TITLE
Is there a way to view env in local with mouse and keyboard?

### ISSUE THREAD

**Issue by punnpkin** [allenai/ai2thor#320]
Using code to browse is inconvenient..

**Comment by winthos** [comment]
you can explore some of the environments with our online [web demo](https://ai2thor.allenai.org/demo/), or you can download and install the Unity editor to browse through the scenes. Make sure to install the correct version of the Editor, as we are compatible with Unity version 2018.3.6 which you can find in the [Unity Download Archive](https://unity3d.com/get-unity/download/archive).

**Comment by Tushar-N** [comment]
There's also the `controller.interact()` if you want simple keyboard control.
https://github.com/allenai/ai2thor/blob/master/ai2thor/controller.py#L482

**Comment by punnpkin** [comment]
> There's also the `controller.interact()` if you want simple keyboard control.
> https://github.com/allenai/ai2thor/blob/master/ai2thor/controller.py#L482

let me give it a try

**Comment by XiaoLiSean** [comment]
It appears that the AI2THOR documentation website has been updated recently and I could not manage to find the previous web demo page. I would appreciate it if you could point me to the right link. Thanks in advance!

**Comment by mattdeitke** [comment]
Hey, I'll update this thread soon when I add it in. I was holding off on the moment to try and add RoboTHOR scenes to the demo, in addition to the iTHOR scenes that used to be on it, but that part can be pushed back until after.

**Comment by mattdeitke** [comment]
The demo is now available at https://ai2thor.allenai.org/demo 😄

**Comment by Eugleo** [comment]
@mattdeitke Hey, is the full range of interactions possible in the demo? I couldn't figure out how to slice an apple, for example. Thanks!

**Comment by Hanqi7921** [comment]
> The demo is now available at https://ai2thor.allenai.org/demo 😄

hi! shall we have a look at the demo code about how to initialize a complete simulator platform.It's still difficult for me to rebuild a platform from scratch.Or how to use ai2thor COMPLETELY.THANK YOU!

**Comment by basteran** [comment]
Hi @punnpkin , do you have any news about it? It seems a very interesting functionality!
