### ISSUE TITLE
Run with docker_enabled=True return event.frame==None

### ISSUE THREAD

**Issue by shuyanzhou** [allenai/ai2thor#328]
Hi,

It seems the env.last_event.IMAGE_RELATED_ATTRIBUTES (e.g. frame) are None with docker_enabled=True. 
```python
import ai2thor.controller
controller = ai2thor.controller.Controller()
controller.docker_enabled = True
controller.start()
# can be any one of the scenes FloorPlan###
controller.reset('FloorPlan28')
controller.step(dict(action='Initialize', gridSize=0.25))
controller.step(dict(action='RotateRight'))
controller.last_event.frame == None # True
```

How could I get image-related attributes with docker?

Thanks!

**Comment by JethroJC** [comment]
@shuyanzhou Hi, I meet the same error as you. Have you solved it now?

**Comment by ekolve** [comment]
Please take a look at this: https://github.com/allenai/ai2thor-docker

It is a mini-framework to make running ai2thor in docker easier.
