### ISSUE TITLE
can't run ai2thor methods in OS X

### ISSUE THREAD

**Issue by ascourtas** [allenai/ai2thor#332]
It seems that I can't even a simple setup going in Mac OS X 10.14.6 (Mojave)? I've tried following the examples in the documentation, but even the following never finishes executing (it gets stuck at the second line of code). Any advice?

```
import ai2thor.controller

controller = ai2thor.controller.Controller(scene='FloorPlan28', gridSize=0.25)
event = controller.step(dict(action='MoveAhead'))
# Numpy Array - shape (width, height, channels), channels are in RGB order
event.frame
# Numpy Array in BGR order suitable for use with OpenCV
image = event.cv2image()
# current metadata dictionary that includes the state of the scene
print(event.metadata)
```

Also, is it true that this library is only compatible with Unity 2017.3.1?

**Comment by ekolve** [comment]
What version of ai2thor do you have installed?

The unity project is built using Unity 2018.3.6.

**Comment by wayne1029jihad** [comment]
This example isn't matching New version ai2thor 2.2.0
The changed their example but not change their code in 2.2.0
I have no idea why they do this.

the older example:
```
import ai2thor.controller                                                                                          
controller = ai2thor.controller.Controller()
controller.start()

controller.reset('FloorPlan28')
controller.step(dict(action='Initialize', gridSize=0.25))
# Numpy Array - shape (width, height, channels), channels are in RGB order
event.frame
# Numpy Array in BGR order suitable for use with OpenCV
image = event.cv2image()
# current metadata dictionary that includes the state of the scene
print(event.metadata)
```

**Comment by wayne1029jihad** [comment]
I can run older example in version 2.1.0.
The new example I can't execute on any version.
The older example:
```
import ai2thor.controller
controller = ai2thor.controller.Controller()
controller.start()
controller.reset('FloorPlan28')
controller.step(dict(action='Initialize', gridSize=0.25,cameraY=0.03))
event = controller.step(dict(action='MoveAhead'))
# Numpy Array - shape (width, height, channels), channels are in RGB order
event.frame
# Numpy Array in BGR order suitable for use with OpenCV
image = event.cv2image()
# current metadata dictionary that includes the state of the scene
print(event.metadata)
```

**Comment by mattdeitke** [comment]
Hey!

Please upgrade your version of AI2-THOR to 2.2.0. The syntax you are trying to use is introduced in that version. Basically `start()`, `step(action='Initialize')` and `reset` are merged when first initializing a `Controller`, and when `reset` is called, you no longer need to call `step(action='Initialize')`.

Related, which goes a little more in-depth at the differences #326.

**Comment by ascourtas** [comment]
@mattdeitke @ekolve  I am indeed running AI2-THOR 2.2.0, but still have the issues I previously described.

**Comment by ekolve** [comment]
Can you confirm you are running the latest version by adding this after your import statements?

print(ai2thor.__version__)

Its possible an old version exists in your pythonpath from an earlier installation.

**Comment by ascourtas** [comment]
sorry I didn't follow up earlier, the issue actually wound up being a mismatch between our ai2thor and unity versions. Ensuring I had the newest version of Unity, the newest version of AI2-THOR, and restarting my computer after install seemed to do the trick.
