### ISSUE TITLE
How to Execute Random Multi-Agent Actions?

### ISSUE THREAD

**Issue by zyzhang1130** [allenai/ai2thor#333]
I tried to modify the following example into two agent setting:

```python
from gym_ai2thor.envs.ai2thor_env import AI2ThorEnv
N_EPISODES = 20
env = AI2ThorEnv()
max_episode_length = env.task.max_episode_length
for episode in range(N_EPISODES):
    state = env.reset()
    for step_num in range(max_episode_length):
        action = env.action_space.sample()
        state, reward, done, info = env.step(action)
        if done:
            break
```

modified:

```python
from gym_ai2thor.envs.ai2thor_env import AI2ThorEnv
import ai2thor.controller
controller = ai2thor.controller.Controller()
multi_agent_event = controller.step(dict(action='Initialize', gridSize=0.25, agentCount=2))
N_EPISODES = 20
env = AI2ThorEnv()
max_episode_length = env.task.max_episode_length
for episode in range(N_EPISODES):
    state = env.reset()
    for step_num in range(max_episode_length):
        action = env.action_space.sample()
        state, reward, done, info = multi_agent_event(dict(action, agentId=0)) 
        state, reward, done, info = multi_agent_event(dict(action, agentId=1)) 
        if done:
            break
```

it returns the following error:
TypeError: 'int' object is not iterable

May I ask what is the right way to let different any to do random action?

Thank you.

**Comment by mattdeitke** [comment]
Hey!

I'm not super familiar with `gym_ai2thor`, but using the standard AI2-THOR framework to grab a random action, one could call:
```python
from ai2thor.controller import Controller
import random

# initialize controller with 2 agents
controller = Controller(scene='FloorPlan28', agentCount=2)

# define all the actions
actions = ['MoveAhead', 'RotateRight', 'RotateLeft']

# get random actions
action0 = random.sample(actions)
action1 = random.sample(actions)

# step with random actions
controller.step(action=action0, agentId=0)
controller.step(action=action1, agentId=1)
```

There is not really a set of all possible actions, as that depends on the scene and the location of an agent. Here, one could obviously change the action space by changing the `actions` list.

**Comment by zyzhang1130** [comment]
does it do the same thing as self.action_space.sample()?

**Comment by zyzhang1130** [comment]
May I ask does controller.step(action=action0, agentId=0) do the same thing as env.step(action, agentId=0) where action = env.action_space.sample() ? (does 'action = env.action_space.sample()' help to define all possible actions instead of manually adding actions into the list?)

**Comment by mattdeitke** [comment]
Hey, sorry for the late reply.

> does `controller.step(action=action0, agentId=0)` do the same thing as `env.step(action, agentId=0)`?

Yes. These are equivalent.
