### ISSUE TITLE
Can't find lidar senso

### ISSUE THREAD

**Issue by QLV5645-QLJ** [allenai/ai2thor#349]
Hi, Is there any possibility that we can use lidar sensor in AI2THOR simulation. Since in many real-world case, indoor-navigation application use lidar sensor as input.

**Comment by mattdeitke** [comment]
Hey. Yes we should have what you're looking for!

Lidar sensors are used in real-world applications to get estimated depth information about surrounding objects in an image. We call this capability a `depth image`, and depth images can be accessed by initializing a Controller with:
```
controller = Controller(renderDepthImage=True)
```
and then in each Event, you will have access to a depth image with:
```
event = controller.step(action='Pass')
event.depth_frame
```

**Comment by QLV5645-QLJ** [comment]
Thanks for your reply. Sounds good! 

Is there any way to get a 2D 360-degree sensor or 3d 360-degree sensor??

**Comment by winthos** [comment]
360 degree sensors are not currently supported.

**Comment by mattdeitke** [comment]
Moving the follow-up conversation to #444.

Feel free to re-open if there are any follow-ups on LiDar.
