### ISSUE TITLE
Does the agent itself has a field of view?

### ISSUE THREAD

**Issue by zyzhang1130** [allenai/ai2thor#358]
Hi, I would like to check does the agent itself has a field of view? In reality the robot agent is likely to be equipped with sensors, which allows it to recognize the objects within its F.O.V.. In the demo (https://ai2thor.allenai.org/ithor/demo/), whenever the mouse/cursor is pointed to some object with certain attributes (e.g. apple), the object name will be shown. So will the agent also be able to tell the objects appeared in its F.O.V. or it is totally blind and only able to tell the object until it interacts with it (e.g. open, pickup, etc.)?

**Comment by winthos** [comment]
The demo was made with some alterations to how the agent operates via python commands. The cursor pointing at an object and highlighting it is only there in the demo as a human interface, the actual way the agent renders and sees the environment is different.

The agent does have a field of view setting you can alter on the camera, the current default is a FOV of 90. As per the documentation, the agent will be able to "see" objects as long as they are within the `visibilityDistance` of the agent and are unobstructed by other objects. See the [concepts page](https://ai2thor.allenai.org/ithor/documentation/overview/concepts/) for more details on how the framework works, and see the [initialization](https://ai2thor.allenai.org/ithor/documentation/actions/initialization/) and [metadata](https://ai2thor.allenai.org/ithor/documentation/metadata/) pages for more information on what kind of images you can render, and how to retrieve them from event objects.

**Comment by zyzhang1130** [comment]
Thank you for the info. It is critical to what I am doing.
