### ISSUE TITLE
Coordinate System

### ISSUE THREAD

**Issue by playerkk** [allenai/ai2thor#36]
How are the coordinate system of x, y, z defined? What are their ranges? Thanks.

**Comment by roozbehm** [comment]
x and z are parallel to the ground plane and y is perpendicular to the ground plane. The range can be anything.

**Comment by playerkk** [comment]
Thanks for the reply. Where is the origin?

**Comment by roozbehm** [comment]
There is no specific rule for the origin. It can be anywhere in the scene.

**Comment by playerkk** [comment]
Thanks. Will close the issue.
