### ISSUE TITLE
partially obstructed sight

### ISSUE THREAD

**Issue by zyzhang1130** [allenai/ai2thor#361]
Hi, 
May I check with you what is the minimum area for an object to be blocked by other objects such that the agent could not see it even it is within the FoV?

Thank you

**Comment by winthos** [comment]
There is not a static minimum area that determines if an object is visible or blocked. Each object instance has a set of "visibility points" that are spread about the overall form of an object. If a raycast from the camera can hit any one of those points successfully, the object is considered visible. Depending on the size of the object and how close the agent is able to get to the object, the number of visibility points to check for each object will be different. 

An extremely rough estimate would be if 5-10% of an object's overall area is not obstructed, it will be visible. Again this is an extremely rough estimate as individual object instances will vary.

**Comment by zyzhang1130** [comment]
noted with thanks
