### ISSUE TITLE
Picking up one object from multiple

### ISSUE THREAD

**Issue by zyzhang1130** [allenai/ai2thor#362]
Hi, 
I would like to ask for the situation where the agent is about to pick one object from among multiple objects in a drawer.  Since the agent is facing the drawer and the drawer is relatively small, all objects in the drawer should have approximately the same distance from the agent. In this case would which object to be picked totally random?

**Comment by winthos** [comment]
No the object picked up would not be random.

If you check the PickupObject Action details in the [documentation here](https://ai2thor.allenai.org/ithor/documentation/actions/object-interaction/), you will see that it requires a target object’s string id as a parameter. In the case you are describing, the action would do nothing and not pickup either object until you specify which object you are attempting to pickup.

**Comment by zyzhang1130** [comment]
noted with thanks
