### ISSUE TITLE
object after broken blocks the path

### ISSUE THREAD

**Issue by zyzhang1130** [allenai/ai2thor#366]
Hi, I realize that when some object breaks and the shattered pieces are on the floor, it will block the agent from passing over. Neither can the pieces be picked up. The only exception I've encountered so far is egg (cracked egg can be picked up like a normal object). Is there any walk-around method to clear the path blocked by the pieces? There are certain scenes where the path is very narrow and one broken object can entirely block the passage.

Thanks.

**Comment by winthos** [comment]
Currently the broken object pieces cannot be picked up as the fragments are no longer classified as sim objects and are simply meshes with collision within the scene. The egg is an exception because breaking it spawns in an Egg Cracked object, which is still a manipulateable sim object. There is not any built in walk-around methods or any methods to clear pieces at this time, but we can work on building in that functionality in a future release.

**Comment by zyzhang1130** [comment]
noted. thank you for your reply.

**Comment by zyzhang1130** [comment]
Anyway, is there any way to disable certain actionable properties of an object (in this case, breakable) to suit specific tasks?

**Comment by winthos** [comment]
Yes, please look at the documentation under the ["Unbreakable" section here.](https://ai2thor.allenai.org/ithor/documentation/actions/initialization/). This allows you to toggle off the property that allows objects to be broken automatically when subject to enough force. Other actionable properties cannot be disabled yet, but most of the other actionable properties do not automatically cause changes in the scene or objects, and will only have a change when an action is applied to them (ie: a drawer won't open by itself, it can only open when the `OpenObject` action is applied, so there is no need to toggle "off" the behavior).

**Comment by zyzhang1130** [comment]
Actually what I want is to have a locking mechanism for openable objects such as drawer... can I overwrite 'openable' in metadata or something?

**Comment by winthos** [comment]
There is no way to overwrite the openable property on objects at this time.

**Comment by zyzhang1130** [comment]
noted
