### ISSUE TITLE
issue with teleport

### ISSUE THREAD

**Issue by zyzhang1130** [allenai/ai2thor#369]
Hi, I try to execute Teleport by using the following code:
            self.event  = self.controller.step(dict(action='GetReachablePositions'))
            xx=self.event.metadata['reachablePositions'][1]['x']
            yy=self.event.metadata['reachablePositions'][1]['y']
            zz=self.event.metadata['reachablePositions'][1]['z']
            self.event = self.controller.step(action='Teleport', x=xx, y=yy, z=zz)

Unlike mentioned in the documentation, actionReturn does not contain the ReachablePositions, instead, I found them in reachablePositions. Nevertheless, this did not teleport to some location. Instead, the agent only moved by a little nudge. When I repeatedly execute the same code, the agent seemed to move to a certain location step by step and eventually converged at a side of a wall. This should not be the expected behavior but I'm not sure what is going on.

**Comment by winthos** [comment]
The coordinates from `GetReachablePositions` are returned in two places. The documentation is correct in that you can access it via the actionReturn key: `self.event.metadata['actionReturn']`, but the controller.step's return object also includes a `reachablePositions` with the same information. Note that the `reachablePositions` found in  the return object will not have any values until a `GetReachablePosition` action is executed, so it's always safer to access the returned reachable positions via the `actionReturn` key.

I'm also not able to replicate your teleport behavior. If you are able to successfully teleport to a position, repeatedly using the teleport action should result in you staying in that position. If you could post an example of the script you are using, that might provide more hints on what might be causing this behavior.

**Comment by zyzhang1130** [comment]
Thank you. I've found the issue. It is because i always chose to teleport to the first entry of the returned reachablePositions and that entry is always the position next to the current location of the agent, hence the observed behavior.
