### ISSUE TITLE
unable to install ai2thor

### ISSUE THREAD

**Issue by Python43coder** [allenai/ai2thor#37]
Hello,

I am using Ubuntu 14.04 and Python 2.7, whenever i try 'sudo pip install ai2thor' i am getting the following error:

`Collecting ai2thor
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not fetch URL https://pypi.python.org/simple/ai2thor/: There was a problem confirming the ssl certificate: [Errno 1] _ssl.c:510: error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied - skipping
  Could not find a version that satisfies the requirement ai2thor (from versions: )
No matching distribution found for ai2thor
`

How can i solve it?

**Comment by roozbehm** [comment]
Can you try the following before installing ai2thor? 
`pip install 'requests[security]'` or `pip install pyOpenSSL ndg-httpsclient pyasn1`

**Comment by ekolve** [comment]
You may be behind a proxy, in which case you will need to contact your administrator to determine the correct configuration for pip/ssl.  The error you are getting is not related to ai2thor, but rather the Python's pip framework running into SSL issues validating the certificates returned from the pypi servers.

**Comment by Python43coder** [comment]
Oh, thanks. I think that's the reason. But i install alot of pacakges and whenever i use SUDO it always working, but i don't know why this is not working.
