### ISSUE TITLE
Unexpected Behavior (potential bug?) of Teleport in Ver. 2.3.4, with a wrong case to demo 

### ISSUE THREAD

**Issue by SgtVincent** [allenai/ai2thor#371]
I got a strange error when running my scripts with ai2thor api. When I spotted the error I found that 
I cannot handle this bug since Controller.step() communicates with the backend Unity engine to execute the action and I am not farmiliar with Unity. 

I wrote a small script to show this bug:
```
###### This case is to demonstrate a potential bug of Teleport function ####
from ai2thor.controller import Controller

# initialization config
wrong_case_config = {
    "scene":"FloorPlan1",
    "grdiSize":0.25,
    "fieldOfView":90,
    # "agentMode":"bot",
    "cameraY":1.00
}

init_position = {
    "x":-1.50,
    "y":1.00,
    "z":1.00
}
target_position = {
    "x": -1.75,
    "y": 1.00,
    "z": 1.00
}

def get_state_from_evenet(event):

    x=event.metadata["agent"]["position"]["x"]
    y=event.metadata["agent"]["position"]["y"]
    z=event.metadata["agent"]["position"]["z"]
    rotation=event.metadata["agent"]["rotation"]["y"]
    horizon=event.metadata["agent"]["cameraHorizon"]
    return (x, y, z, rotation, horizon)

if __name__ == "__main__":

    controller = Controller(**wrong_case_config)
    event = controller.step(action="Teleport", **init_position)
    print("Initial state: (x, y, z, rotation, horizon)={}".format(get_state_from_evenet(event)))
    
    event = controller.step(action="Teleport", **target_position)
    print("State after Teleport: (x, y, z, rotation, horizon)={}".format(get_state_from_evenet(event)))
    print("Last Action Success:{}; Error Message:{}".format(
        event.metadata["lastActionSuccess"],
        event.metadata["errorMessage"]))
```
I get the output 
```
Initial state: (x, y, z, rotation, horizon)=(-1.5, 0.9009996, 1.0, 270.0, 0.0)
State after Teleport: (x, y, z, rotation, horizon)=(-1.5, 0.9009993, 1.0, 270.0, 0.0)
Last Action Success:True; Error Message:
```
which means that Teleport actually fails but returns no error message, if I get it right. 

Is there anyone to help me with this error?

**Comment by winthos** [comment]
I noticed a couple potential errors in your test script that might be the cause of some of the issues.

First, check your wrong_case_config as there is a typo in "gridSize/grdiSize"

```
wrong_case_config = {
    "scene":"FloorPlan1",
    "gridSize":0.25,
    "fieldOfView":90,
    # "agentMode":"bot",
    "cameraY":1.00
}
```

Secondly, the parameters you are passing in to the `Teleport` action are incorrect. You are unpacking your `init_position` and `target_position` dictionaries which is resulting in this being effectively passed in to the `Teleport` action:

```
event = controller.step(action='Teleport', -1.50, 1.00, 1.00)
```

Due to the way we serialize the python parameters into Unity, it requires you explicitly pass in with the following syntax:

```
event = controller.step(action='Teleport', x=-1.50, y=1.00, z=1.00)
```

I would recommend reformatting your test teleports to something like this:

```
 event = controller.step(action="Teleport", x=init_position['x'], y=init_position['y'], z=init_position['z'])
```
Your current teleport scripts are basically being passed in with default parameters, as the x,y,z params are not being set, so they are defaulting to the agent's current position coordinates. This is why the `Teleport` is succeeding but you are not seeing any change in position. It successfully teleported to the same spot it was already in.

**Comment by SgtVincent** [comment]
Hi, @winthos! Thanks for your reply!  

First sorry for my typo that you pointed out. 

Yet the usage of passing the unpacked dictionary to function is correct. As demonstrated in snippet
``` 
def test_args_kwargs(arg1, arg2, arg3):
    print("arg1:", arg1)
    print("arg2:", arg2)
    print("arg3:", arg3)

# now with **kwargs:
>>> kwargs = {"arg3": 3, "arg2": "two", "arg1": 5}
>>> test_args_kwargs(**kwargs)
arg1: 5
arg2: two
arg3: 3
``` 
copied from [https://book.pythontips.com/en/latest/args_and_kwargs.html#using-args-and-kwargs-to-call-a-function](https://book.pythontips.com/en/latest/args_and_kwargs.html#using-args-and-kwargs-to-call-a-function). 

Besides, even though I  changed my code to 
```
    ...
    event = controller.step(action="Teleport", x=-1.50, y=1.00, z=1.00)
    print("Initial state: (x, y, z, rotation, horizon)={}".format(get_state_from_evenet(event)))
    event = controller.step(action="Teleport", x=-1.75, y=1.00, z=1.00)
    ...
```
I still got the same result 
```
Initial state: (x, y, z, rotation, horizon)=(-1.5, 0.9009996, 1.0, 270.0, 0.0)
State after Teleport: (x, y, z, rotation, horizon)=(-1.5, 0.9009993, 1.0, 270.0, 0.0)
Last Action Success:True; Error Message:
```

**Comment by winthos** [comment]
Upon further investigation it seems that your test positions (-1.50, 1.00, 1.00) and (-1.75, 1.00, 1.00) in FloorPlan1 are both positions in which the agent would clip into the environment in that particular scene, specifically into the Refrigerator and its surrounding wooden frame. 

After checking, it seems that those two test positions are not returned as valid positions in the `GetReachablePositions` action, which generates non-clipping positions the agent can move to based on the initialized `gridSize`. I believe the teleport is working as intended, as we do not restrict what coordinates you pass in, and as such allow the possibility to clip the agent into walls, objects, or even out of bounds. I am currently investigating if there is a possible metadata desync issue which may be causing your metadata returns to still show lastActionSucces=True. If you attempt a sequence of teleports using a positions that are validated by `GetReachablePositions`, do you still have this issue?

**Comment by SgtVincent** [comment]
It works, thanks!
