### ISSUE TITLE
MakeAllPickupableObjectsMoveable

### ISSUE THREAD

**Issue by zyzhang1130** [allenai/ai2thor#373]
Hi, just to check if event = controller.step(action='MakeAllPickupableObjectsMoveable') is only available for the latest version because in my case it gave me error 'Invalid action'. Thank you.

**Comment by winthos** [comment]
This was a typo in the documentation. Thank you for helping us find it! Please use `MakeAllObjectsMoveable` as the action name and it should work. The documentation has also been updated to remove the typo.

**Comment by zyzhang1130** [comment]
My pleasure.
