### ISSUE TITLE
Download data

### ISSUE THREAD

**Issue by buxpeng** [allenai/ai2thor#375]
hi.Where can I download the original pictures of 120 scenes?

**Comment by mattdeitke** [comment]
Hey!

Each scene is made in 3D space, which means there are an infinite number of possible images. Further, there are several user settings that may alter the image dataset, such as the camera's field of view, the height/width/resolution, and the channels available (e.g., depth, instance segmentation, class segmentation, etc.).

Thus, we do not have a dataset for every possible image. However, if you wanted to roam around the environments, and download the images, this can be done using Python's image library. For example:
```
from PIL import Image
from ai2thor.controller import Controller

with Controller() as c:
    for _ in range(10):
        event = c.step(action='MoveBack')

        # save image
        Image.fromarray(event.frame).save(path)
```

If you want a more curated dataset of all positions in each room, use [GetReachablePositions](https://ai2thor.allenai.org/ithor/documentation/actions/agent-navigation/#get-reachable-positions) and [Teleport](https://ai2thor.allenai.org/ithor/documentation/actions/agent-navigation/#teleport) to each of the returned reachable positions:

```
from PIL import Image
from ai2thor.controller import Controller

with Controller() as c:
    event = c.step(action='GetReachablePositions')
    positions = event.metadata['reachablePositions']
    for pos in positions:
        event = c.step(action='Teleport', **pos)
        Image.fromarray(event.frame).save(path)
```

The above code works for a single room, but using the `reset` method allows you to move to different rooms.

Matt.

**Comment by mattdeitke** [comment]
Closing this as it appears to be solved. Feel free to reopen if there are any follow-ups.
