### ISSUE TITLE
codes freeze when add thirdparty camera

### ISSUE THREAD

**Issue by gophermmq** [allenai/ai2thor#381]
Hi,

I am running ai2thor 2.3.7 on Ubuntu 18.04. When I call the function

	controller.step(action='AddThirdPartyCamera',rotation = dict(x=0,y=90,z=0), position=dict(x = -1.25, y=1.0, z=-1.0) )

This line runs forever and I cannot get a view from a third-party camera. Anyone has similar problems? Thanks.

**Comment by winthos** [comment]
This has been fixed in the latest release. Please get ai2thor version 2.3.8 and it should resolve this issue.

**Comment by gophermmq** [comment]
Thank you so much.
