### ISSUE TITLE
Depth frame size

### ISSUE THREAD

**Issue by gophermmq** [allenai/ai2thor#384]
Hi,

When initializing the controller, we could set the rgb image width and height. But it looks like the depth frame remains to be 300x300. Is there a way to directly get depth frame of the same size as the rgb? Thank you.

**Comment by AlvaroHG** [comment]
Hi!
If you pass the parameters `width` and `height` to the `Controller` constructor the depth image will also match the rgb image. Can you verify you are doing that?

Try constructing your controller like this:

```
 env = ai2thor.robot_controller.Controller(
            width=1200,
            height=1200,
            # unity initialization params
            gridSize=0.25,
            renderDepthImage=True
        )
```

Then after a `step` action look at the `depth_frame` and `frame` members of the returned event (you can write them to disk), they should both be `1200 x 1200`. Note that `frame` is a 3d array of `1200 x 1200 x 3` and depth is a 2d array of `1200 x 1200 `

**Comment by gophermmq** [comment]
Hi AlvaroHG,

Thank you so much for your reply. Yes, the size of rgb and depth images are the same. I think I did something wrong previously.
