### ISSUE TITLE
Third Party Cameras are Read from Wrong Dict

### ISSUE THREAD

**Issue by ThomasSchellenbergNextCentury** [allenai/ai2thor#385]
In the Unity code, the third party cameras are added to the step event metadata:

https://github.com/allenai/ai2thor/blob/master/unity/Assets/Scripts/AgentManager.cs#L602

This is accurate according to the documentation:

https://ai2thor.allenai.org/ithor/documentation/metadata/#metadata-attributes

However, in the python library, the third party cameras are read from the agent dict within the metadata:

https://github.com/NextCenturyCorporation/ai2thor/blob/master/ai2thor/server.py#L451-L455

**Comment by ThomasSchellenbergNextCentury** [comment]
I think this may be causing https://github.com/allenai/ai2thor/issues/327

**Comment by mattdeitke** [comment]
Hey Thomas!

Just want to clarify the issue. To initialize a ThirdPartyCamera are you running something along the lines of
```
controller.step(
    action='AddThirdPartyCamera', 
    rotation=dict(x=0, y=90, z=0), 
    position=dict(x=-1.25, y=1.0, z=-1.0),
    fieldOfView=60
)
```

And then taking an action (to get an `Event`):
```
event = controller.step(action='MoveAhead')
```
And then trying to access the frames with the following syntax?
```
event.frame  # agent's view
event.metadata['third_party_camera_frames']  # 3rd party view
```

Matt.

**Comment by ThomasSchellenbergNextCentury** [comment]
My bad -- I didn't realize that the frames were being stored in the metadata object and not the thirdPartyCamera object.
