### ISSUE TITLE
the coordinate scale of different rooms

### ISSUE THREAD

**Issue by JethroJC** [allenai/ai2thor#386]
Hi,

By using the metadata, we can get the X,Y,Z coordinates of the object in global space. Is the scale of the coordinates the same for different rooms?  Also, is the range of coordinate values in different rooms the same?

Thank you very much:)

**Comment by JethroJC** [comment]
By the way, how can I get the xyz coordinate dictionaries representing the bounding box of the object. I only know that I can get the objectBounds of pickable objects from the metadata.

Thanks!

**Comment by winthos** [comment]
The scale of position coordinates is the same across rooms. I’m not quite sure what you mean by the range of coordinates, as the range depends on the size of the scene.

He latest release, version 2.4.0, includes axisAlignedBoundingBox as a metadata return for all objects. Note that this box is aligned to world axis, so if the object is rotated the volume approximation will change. Only pickupable objects have object oriented bounds that are constant no matter the rotation of the object.

**Comment by JethroJC** [comment]
Hi, winthos,

Thank you so much for your reply.
