### ISSUE TITLE
reset scene

### ISSUE THREAD

**Issue by xli4217** [allenai/ai2thor#39]
Hi, I'm trying to reset scene so the object positions are randomized at the start of each episode. I'm using `controller.random_initialize(random_seed, randomize_open=True, unique_object_types=False, exclude_receptacle_object_pairs=[])` and then `controller.initialize_scene`. Somehow this always fails and shuts down the program. Help would be appreciated.

**Comment by ekolve** [comment]
Could you provide a snippet showing the failure?  Have you tried executing any controller.step() action?  If the Unity window is appearing then shortly thereafter disappearing, then that is expected behavior.

**Comment by xli4217** [comment]
the error says 

File "/anaconda/lib/python3.6/site-packages/ai2thor/controller.py", line 1088, in initialize_scene
    forceVisible=True), raise_for_failure=True)
  File "/anaconda/lib/python3.6/site-packages/ai2thor/controller.py", line 442, in step
    assert self.last_event.metadata['lastActionSuccess']
AssertionError

**Comment by xli4217** [comment]
Here a snippet

`import ai2thor.controller

controller = ai2thor.controller.BFSController()
controller.start()
controller.reset('FloorPlan1')

controller.random_initialize(random_seed=1,
                             randomize_open=True,
                             unique_object_types=False,
                             exclude_receptacle_object_pairs=[])

controller.initialize_scene()`

**Comment by ekolve** [comment]
I was able to reproduce the bug - please upgrade to version 0.0.24 and you shouldn't see the failure.

**Comment by xli4217** [comment]
Thanks, the crashing problem is solved. But the positions of the objects aren't randomized between calls to the random_initialize() function.

**Comment by ekolve** [comment]
Please try running the following snippet:
```python
    controller = ai2thor.controller.BFSController()
    controller.start()
    controller.reset('FloorPlan1')

    controller.random_initialize(random_seed=1, randomize_open=True, unique_object_types=False,exclude_receptacle_object_pairs=[])
    object_positions = {}
    for o in controller.last_event.metadata['objects']:
        object_positions[o['objectId']] = o['position']

    controller.reset('FloorPlan1')
    controller.random_initialize(random_seed=2, randomize_open=True, unique_object_types=False,exclude_receptacle_object_pairs=[])
    for o in controller.last_event.metadata['objects']:
        if o['objectId'] in object_positions and object_positions[o['objectId']] != o['position']:
            print("%s %s vs %s" % (o['objectId'], o['position'], object_positions[o['objectId']]))
```

**Comment by xli4217** [comment]
I see the problem, I've been giving random_initialize() the same random_seed every time I call it. Turns out each random_seed corresponds to a configuration. One last question, what is the difference between `initialize_scene()` and `controller.step(dict(action="Initialize"))`?

**Comment by ekolve** [comment]
```python
controller.step(dict(action='Initialize', gridSize=0.25))
```
Initialize called through the step() function allows you to set the gridSize of the scene and will snap the agent to the nearest point on that grid.


```python
controller.initialize_scene()
```
initialize_scene() is a method only available on the BFSController and wasn't really intended to be used beyond a few use cases we had internally.  It should probably be renamed, but what it does is open the receptacles for two objects chosen randomly in the scene (fridge, cabinet, drawer).  This was created for training a specific task that wanted to increase the number of objects visible from some perspective in the scene without having to actually open something.
