### ISSUE TITLE
Starting THOR without specifying a scene.

### ISSUE THREAD

**Issue by Lucaweihs** [allenai/ai2thor#392]
### Problem

Currently if using a local THOR build that does not include `"FloorPlan_Train1_1"`, initializing the controller without specifying the scene will result in a value error. Sometimes it is useful to initialize a controller before you know what scenes you'll be using in training and so this can be problematic.

### Expected behavior

THOR will launch selecting some scene from the build, which scene is chosen does not matter. This was the default behavior in older releases.

### Proposed solution

Allow users to specify the scene as `None` in the `Controller` initializer in which case the controller has the expected behavior.

**Comment by mattdeitke** [comment]
Fixed in #605
