### ISSUE TITLE
About the full documentation website and the scene data.

### ISSUE THREAD

**Issue by liuxz-cs** [allenai/ai2thor#393]
I cannot access the website link of newly released documentation in ReadMe.md, when I try to access the website, it has a '404' error.
In the website [https://ai2thor.allenai.org/ithor/documentation/](url), we can only see some simple concepts and examples, and we cannot see the full documentation.

I want to know how to get the scene data in ai2thor, such as json file or the rgb images data.

**Comment by roozbehm** [comment]
The link works for us. Did you try [this link](https://ai2thor.allenai.org/news-releases/v2-4-0/) ?

It would be great if you let us know what information you want us to include in the documentation. We are not sure what json files you are referring to. It is explained in [this section](https://ai2thor.allenai.org/ithor/documentation/overview/examples/#moveahead) how to get rgb images.

**Comment by liuxz-cs** [comment]
In the documentation, I do not find the scene id of all scenes or object id of all objects. And I want to know the initialization status of every scene. When reset the controller, there is no object in the scene, and we need to put objects in different position mannually?

**Comment by roozbehm** [comment]
The list of scenes for iTHOR is here: [https://ai2thor.allenai.org/ithor/documentation/actions/initialization/#initialization-parameters](https://ai2thor.allenai.org/ithor/documentation/actions/initialization/#initialization-parameters)

The list of scenes for RoboTHOR is here: [https://ai2thor.allenai.org/robothor/documentation/#training-scenes](https://ai2thor.allenai.org/robothor/documentation/#training-scenes)

The set of Object Ids is too large to be included in the documentation. The object types are here: [https://ai2thor.allenai.org/ithor/documentation/objects/object-types/](https://ai2thor.allenai.org/ithor/documentation/objects/object-types/)

The metadata includes the information about the state, location, id and properties of all objects in a scene.

**Comment by liuxz-cs** [comment]
If there exist some data file to show the scene feature of every scene. For example, how many objects are in the scene, where are the objects and the shorest path between the start point of agents and objects and so on. Or we can only get this data through running controller and getting metadata from the controller. I mean if we can get some off-online data.

**Comment by roozbehm** [comment]
We have not pre-stored this information since actions such as object randomization can change all locations and paths. You should run the controller and obtain the metadata.

**Comment by ekolve** [comment]
Closing - issue appears to be resolved (scene metadata can be obtained from the controller).
