### ISSUE TITLE
Support Newer Versions of Unity Editor

### ISSUE THREAD

**Issue by ThomasSchellenbergNextCentury** [allenai/ai2thor#398]
Are there any plans to support newer versions of the Unity Editor than 2018.X?

**Comment by winthos** [comment]
There are no current plans to upgrade to newer versions of the Unity Editor, as the current version is a stable "LTS" version that Unity supports and works well with the rest of our infrastructure.  However, there is always the possibility to update the to a newer Unity version down the line, and a new pip release will always accompany any version updates.

**Comment by roozbehm** [comment]
@ThomasSchellenbergNextCentury Is there any specific functionality that you need?

**Comment by mattdeitke** [comment]
Hi. Version 2019.4.2 LTS is now supported officially.

Feel free to reopen if there are any related issues.
