### ISSUE TITLE
Red masks with thirdPartyCameras

### ISSUE THREAD

**Issue by Tushar-N** [allenai/ai2thor#399]
I'm trying to set up a couple of thirdPartyCameras but for some reason, receptacle surfaces seem to be masked with red. I've tried executing the Unmask action for these (or masking with Magenta, and unmasking again), but it does not change.

![aaa](https://user-images.githubusercontent.com/4995097/83064175-023de180-a027-11ea-9ebb-e8183811c7ef.png)

```
controller.reset('FloorPlan1') 
controller.step(dict(action='Initialize', gridSize=0.25))
controller.step(
    action='AddThirdPartyCamera', 
    rotation=dict(x=30, y=220, z=0), 
    position=dict(x=2.25, y=2.5, z=2.25),
    fieldOfView=60
    )
```

**Comment by winthos** [comment]
Hello! This is an issue with the third party camera not using the same culling mask as the main agent camera. This will be fixed in the next pip release (which should be live relatively soon). I will update this post when the fix is live.

**Comment by winthos** [comment]
The newest release, version `2.4.4` has fixed this issue and is live.

**Comment by Tushar-N** [comment]
Thank you!
