### ISSUE TITLE
Is there a way to change agent's discrete action to continuous action？

### ISSUE THREAD

**Issue by ElizabethDuo** [allenai/ai2thor#40]
First, thank you all for providing such a splendid simulation environment!

  I realized that actions of agent like MoveAhead, MoveBack, MoveRight are discrete actions, so in every step the agent can only move in fixed distance e.g, gridsize or fixed angular e.g, step(dict(action='MoveLeft')).
I find specific definition of MoveLeft in unity/Assets/Scripts/DiscreteRemoteFPSAgentController.cs
`
public void MoveLeft(ServerAction action)
 {
			moveCharacter (action, 270);
		}
`
  So I wonder if there is a way to change these fixed discrete actions into continuous? And how? Thanks.

**Comment by ekolve** [comment]
I just added an option that you can use during Initialize to switch to continuous.  You use it the following way:

```python
controller = ai2thor.controller.Controller()
controller.reset('FloorPlan1')
controller.step(dict(action='Initialize', continuous=True))
# this will try to move 0.33 but if you hit a wall, you will go wherever the Unity physics engine puts you
controller.step(dict(action='MoveAhead', moveMagnitude=0.33))

# you can turn in any direction by using the following command
# keep in mind that this is the absolution rotation of the agent in world space, so running the command a second time will not rotate the agent, it will just set the rotation to 275 degrees about the Y axis
controller.step(dict(action='Rotate', rotation=275.0)) 

# you can also controller where the agent looks in any amount, as with Rotate, this is an absolute value 
controller.step(dict(action='Look', horizon=37.0))
```
Most users have used Thor in discrete mode, so we don't have much feedback from users using this in continuous mode.  Let me know through email (erick@allenai.org) or through an issue if you run in to anything that appears wrong.

**Comment by ElizabethDuo** [comment]
Thank you for your reply! I have tried the snippet and it works well.
Well I still have some questions. 
1. When hit a wall or in other words, collided happens, can the agent go back the same start position in every reset?
2. Both Rotate and Look are absolute value, then how can the agent do next Rotate or Look?

**Comment by ekolve** [comment]
Okay, please try the following:

```python

controller = ai2thor.controller.Controller()
controller.reset('FloorPlan1')
controller.step(dict(action='Initialize')) # note no continuous flag
controller.step(dict(action='MoveAhead', moveMagnitude=0.33, snapToGrid=False))
```

**Comment by ElizabethDuo** [comment]
Thanks again! This snippet also works smoothly. It really helped me a lot! 
I will close this issue.

**Comment by jkulhanek** [comment]
Would not it be better to allow to pass `rotation` to `RotateLeft` and `RotateRight` actions? It would be a delta angle. Also, should not it work without `snapToGrid` when the agent is in the continuous mode?

**Comment by XiaoLiSean** [comment]
I'd like to inquiry if the continuous action is deprecated in some latest versions (i.e. ai2thor=2.4.22 from conda forge). I tried command mentioned in this issue:
`    controller = Controller()
    controller.reset('FloorPlan1')
    event = controller.step(dict(action='Initialize', continuous=True))
    print(event.metadata['agent'])
    event = controller.step(action='RotateLeft', degrees=45.0)
    print(event.metadata['agent'])
    event = controller.step(dict(action="MoveAhead", moveMagnitude=0.2, snapToGrid=False))
    print(event.metadata['agent'])
    event = controller.step(dict(action="MoveAhead", moveMagnitude=0.2, snapToGrid=False))
    print(event.metadata['agent'])
    exit()`
However, the returned robot position still snapped to grid (default grid size 0.25). I'm wondering if it is my code that lead to this problem or the continuous functionality is deprecated.
