### ISSUE TITLE
Scene modifications in Unity

### ISSUE THREAD

**Issue by aditya30887** [allenai/ai2thor#401]
Hello, 
I am extremely new to the field as my background is mainly Neuro-engineering. I am delighted to have found the ai2thor and am playing around with it to see how I can use it for my experiments. I was wondering if you could answer the following two questions- 

1) How do I actually import one of your scenes into Unity? 
2) Can I add my robot Unity object to the scene and control the robot partly using your commands and partly using mine? 

Thanks for your help!
-Adi

**Comment by aditya30887** [comment]
Thank you fr your reply. I have the 2020.1.0b7 version for Unity. Are your scenes version-specific to 2018.4.16 as stated by you? It does seem that way because I can't seem to successfully import the assets in my version of Unity. 
As far as adding my custom robot goes, I do have a mesh that is importable into Unity.
https://pollen-robotics.github.io/reachy-docs/docs/simulation/create-your-own-scene/

Your guidance on this front to incorporate this robot into your scenes would be great! Thank you!

**Comment by winthos** [comment]
The scenes are not restricted to version 2018.4.16, however if you use a more recent version of Unity, some of the Unity specific functions or components might have been deprecated or changed, so we cannot guarantee that all functionality will be maintained, as the current framework was built to only be 100% compatibility with 2018.4.16. When you tried to import our assets to version 2020.1.0b7, I bet something like a compatibility warning asking if you wanted to update scripts came up. If you let that process run, you will most likely be able to import the majority of assets and scripts, but there will be some that simply don't work or break entirely.

Looking at the link you provided, it seems that it would be quite an undertaking to make that custom robot asset they have made compatible with THOR. It looks like they have their own set of scripts to control their robot asset, and depending on whether or not you want to be able to control that through THOR's python controller interface will determine what you are going to need to do.

I would first take a look at the FPSController prefab [in this directory](https://github.com/allenai/ai2thor/blob/master/unity/Assets/Standard%20Assets/Characters/FirstPersonCharacter/Prefabs/FPSController.prefab) to see how the prefab for our agent is set up. 

From there, I would reference the following components that are integral to how the agent functions:

-[BaseFPSAgentController](https://github.com/allenai/ai2thor/blob/master/unity/Assets/Scripts/BaseFPSAgentController.cs) - This defines properties and actions that all types of agent controllers have access to.

-[PhysicsRemoteFPSAgentController](https://github.com/allenai/ai2thor/blob/master/unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs) - This defines a more specific set of actions that only physics-enabled controllers have access to

-[StochasticRemoteFPSAgentController](https://github.com/allenai/ai2thor/blob/master/unity/Assets/Scripts/StochasticRemoteFPSAgentController.cs) - This defines a specific set of actions to be used with a stochastic controller that has more random movement and rotation, but no access to physics based actions.

-[AgentManager](https://github.com/allenai/ai2thor/blob/master/unity/Assets/Scripts/AgentManager.cs) - This manages the initialization of the agent as well as defines the `ServerAction` class that is used for all actions the agent can take. Note that in the various FPSAgentControllers, any action that takes a ServerAction as input is able to be controlled via the python controller.

Overall, depending on exactly what you want to do and to what level of fidelity you'd like to integrate the articulated robot asset with our various metadata and event systems, the things you will need to update or integrate will differ.

**Comment by aditya30887** [comment]
Thank you for your reply! What I would like to do really is be able to use my robot asset's instruction set (and not the THOR's python controller interface) to interact with the THOR world. I can see how that might be a massive undertaking. Imagine being in the THOR kitchen. Given that I can extract the location of the knife in the kitchen scene, I can possibly place the robot asset right next to it, and then the remaining task is to get the robot to grip the knife using its instruction set. I am beginning to see that it won't be as easy to get all of this done. Would you agree?

**Comment by winthos** [comment]
Integrating this is definitely possible but I do agree if you do not have much experience specifically using Unity, it may be a lot to take on. What might be worth experimenting with is instead of trying to fully integrate your robot asset into the framework (ie: python controller, server actions, sim object metadata), there should be a way to just place that robot into the THOR scenes and still be able to manipulate objects without using any of the functionality of the THOR framework itself.

This might involve going into Unity and removing components or disabling components that are integrated into our framework, and making a sort of blank slate that has all the game objects and collisions and physics still in tact. At that point, it would be no different than placing your robot asset into an empty new room and placing a cube in the room for it to pick up.

**Comment by aditya30887** [comment]
Thank you for your reply. I think I have enough answers for now. I will close this issue for now.
