### ISSUE TITLE
Running in headless mode using the Docker image?

### ISSUE THREAD

**Issue by prasoongoyal** [allenai/ai2thor#403]
I'm trying to run ai2thor in headless mode using the Docker image. I don't have root access to the machine I want to run this on, so I'm using [Singularity](https://singularity.lbl.gov/index.html) to launch the Docker image. But I'm not sure how to run an X server within the container. The commands startx and xinit error out with `command not found`.

**Comment by ekolve** [comment]
I plan on taking a lot of the code from the robothor-challenge repo (https://github.com/allenai/robothor-challenge) and creating a new repo ai2thor-docker that makes it easier to run thor using docker including running the X server.  

Please have a look at the Dockerfile and this line:
https://github.com/allenai/robothor-challenge/blob/a2281a155b502f90f995d217eeaa20aa26c1427c/robothor_challenge/__init__.py#L131

That is where X is started prior to running the ai2thor Controller.

**Comment by prasoongoyal** [comment]
Thanks a lot! I managed to get it working on a different machine that had X server.

**Comment by Gabesarch** [comment]
Did you manage to get it working with a singularity image? Thanks!
