### ISSUE TITLE
opening an object halfway

### ISSUE THREAD

**Issue by zyzhang1130** [allenai/ai2thor#405]
Hi may I check if I open an object halfway (for example event = controller.step(action='OpenObject', objectId="Fridge|0.25|0.75", moveMagnitude=0.5) in the documentation, will the object's isOpen equals True for False?

Thank you for your reply.

**Comment by winthos** [comment]
Yes, opening halfway will still flag the object as isOpen = TRUE. As long as the object is not in the fully “closed” state, it is considered open.

**Comment by zyzhang1130** [comment]
Noted with thanks.
