### ISSUE TITLE
package feedback for conda repo

### ISSUE THREAD

**Issue by systemshift** [allenai/ai2thor#408]
So I just uploaded ai2thor to the conda repo.
https://anaconda.org/conda-forge/ai2thor
I would like some user feedback to ensure that it has been built correctly. I will assume everything has been done correctly unless someone mentions the contrary on this issue.

**Comment by ekolve** [comment]
I installed the package and didn't run in to any problems.  Are you planning on updating this as we release new pip packages?

**Comment by systemshift** [comment]
> Are you planning on updating this as we release new pip packages?
Yes, packages should be on pair in both repos. The exception would be if a new build method is introduced things would break on my side and would have to fix it.

**Comment by ekolve** [comment]
Great, thanks for maintaining this.  I will close the issue unless there is anything else?
