### ISSUE TITLE
Running on gcloud

### ISSUE THREAD

**Issue by xli4217** [allenai/ai2thor#41]
Hi, I'm trying to run on the google cloud compute engine. I have x-server running remotely by `Xvfb :0.0&`. When I try to run 

```
import ai2thor.controller
c = ai2thor.controller.Controller()
c.start()
```

I get the error message 
```
File "/usr/local/lib/python3.6/dist-packages/ai2thor/controller.py", line 572, in _start_unity_thread
    raise Exception("command: %s exited with %s" % (command, returncode))
Exception: command: ['/home/.ai2thor/releases/thor-201804271353-Linux64/thor-201804271353-Linux64', '-screen-width', '300', '-screen-height', '300'] exited with 1
```

**Comment by xli4217** [comment]
I think I might have found a fix. In line 544 of controller.py, modify `command += " -screen-width %s -screen-height %s" % (width, height)` to `command += " -screen-width %s -screen-height %s -nographics" % (width, height)` makes the error go away. Things seem to be running.

**Comment by ekolve** [comment]
Closing issue as it appears to be resolved.

**Comment by li3cmz** [comment]
> I think I might have found a fix. In line 544 of controller.py, modify `command += " -screen-width %s -screen-height %s" % (width, height)` to `command += " -screen-width %s -screen-height %s -nographics" % (width, height)` makes the error go away. Things seem to be running.

Can you get normal event.frame from this settings?
