### ISSUE TITLE
metadata

### ISSUE THREAD

**Issue by zyzhang1130** [allenai/ai2thor#414]
Hi, may I check it that true that all the information regarding the state of the environment as well as the agent are stored in the metadata object, including things like the camera view (pixel values of each frame) of the agent? Thank you.

**Comment by mattdeitke** [comment]
Hey!

That is mostly true, but I can clarify it a bit.

Everything regarding the state of the environment (including the metadata) is stored in an `Event`, which is returned after each step
```
from ai2thor.controller import Controller
controller = Controller()
---
event = controller.step(action='MoveAhead')
```
Now `event` is an `Event`, with properties like
```
frame = event.frame
```
to extract the **frame**, [along with other properties listed in this section of the website](https://ai2thor.allenai.org/ithor/documentation/metadata/#metadata-object). One special property is metadata
```
metadata = event.metadata
```
which contains [a bunch more attributes linked here](https://ai2thor.allenai.org/ithor/documentation/metadata/#metadata-attributes), such as the **position/rotation of the agent**, **object information**, and the name of the **last action**, for example.

*Note* that there's an *infinite amount of information* that could use to represent the environment state, (e.g., what is at position x, y, z for each x, y, z) so we cannot give *all the information regarding the environment*. Instead, we consolidate that information into what we think is useful (e.g., the robot's camera frame, the position of objects, the name of objects, etc.)

[This page](https://ai2thor.allenai.org/ithor/documentation/metadata/) in the documentation should hopefully be helpful, but let me know if there's anything confusing!

Matt.

**Comment by zyzhang1130** [comment]
Hi, thank you for the detailed explanation. I think it clarifies most of my questions at the moment. I'll let you know if I encounter other issues along the way.
