### ISSUE TITLE
Stuck at controller.start()

### ISSUE THREAD

**Issue by cwhao98** [allenai/ai2thor#415]
The process is stuck here. Could anyone give me some tips? Thanks.

>Found path: /home/ubuntu/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64
Mono path[0] = '/home/ubuntu/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Managed'
Mono config path = '/home/ubuntu/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Mono/etc'
Preloaded 'ScreenSelector.so'
Logging to /home/ubuntu/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor/Player.log

**Comment by mattdeitke** [comment]
Hey!

Could you provide the code preceding the call to `controller.start()`?

Also could you provide the version of AI2-THOR you're using with
```python
import ai2thor
ai2thor.__version__
```

For the most part, `controller.start()` has been deprecated in newer versions of AI2-THOR and is simply called upon initializing a `Controller` with
```python
from ai2thor.controller import Controller
c = Controller()  # calls start() upon initialization for newer versions
```

Matt.

**Comment by cwhao98** [comment]
@mattdeitke 

Thanks for your replying.

The version of AI2-THOR is 2.1.0. 

However, I have found the main reason is that I run the code on a headless machine without a display.  And I've solved this by 'startx'.

Anyway, thanks a lot.
