### ISSUE TITLE
Running failed after update to 0.0.25

### ISSUE THREAD

**Issue by ElizabethDuo** [allenai/ai2thor#42]
After update to 0.0.25 using `sudo pip install --upgrade ai2thor`, I can't even running the basic example.
The error message goes like this

> Traceback (most recent call last):
  File "test_example.py", line 2, in <module>
    import ai2thor.controller
  File "/usr/local/lib/python2.7/dist-packages/ai2thor/controller.py", line 461
SyntaxError: Non-ASCII character '\xe2' in file /usr/local/lib/python2.7/dist-packages/ai2thor/controller.py on line 461, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Why did import ai2thor go wrong and how to fix it?

**Comment by ekolve** [comment]
I will fix this shortly (hopefully today).  This is a 2.7 incompatibility.  If you can comment that line out for now (its just a print statement for a manual controller that be operated using keyboard), you should be able to get it running.

**Comment by ElizabethDuo** [comment]
Thanks for improving THOR even in weekends! Let me know if THOR is updated!

**Comment by ekolve** [comment]
Just pushed version 0.0.26 that should fix the unicode issues with 2.7. Please give that a try.

**Comment by ElizabethDuo** [comment]
Tried and and everything goes well.Closing this issue.
