### ISSUE TITLE
a problem about the action 'GetReachablePositions'

### ISSUE THREAD

**Issue by liuxz-cs** [allenai/ai2thor#420]
The action 'GetReachablePositions' only return one event result, does it return the closest position or a random position?

**Comment by liuxz-cs** [comment]
And if I want to get all the reachable positions, what action can I use?

**Comment by mattdeitke** [comment]
Hey!

`GetReachablePositions` returns _all_ the reachable positions in the scene (not just the neighboring positions). Here, you'd run
```python
from ai2thor.controller import Controller
c = Controller()
event = c.step(action='GetReachablePositions')
positions = event.metadata['reachablePositions']
```
Here `positions` is a list of `xyz dictionaries` for all reachable positions in the scene.

---
*Note* that if you adjust `gridSize` upon [initialization](https://ai2thor.allenai.org/ithor/documentation/actions/initialization/#initialization-parameters) with
```python
c = Controller(gridSize=0.1)  # default is 0.25
```
you can make the agent step size smaller, resulting in more reachable positions.

---

Hope that helps,
Matt! :)

**Comment by liuxz-cs** [comment]
Ok, thanks a lot!
