### ISSUE TITLE
Some issues about function 'get_shortest_path_to_object'

### ISSUE THREAD

**Issue by liuxz-cs** [allenai/ai2thor#422]
When we want to compute spl in navigation task, we try to use the function 'get_shortest_path_to_object' to get the shortest path from the start point to the target object， but we always get an exception and cannot run this function successfully. We can ensure the objectID we give to the function is in the scene, so what's the possible problem leading to that error?

**Comment by liuxz-cs** [comment]
I try the function 'get_shortest_path_to_object' and function 'get_shortest_path_to_object_type', but both cannot run successfully.

**Comment by AlvaroHG** [comment]
Hi!

Can you provide the full arguments you used to call this function, how you initialized the controller and what scene are you running in?

Note that these functions are available in only RoboTHOR scenes now, so if you are using any scene named `FloorPlan...` this is expected to fail.

Alvaro

**Comment by liuxz-cs** [comment]
Oh， I use the function in ithor scenes named FloorPlanxxx, such as FloorPlan201, FloorPlan202 and so on. So I want to know if I want to evaluate the spl of navigation tasks in ithor scenes, which function can I use?  Which function can I use to calcuate the shortest path, and which function to calculate the spl?

**Comment by liuxz-cs** [comment]
> Hi!
> 
> Can you provide the full arguments you used to call this function, how you initialized the controller and what scene are you running in?
> 
> Note that these functions are available in only RoboTHOR scenes now, so if you are using any scene named `FloorPlan...` this is expected to fail.
> 
> Alvaro

Oh， I use the function in ithor scenes named FloorPlanxxx, such as FloorPlan201, FloorPlan202 and so on. So I want to know if I want to evaluate the spl of navigation tasks in ithor scenes, which function can I use? Which function can I use to calcuate the shortest path, and which function to calculate the spl?

**Comment by liuxz-cs** [comment]
I don't find the relevant function about how to calculate shortest path and spl in documentation of ithor.

**Comment by mattdeitke** [comment]
Merging with #443

**Comment by liuhe1305** [comment]
> Hi!
> 
> Can you provide the full arguments you used to call this function, how you initialized the controller and what scene are you running in?
> 
> Note that these functions are available in only RoboTHOR scenes now, so if you are using any scene named `FloorPlan...` this is expected to fail.
> 
> Alvaro

I saw some scenes named 'FloorPlan_Train...' in RoboTHOR scenes and why can I not use the get_shortest_path_to_object either.
