### ISSUE TITLE
How to calculate spl of navigation task in ithor?

### ISSUE THREAD

**Issue by liuxz-cs** [allenai/ai2thor#425]
We want to calculate the spl of navigation task in ithor scenes, and we want to know how to calculate it ?  So we need to first the shortest path distance, and then calculate spl? Is there any function we can use directly in ithor scenes ?

**Comment by mattdeitke** [comment]
Hi. We have not yet implemented cached calculations for SPL in iTHOR.

But, one could use BFS to find all the grid positions and position of each target object in the scene to find the minimum distance from a position to the target. The other quantities you'd need to know are success (depends on your task definition) and the path of the agent (which you can get from carrying out an episode).

Matt.

**Comment by mattdeitke** [comment]
Merging with #443.
