### ISSUE TITLE
The distance of the action 'MoveAhead'.

### ISSUE THREAD

**Issue by liuxz-cs** [allenai/ai2thor#427]
When we step the action 'MoveAhead', the distance agent moves is default to 'gridsize'. If we assign a specific value to the parameter 'moveMagnitude', then the distance the agent moves this step is the value assign, and if we continue to perform 'MoveAhead' and do not assign the value of 'moveMagnitude', the distance the agent will move is the default value of 'gridsize' or the new value we assigned before?

And I try to assign the 'moveMagnitude' when use 'MoveAhead', sometimes, the distance is always default to 'gridsize', do not change to the value I assigned, what's the problem with it?  Does the parameter 'moveMagnitude' automatically clamps to the nearest tenth of the value or have some value setting?

**Comment by liuxz-cs** [comment]
And sometimes, I assign the 'moveMagnitude', and it does not move.

**Comment by mattdeitke** [comment]
Hey, it sounds like when you pass in `MoveMagnitude` , it's snapping to the nearest grid position. Try using passing in contunuous=True to the controller and rerunning the code:
```python
from ai2thor.controller import Controller
c = Controller(continuous=True)
c.step('MoveAhead', moveMagnitude=...)
```

Matt.

**Comment by liuxz-cs** [comment]
> Hey, it sounds like when you pass in `MoveMagnitude` , it's snapping to the nearest grid position. Try passing in `contunuous=True` to the controller and rerunning the code:
> 
> ```python
> from ai2thor.controller import Controller
> c = Controller(continuous=True)
> c.step('MoveAhead', moveMagnitude=...)
> ```
> 
> Matt.

I  try it, but setting contunuous=True seems not useful.  Then I try setting   snapToGrid=False   of  controller, it is useful.

**Comment by winthos** [comment]
Yes this is correct. Setting 'continuous' is deprecated. Initializing with snapToGrid=False will stop the agent from snapping to the nearest grid point upon using a move action.

Additionally you are correct in that if you do not specify a moveMagnitude for each move action, it will default to the grid size. Any previous "Move" actions you called will not set the moveMagnitude, it can be uniquely set each time you call the action. If you did want to do something like pass in the same moveMagnitude for every Move action, you would need to store that value in an external variable and just pass in that variable each time as the moveMagnitude value.

**Comment by liuxz-cs** [comment]
Thanks a lot. And I have a similar question about the 'RotateLeft' and 'RotateRight' action.  When I set the value of the parameter 'degrees' using  controller.step('RotateLeft', degrees=...),  it seems the parameter 'degrees' is not useful, it still rotate the value of  'rotateStepDegrees' of initialization.

**Comment by winthos** [comment]
Yes, the rotate actions also behave the same way. If you want to apply the same, non default rotation each time you execute the action you will need to pass it in each time. It is strange that the default value is not being overwritten. Could you provide more information like the which version of THOR you are using and the exact syntax you are using?

**Comment by mattdeitke** [comment]
Closing as this appears to be solved. Feel free to re-open if there are any follow-ups :)
