### ISSUE TITLE
The parameter ‘rotateGaussianMu‘ seems not useful.

### ISSUE THREAD

**Issue by liuxz-cs** [allenai/ai2thor#429]
When creating the controller, I set 'applyActionNoise = True', and I set the value of 'rotateGaussianMu' and 'rotateGaussianSigma', but during the navigation, the degree of rotation action is still the default value. It seems that it does not add the noise to the rotate degrees.

**Comment by winthos** [comment]
Please note that the applyActionNoise initialization parameter only works for agents if they are initialized with both the agentMode and agentControllerType set to specific values:

agentMode='default'
AND
agentControllerType='stochastic' 

or
 
agentMode='bot'  
AND
agentControllerType='stochastic'

If you leave the default settings, the agent will initialize with agentMode='default' and agentControllerType='physics' which is not compatible with movement or rotation gaussians. This is documented in the [initialization section of our documentation here.](https://ai2thor.allenai.org/ithor/documentation/actions/initialization/#initialization-parameters)

**Comment by liuxz-cs** [comment]
> Please note that the applyActionNoise initialization parameter only works for agents if they are initialized with both the agentMode and agentControllerType set to specific values:
> 
> agentMode='default'
> AND
> agentControllerType='stochastic'
> 
> or
> 
> agentMode='bot'
> AND
> agentControllerType='stochastic'
> 
> If you leave the default settings, the agent will initialize with agentMode='default' and agentControllerType='physics' which is not compatible with movement or rotation gaussians. This is documented in the [initialization section of our documentation here.](https://ai2thor.allenai.org/ithor/documentation/actions/initialization/#initialization-parameters)

I have already set  agentMode='bot' and  agentControllerType='stochastic', but it still seems not useful.

**Comment by winthos** [comment]
I have not been able to replicate this bug locally on my end. Could you provide some more details so we can look into it? Which version of THOR are you using, the latest? After you initialize everything that should be needed to use rotation Gaussian, when you try a rotate action, can you return the agent information in the event return? This should explicitly list the rotation of the agent and we can see if the noise is being applied or not.

**Comment by liuxz-cs** [comment]
> I have not been able to replicate this bug locally on my end. Could you provide some more details so we can look into it? Which version of THOR are you using, the latest? After you initialize everything that should be needed to use rotation Gaussian, when you try a rotate action, can you [return the agent information in the event return](https://ai2thor.allenai.org/ithor/documentation/metadata/#agent-attributes-)? This should explicitly list the rotation of the agent and we can see if the noise is being applied or not.

The version is ai2thor 2.3.7. I create the controller using :

`            self.controller = ai2thor.controller.Controller(
                snapToGrid=False,
                gridSize=0.25,
                rotateStepDegrees=30, 
                agentControllerType='stochastic', 
                agentMode='bot',
                applyActionNoise=True,
                rotateGaussianMu = 10,
                rotateGaussianSigma = 0.5,
            )`

And I print the rotation of every step, and when the last_event_action == True, the change of rotation is always 30, do not add the noise.

**Comment by winthos** [comment]
Ah I see. I believer the issue is that the current documentation denoting how to use the new ControllerType/agentMode/Gaussians is only guaranteed to be compatible with version 2.4.0 and later.

**Comment by liuxz-cs** [comment]
> Ah I see. I believer the issue is that the current documentation denoting how to use the new ControllerType/agentMode/Gaussians is only guaranteed to be compatible with version 2.4.0 and later.

I think there may exist some problems in version 2.4.0.  For example, the action 'TeleportFull' cannot be used. I use action 'TeleportFull' based on the document, but it runs with error  `ValueError: Invalid action: TeleportFull`.  So how to solve this problem, does the new version change the use of 'TeleportFull'

**Comment by winthos** [comment]
The functionality of TeleportFull has not changed in the new version. Are you initializing the agent using a `physics` or `stochastic` controller? I have a hunch of what the issue might be, and which controller type you are using might help find it.

**Comment by liuxz-cs** [comment]
> The functionality of TeleportFull has not changed in the new version. Are you initializing the agent using a `physics` or `stochastic` controller? I have a hunch of what the issue might be, and which controller type you are using might help find it.

The type of agent is `stochastic`

**Comment by liuxz-cs** [comment]
> The functionality of TeleportFull has not changed in the new version. Are you initializing the agent using a `physics` or `stochastic` controller? I have a hunch of what the issue might be, and which controller type you are using might help find it.

I set the value of `agentControllerType` to be `stochastic`, and `agentMode` to `bot`. When I use it in version 2.3.7, is ok, but Iuse it in 2.4.0, it get the error `ValueError: Invalid action: TeleportFull`. The controller initialization shows as follows:
`
controller = ai2thor.controller.Controller(
                snapToGrid=False,
                gridSize=0.25,
                rotateStepDegrees=45.0, 
                agentControllerType='stochastic', 
                agentMode='bot',
                fieldOfView = 100,
            )
`

**Comment by winthos** [comment]
Yes, between version 2.3.7 and 2.4.0, there was a refactor in how we structured our Controller/Mode hierarchy. As part of this, currently only the `physics` controller is able to use the Teleport actions. We will add back the ability to Teleport for the `agentMode = bot` and `agentControllerType = stochastic` configurations in a new release very soon. I will update here when that release is live.

**Comment by winthos** [comment]
Version 2.4.8 has been released adding back the ability for stochastic agents to use the Teleport actions. Please let me know if you continue to have any issues, especially in regards to the Gaussian parameters.
