### ISSUE TITLE
How to get location ids (e.g. '26', '37', '43', '53', '69')

### ISSUE THREAD

**Issue by XuGK** [allenai/ai2thor#434]
Hello, I am reading the article _Target-driven Visual Navigation in Indoor Scenes using Deep Reinforcement Learning._ This is the code inside, 

##keys are scene names, and values are a list of location ids (navigation targets)
TASK_LIST = {
  'bathroom_02'    : ['26', '37', '43', '53', '69'],
  'bedroom_04'     : ['134', '264', '320', '384', '387'],
  'kitchen_02'     : ['90', '136', '157', '207', '329'],
  'living_room_08' : ['92', '135', '193', '228', '254']
}

I want to know how to get the scene of location ids (e.g. '26', '37', '43', '53', '69'). In other words, how to know what the target object is. I'm just getting started with AI, the question may be a little simple, but I'm stuck. Thank you for your reply！

**Comment by XuGK** [comment]
I want to know what the scene is，at location ids

**Comment by mattdeitke** [comment]
Hey, @XuGK!

I think you might be trying to use outdated syntax.

For the problem of setting up target-driven visual navigation within THOR, check out https://github.com/allenai/ai2thor/issues/416#issuecomment-655285686. It shows how one would build/use Target-driven Visual Navigation within AI2-THOR's RoboTHOR environment (which is an environment focused on navigation).

Sorry for the late reply,
feel free to chime in with any other questions!

Matt =)

**Comment by XuGK** [comment]
Hey, Matt！

Thank you for your reply. I have solved the problem, and #416 (comment) is so useful to me! Thank you again for your support！Wish you work smoothly! 

XuGK =）
