### ISSUE TITLE
Hi! Can you guys add a wait&observe action to the action list？

### ISSUE THREAD

**Issue by yang9004** [allenai/ai2thor#437]
Hi! 
I notice that there are some physical processes in ithor (e.g., a falling ball), and we need agents to observe such processes, which requires an agent can wait and do nothing but watch.
Now, we use a work around solution to tackle this issue :  
`event = controller.step(action="MoveAhead", moveMagnitude=0.0000001)`
Thus, the agent can keep (almost) steady , and we can continously obtain an updated event and metadata information in it .
But, it is, after all, an temporary solution, I wonder if you can consider such wait&observe action

**Comment by winthos** [comment]
Hello! We already have a “no op” action that does nothing but return metadata. Please see our documentation here: https://ai2thor.allenai.org/ithor/documentation/actions/miscellaneous-actions/#do-nothing

**Comment by yang9004** [comment]
Oh! Thank you very much!
