### ISSUE TITLE
How can I change the camera's distance threshold?

### ISSUE THREAD

**Issue by choys73** [allenai/ai2thor#44]
Hello
An object is said to be visible if it is in camera view and within a threshold of distance.
Default value is 1 meter.
I want to change the threshold of distance.
How can I change the camera's distance threshold?

**Comment by ChoYS96** [comment]
Where can I change it?
I try to find the AI2THOR_VISIBILITY_DISTANCE value but I can't find it in code.

**Comment by ekolve** [comment]
you can set this in Python by doing the following:
```python
import os
os.environ['AI2THOR_VISIBILITY_DISTANCE'] = '4.0'
# start ai2thor here
```
