### ISSUE TITLE
Hi! Can I capture the intermediate process of the state change of an object?

### ISSUE THREAD

**Issue by yang9004** [allenai/ai2thor#441]
For example , I can observe the falling process of an apple (order the agent to drop the apple ) or cook something, or fill the cup with coffee.

But, can I capture the intermediate state of this falling? since all the information are captured by 
`event = controller.step(action="...")`
I want to obtain states sequence like { t0:apple -> t1:apple falling -> t2:apple on the ground}
or something like that, change of x axis, y axis, z axis is also ok ！
how can I capture such kind of information？

**Comment by roozbehm** [comment]
You can pause physics and advance the simulation by a for loop using the [pause physics commands](https://ai2thor.allenai.org/ithor/documentation/actions/miscellaneous-actions/#pause-time) to get the intermediate frames.

This works only for physics based changes (e.g., object falling). Our state changes (e.g., cooking) happen instantly.

**Comment by yang9004** [comment]
Thank you ! I will check this solution right away!

**Comment by mattdeitke** [comment]
Closing as this appears to be solved. If there are any related follow-ups, feel free to re-open :)

**Comment by d-val** [comment]
Hi, there is an issue with the video controller. See issue https://github.com/allenai/ai2thor/issues/498#issuecomment-893693197

**Comment by d-val** [comment]
@mattdeitke PR https://github.com/allenai/ai2thor/pull/856 fixes this bug
