### ISSUE TITLE
Support 'MapFrame' Officially

### ISSUE THREAD

**Issue by mattdeitke** [allenai/ai2thor#445]
**Expected functionality.**

Currently, this can be achieved from Python with
```python
c = Controller()
agent_view = c.last_event.frame
event = c.step('ToggleMapView')
map_view = event.frame
c.step('ToggleMapView')  # goes back to agent view with actions available.
```

But, It should work with:
```python
c = Controller(renderMapFrame=True)
event = c.step('MoveAhead')
map_view = event.map_frame
agent_view = event.frame
```

It does not have to be super optimized, since this is purely for visualization purposes. Just a wrapper from the Unity side that makes it easier.

---

I can run some tests to confirm that ToggleMapView works with all scenes, but I believe this issue was fixed with the video.

**Comment by Lucaweihs** [comment]
I have some python code that automatically generates functions which produce a 1-1 correspondence between pixel coordinates (in the map view) to (x,z) in THOR, is this something that we would want to include here? For instance, something like

```python
x, z = event.map_coord_to_thor_xz(row, col)
assert (row, col) == event.thor_xz_to_map_coord(x, z)
```

**Comment by mattdeitke** [comment]
Yeah, that seems quite useful from the Python side! I wouldn't return all the x/z positions in the metadata. The best place for it would probably be within Python `Controller`.

**Comment by thomason-jesse** [comment]
> I have some python code that automatically generates functions which produce a 1-1 correspondence between pixel coordinates (in the map view) to (x,z) in THOR, is this something that we would want to include here? For instance, something like
> 
> ```python
> x, z = event.map_coord_to_thor_xz(row, col)
> assert (row, col) == event.thor_xz_to_map_coord(x, z)
> ```

I would love to see this code. I'm trying to do this mapping using `SceneBounds` but with particularly stretched/elongated maps there's a lot of drift between the topdown view and the corresponding (x, z) coords.

**Comment by Lucaweihs** [comment]
Hi @thomason-jesse,

Check out this [get_agent_map_data](https://github.com/allenai/cordial-sync/blob/master/utils/visualization_utils.py#L109) function as well as this [visualize_agent_path](https://github.com/allenai/cordial-sync/blob/master/utils/visualization_utils.py#L206) function. These were made with an older version of THOR in mind but I believe they should work now still. Let me know if you have any issues.

**Comment by keeper1314** [comment]
我在主函数中加入代码：为什么不能改变agent的位置？
if __name__ == "__main__":
    import matplotlib.pyplot as plt
    
    c = Controller()
    c.start()
    c.reset("FloorPlan1_physics")
    tar= {"x": 1.0, "y": 0.0, "z": -1.0}
c.step({"action": "Teleport", "position": target_position})
    # 获取Agent地图数据
    t = get_agent_map_data(c)
    # 添加表示Agent视野的三角形
    new_frame = add_agent_view_triangle(
        position_to_tuple(c.last_event.metadata["agent"]["position"]),
        c.last_event.metadata["agent"]["rotation"]["y"],
        t["frame"],
        t["pos_translator"],
    )
    # 显示结果图像
    plt.imshow(new_frame)
    plt.show()
