### ISSUE TITLE
Get Spawn Coordinate Above Receptacle

### ISSUE THREAD

**Issue by XiaoLiSean** [allenai/ai2thor#452]
When I try to get a spawn coordinate above CounterTop|-01.94|+00.98|-03.67 using 

`event = controller.step('GetSpawnCoordinatesAboveReceptacle', objectId=obj_ID, anywhere=True)`

the program just stuck at this line.

**Comment by winthos** [comment]
Hello! This error has been fixed as of version 2.4.11, please update to that version. (https://github.com/allenai/ai2thor/releases/tag/2.4.11)

**Comment by XiaoLiSean** [comment]
Thanks for your information. However, when I was trying to build AI2THOR from the source code using 
`pip install ai2thor-2.4.11.tar.gz` 
there pops up an error:

Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-q_qoEE-build/setup.py", line 3, in <module>
        exec(open('ai2thor/_version.py').read())
    IOError: [Errno 2] No such file or directory: 'ai2thor/_version.py'

Hope you can give me some suggestions. Thanks for your time!

**Comment by XiaoLiSean** [comment]
I just update my AI2THOR version to 2.4.11 using 
`conda install -c conda-forge ai2thor`
 The action type for getting spawn coordinate above receptacle works just fine.
`event = controller.step('GetSpawnCoordinatesAboveReceptacle', objectId='CounterTop|1|1|1', anywhere=True)`
However, the action for placing an object such as chair at a point won't work.
`event = controller.step(action = 'PlaceObjectAtPoint', objectId='Toaster|1|1|1', position=dict(x=-1.25, y=1.0, z=-1.0))`
