### ISSUE TITLE
Can I run AI2-THOR off-line?

### ISSUE THREAD

**Issue by faylsaac** [allenai/ai2thor#453]
if so, what should i do

**Comment by Voidminded** [comment]
You can, although you need an internet connection once to download the binaries. All you have to do is to download the binaries once and then you can pass the local path to the controller to skip the network query step. 

> The first time a Controller is initialized, the game environment containing the 3D scenes will be downloaded to `$HOME/.ai2thor`.

If you are cloning the ai2thor repo, you'll have all the binaries you need and can skip the setup. However, based on your question I assume you want to install the `pip` version. Considering you have an internet connection for installing AI2Thor, for a fresh install:

```
$ pip install ai2thor
```

Then download the binaries by running the controller once, you can use download only mode:

```
python3 -c "import ai2thor.controller; ai2thor.controller.Controller(download_only=True)"
```

Next, you need to find the binary address, it should look like sth like this:

```
~/.ai2thor/releases/thor-Linux64-a5739c7f142769433c2a0b25e8c1570a50a7cc9c/thor-Linux64-a5739c7f142769433c2a0b25e8c1570a50a7cc9c
```

Then all you need to do is to pass this address to the Controller constructor as `local_executable_path`, it won't look for network connection anymore:

```
import ai2thor.controller
c = ai2thor.controller.Controller(local_executable_path='/home/YourCoolUsername/.ai2thor/releases/thor-Linux64-a5739c7f142769433c2a0b25e8c1570a50a7cc9c/thor-Linux64-a5739c7f142769433c2a0b25e8c1570a50a7cc9c')
```

**Comment by ekolve** [comment]
Issues appears to be resolved.  Please re-open if there are issues running offline (assuming the binary has been downloaded).
