### ISSUE TITLE
'RotateHand' is broken/hangs

### ISSUE THREAD

**Issue by mattdeitke** [allenai/ai2thor#455]
In the simplest form
```python
from ai2thor.controller import Controller
c = Controller(scene='FloorPlan1')
c.step(action='RotateHand', x=90, y=-15, z=28)
```
the action hangs indefinitely. I've also tried with a few other values, and it continues to hang indefinitely.

[For reference, RotateHand is documented here.](https://ai2thor.allenai.org/ithor/documentation/actions/held-object-manipulation/#rotate-hand)

**Comment by winthos** [comment]
Just pushed a fix for this. When rotating the hand without holding anything, the hanging was happening because no actionFinished(False) call was included with the return.
