### ISSUE TITLE
install new version from pip install

### ISSUE THREAD

**Issue by ksw9446** [allenai/ai2thor#46]
hi.
I want to install latest version.
but, 'pip install ai2thor' command install 0.0.27 version.
How can I install latest version?

**Comment by roozbehm** [comment]
pip install ai2thor --upgrade

**Comment by ekolve** [comment]
0.0.28 will be released shortly. I have to do a little more testing before I release. It should be today or tomorrow.

**Comment by ksw9446** [comment]
thank you
