### ISSUE TITLE
Invalid action: SetStateOfAllObjects

### ISSUE THREAD

**Issue by IgorDroz** [allenai/ai2thor#473]
Hey,

i am trying to use the following command:
super().step(dict(action='SetStateOfAllObjects',StateChange="CanBeDirty",forceAction=True))

and i get the error that in the title, i guess this action is deprecated, could you please tell me what is the correct new action that does the same?

Thanks!

**Comment by winthos** [comment]
Hello! That version of the action has been deprecated. Please use: https://ai2thor.allenai.org/ithor/documentation/actions/initialization/#set-objects-states-by-object-type
