### ISSUE TITLE
Simulator freeze when 'ChangeResolution' called after initializing with renderObjectImage=True

### ISSUE THREAD

**Issue by thomason-jesse** [allenai/ai2thor#477]
Minimum to reproduce in ipython:

`In [1]: import ai2thor`
`In [2]: ai2thor.__version__`
`Out[2]: '2.4.10'`
`In [3]: from ai2thor.controller import Controller`
`In [4]: c = Controller(renderObjectImage=True)`
`Initialize return: {'cameraNearPlane': 0.1, 'cameraFarPlane': 20.0}`
`In [5]: c.step(action="ChangeResolution", x=500, y=500)`

The final call ([5]) never returns.

**Comment by mattdeitke** [comment]
Hey, I was able to reproduce this error. The quick fix is to use `height` and `width` parameters upon initialization, as in:
```python
from ai2thor.controller import Controller
c = Controller(renderObjectImage=True, width=500, height=500)
```

**Comment by thomason-jesse** [comment]
Thanks! That is a much cleaner solution than my workaround (to initialize without `renderObjectImage`, then change the resolution, then re-initialize via an `Initialize` step with `renderObjectImage`).
