### ISSUE TITLE
How can I collect expert trajectories to run imitation learning ?

### ISSUE THREAD

**Issue by shamanez** [allenai/ai2thor#48]
I want to move my agent inside the environment more like a human and collect visual frames and, actions in each frame.  Let's say a coffee making task in a kitchen where agent interacts with fridge, coffee machines, sink and the mug. How can I collect this data ?

**Comment by roozbehm** [comment]
The best way is to implement an agent that receives input from the keyboard. You need to map the keys to the actions in THOR.

**Comment by shamanez** [comment]
So basically I need my agent to move from coffee machine to fridge then to sink and between some other common places in the kitchen. Is there an already implemented agent?

**Comment by roozbehm** [comment]
It is very easy to implement. You just need to map input keys to actions.

**Comment by shamanez** [comment]
yeah, I implemented. Can you also point me out how can I use shortest path function :)
