### ISSUE TITLE
Capturing and saving images of scene

### ISSUE THREAD

**Issue by sushrut3** [allenai/ai2thor#487]
How can I capture and save images of the current scene either from the robots perspective or from a free body ?

**Comment by mattdeitke** [comment]
Hey @sushrut3!

Try using:
```python
from PIL import Image
from ai2thor.controller import Controller

controller = Controller()
for i in range(5):
    Image.fromarray(controller.last_event.frame).save(f'{i}.png')
    controller.step('MoveAhead')
```

**Comment by sushrut3** [comment]
Thanks @mattdeitke I'll try this.

Also, if I'm running the scenes in Unity is there a way I could automate this process ? Like after playing the Unity scene, save pictures like every 5 secs ?

**Comment by sushrut3** [comment]
> Hey @sushrut3!
> 
> Try using:
> 
> ```python
> from PIL import Image
> from ai2thor.controller import Controller
> 
> controller = Controller()
> for i in range(5):
>     Image.fromarray(controller.last_event.frame).save(f'{i}.png')
>     controller.step('MoveAhead')
> ```

Hey @mattdeitke this works, thanks :D

**Comment by sushrut3** [comment]
> Thanks @mattdeitke I'll try this.
> 
> Also, if I'm running the scenes in Unity is there a way I could automate this process ? Like after playing the Unity scene, save pictures like every 5 secs ?

Just wanted to know about this as well

**Comment by mattdeitke** [comment]
Sure! If you want to save images every five seconds, you can run something like:
```python
from PIL import Image
from ai2thor.controller import Controller
import time

controller = Controller()
for second_batch in range(20):
    start = time.time()
    while True:
            controller.step('MoveAhead')
            if time.time() - start > 5:
                Image.fromarray(controller.last_event.frame).save(f'{second_batch}.png')
                # 5 seconds elapsed
                break
```

This will batch images into groups (based on their file names) every 5 seconds :)

---

One warning with this approach is that depending on `time` is a bit dangerous. Here, if you run the same code above multiple times, it's possible that you'd get different results.

An alternative approach would be to save every, say, 10 different **frames**:
```python
from PIL import Image
from ai2thor.controller import Controller

controller = Controller()
for saved_frame in range(20):
    for run_frame in range(10):
        controller.setp('MoveAhead')
    # 10 frames have passed
    Image.fromarray(controller.last_event.frame).save(f'{second_batch}.png')
```

The frame approach would then be reproducible across runs.

**Comment by sushrut3** [comment]
Oh okay, thank you for your help :D

**Comment by sushrut3** [comment]
Closing the issue
