### ISSUE TITLE
Automated Robot Navigation in Scene

### ISSUE THREAD

**Issue by sushrut3** [allenai/ai2thor#488]
Can I make the robot navigate the scene on it's own, i.e without user inputs. The robot should cover all the positions of the scene with the user telling it the way.

**Comment by mattdeitke** [comment]
Do you mean just going to each possible position? If so, use `GetReachablePositions`:
```python
from ai2thor.controller import Controller
 c = Controller()
event = c.step('GetReachablePositions')
positions = event.metadata['reachablePositions']
for pos in positions:
    for rotation in (0, 90, 180, 270):
        c.step('TeleportFull', rotation=dict(x=0.0, y=rotation, z=0.0), **pos)
```
The above code should move to all the position and rotation combinations in a scene.

**Comment by sushrut3** [comment]
Oh okay, I'll give this a try
