### ISSUE TITLE
Randomly but logically placing objects into a scene 

### ISSUE THREAD

**Issue by sushrut3** [allenai/ai2thor#489]
Given a list of objects, can I randomly but logically place the objects into the scene ?  For eg, an apple should be in the kitchen area, towel, near the bathroom. 
Basically, just given a list of objects I want to randomly place them in logical area.

**Comment by mattdeitke** [comment]
For all scenes, the should already be fairly logically placed (as in the apples are in the kitchen scenes, and hand-towels are in the bathrooms).

But, if you want to re-randomize the object positions within the current room, check out [object-position-randomization](https://ai2thor.allenai.org/ithor/documentation/actions/initialization/#object-position-randomization) on the docs :)

**Comment by sushrut3** [comment]
Oh okay, object position randomization might work for my application, I'll try it out. But my major problem is adding more objects to an existing scene. If I wanted to work with one scene I would've added the objects manually, but I want to collect images from multiple scenes. Also, I want to make existing scenes denser by adding more objects. 

In simple words, given a list of objects can I put them in a scene (at logical places), without manually assigning positions.

**Comment by mattdeitke** [comment]
Hey, so... kinda.

Within [Object Position Randomization](https://ai2thor.allenai.org/ithor/documentation/actions/initialization/#object-position-randomization)  you can set the number of duplicate objects of a certain object type. But, the duplicated object types will only come from the current scene.

So, using Object Position Randomization with duplicates won't spawn an object from scene FloorPlan1 into FloorPlan2. It will simply duplicate object types that are already in FloorPlan2.

**Comment by sushrut3** [comment]
Thank you, I think I've got enough
