### ISSUE TITLE
Tutorial Update - How to know the positions of exact objects 

### ISSUE THREAD

**Issue by shamanez** [allenai/ai2thor#49]
Hi, 
I am following the tutorial examples. Following code will make agent look at the mug. But how do we know other positions of the objects to do imitation learning? (Eg: Finding the Fridge) 

`controller.step(dict(action='Teleport', x=-1.25, y=1.00, z=-1.5))
 controller.step(dict(action='LookDown'))
 event = controller.step(dict(action='Rotate', rotation=90))`

**Comment by castielblak** [comment]
Please, check out [the tutorial.](https://ai2thor.allenai.org/tutorials/event-metadata)

> Each call to the controller.step() function returns an Event object that contains a rich amount of information about the state of the environment and each of the objects within the environment.
