### ISSUE TITLE
MultiAgent crashes on any 'OpenObject' action

### ISSUE THREAD

**Issue by thomason-jesse** [allenai/ai2thor#492]
Code to reproduce:

`In [1]: import ai2thor`

`In [2]: ai2thor.__version__`
`Out[2]: '2.4.10'`

`In [3]: from ai2thor.controller import Controller`

`In [4]: controller = Controller(gridSize=0.25, agentCount=2)`
`Initialize return: {'cameraNearPlane': 0.1, 'cameraFarPlane': 20.0}`

`In [5]: e = controller.step(action='MoveAhead', agentId=0)`

`In [6]: controller.step(action="OpenObject", agentId=0, objectId=e.metadata['objects'][0]['objectId'], moveMagnitude=1.0)`

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-11ad266622d9> in <module>
----> 1 controller.step(action="OpenObject", agentId=0, objectId=e.metadata['objects'][0]['objectId'], moveMagnitude=1.0)

~/Library/Python/3.8/lib/python/site-packages/ai2thor/controller.py in step(self, action, **action_args)
    648 
    649             force_visible = action.get('forceVisible', False)
--> 650             if not force_visible and self.last_event.instance_detections2D and action['objectId'] not in self.last_event.instance_detections2D:
    651                 should_fail = True
    652 

AttributeError: 'MultiAgentEvent' object has no attribute 'instance_detections2D'

**Comment by ekolve** [comment]
Fixed with https://github.com/allenai/ai2thor/commit/422ec26508981befae54e9e39ffb2add3beab58b

I'll do a release later today (it will be 2.4.22).
