### ISSUE TITLE
Run ai2thor from repo and not by installing from terminal

### ISSUE THREAD

**Issue by sushrut3** [allenai/ai2thor#493]
It is a noob question but how do I run ai2thor by cloning the repo and using it rather than installing it from the terminal? As I wanted to make some changes to the code.

Which directory do I place my python script. And how do I import ai2thor?

**Comment by sushrut3** [comment]
Solved

**Comment by alphonsusadubredu** [comment]
How did you do it? Did you just clone the repo and run your scripts in the repo?

**Comment by mattdeitke** [comment]
Cloning the repo and running scripts inside of the repo should really only be necessary if you're making changes to the Python side (which mostly just creates a server that communicates with Unity).

If you're making changes to the Unity side (which controls the physics engine, objects, scenes, action behavior, etc.), after making changes to Unity, you'll need to run `invoke local-build` from the root of the directory and then point the controller to this build (see: [Unity Development](https://github.com/allenai/ai2thor#unity-development) and [this discussion](https://github.com/allenai/ai2thor/discussions/551#discussioncomment-218183)). Pointing to the build can then be done in any repo.
