### ISSUE TITLE
Open ai2thor with unity in linux

### ISSUE THREAD

**Issue by he727425209** [allenai/ai2thor#50]
Hi, I was trying to open ai2thor with unity in Linux(unfortunately I don't have a MacOS). When I run the command invoke local-build, it throws an error and I was not able to get it work. I am wondering if anyone happens to know the solution to this?

**Comment by ekolve** [comment]
Are you trying to use the Unity3d editor for Linux? This is still in beta and not something we are going to support until Unity declares it production. I experimented with it in the past and found it to be unstable.

**Comment by he727425209** [comment]
I know that ai2thor have action features in it already (move ahead, backward, left, right, rotate, etc.), but I wanted to add more features into it, so I want to edit the source code. However, I don't know how to open it inside the unity3d editor. I am using Ubuntu 16.04.
