### ISSUE TITLE
Objects in entire FloorPlan and not current scene (frame)

### ISSUE THREAD

**Issue by sushrut3** [allenai/ai2thor#502]
How do I get a list of all object and locations in the entire floorplan (eg. Floorplan 28) and not just the current scene (frame) from the robots perspective.

**Comment by mattdeitke** [comment]
Hey. From the metadata, you should be able to access the data of all objects in the scene:
```python
from ai2thor.controller import Controller
c = Controller(scene='FloorPlan28')
for _ in range(5):
    object_data = c.last_event.metadata['objects']  # <----------
    c.step('MoveAhead')
```
Matt :)

**Comment by sushrut3** [comment]
Sorry it was a noob question but thank you so much
