### ISSUE TITLE
Actions other than 'Random Initall Spawn' for adding objects into the scene ?

### ISSUE THREAD

**Issue by sushrut3** [allenai/ai2thor#503]
Is there any other action for adding object into the scene ? I also wanted to confirm that it is only possible to add objects that already exist in the scene and nothing from outside ? (For eg. I cant add an apple in a bathroom, because it didnt exist before ?) 
Or have I got something wrong ?

**Comment by mattdeitke** [comment]
That is correct from the Python side in the current codebase.

**Comment by sushrut3** [comment]
Okay, thank you so much.
Closing
