### ISSUE TITLE
Queue size as parameter in `wsgi_server`?

### ISSUE THREAD

**Issue by thomason-jesse** [allenai/ai2thor#506]
When pushing actions from multiple clients in multi-agent mode, it's easy/common to flood the `wsgi_server` queues, causing queue full crashes since they're size 1. Would it be possible to increase this queue size, or make it a parameter to `controller`?

[ https://github.com/allenai/ai2thor/blob/master/ai2thor/wsgi_server.py#L148 ]

Example crash:
```
  File "/usr/local/lib/python3.8/site-packages/ai2thor/controller.py", line 693, in step
    self.server.send(action)
  File "/usr/local/lib/python3.8/site-packages/ai2thor/wsgi_server.py", line 216, in send
    self.response_queue.put_nowait(action)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/queue.py", line 190, in put_nowait
    return self.put(item, block=False)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/queue.py", line 136, in put
    raise Full
queue.Full
```

**Comment by ekolve** [comment]
Can you describe how you are getting this error? Are you sharing a single controller with multiple threads?

**Comment by thomason-jesse** [comment]
Sure. It's a single controller being communicated with via flask server from a web app. The app allows multiple clients to connect (e.g., for MultiAgent) and send actions, but all the action processing goes through a single thread. I can get the error by basically spamming actions to both agents (e.g., send a rapid stream of 'MoveAhead' commands to both agentID=0 and agentID=1).

**Comment by ekolve** [comment]
Could you share code how you are able to get the failure? If all actions are sent through the step function on the controller in a single thread it shouldn't matter how many agents were initialized in Unity.

**Comment by thomason-jesse** [comment]
I'll try to find a way to minimally reproduce the error and share. There are other threads reading events from the `controller` but only one thread calling `step`. I'll dig in and see if I can reproduce it in just a few lines.

**Comment by thomason-jesse** [comment]
This error was entirely on me. If `controller` is only attached to one thread, it cannot be produced, but if multiple threads access the same `controller` instance, the queue can be overloaded.
