### ISSUE TITLE
build unity executable in ubuntu 16.04

### ISSUE THREAD

**Issue by he727425209** [allenai/ai2thor#51]
Hi,
I am trying to build the unity executable for ai2thor in ubunti16.04, and I am confuse on where I should modified to get invoke local-build work.

Best

**Comment by ekolve** [comment]
To build ai2thor you will need a Mac OSX machine or Windows machine. The Unity Editor (needed to compile the project) is in beta.  You may be able to adjust the path in tasks.py to point to the editor executable on Linux, but we have never tested this.  

You also may be able to open the project in the Linux editor and use Build menu to build the project.
