### ISSUE TITLE
3D Bounding boxes for overlapping objects ?

### ISSUE THREAD

**Issue by sushrut3** [allenai/ai2thor#512]
As per my knowledge, 2D bounding are created for every frame. Is it possible to 3D coordinates for cases where one object covers the other? In such cases I want to know which object is infront and which one is back.
Or is there any other way I could detect this ambiguity.

**Comment by winthos** [comment]
I believe you can construct what you need with the `axisAlignedBoundingBox` attribute of any objects in question. See the documentation here for more details: https://ai2thor.allenai.org/ithor/documentation/metadata/#object-attributes-

Basically this box is a 3d bounds that encapsulates all objects, but is aligned to the world axis in terms of orientation. This means that a given object, say a pencil, might have a different volume box depending on the pencil's rotation relative to the world axes. Even with this potential variance, you can use the bounds to plot out a boxes to see if they intersect or overlap.

Additionally, you could do something like compare the 2D bounds for a set of objects, and then layer those bounds based on the distance of each object to the agent. This can be calculated by getting the distance between the agent's position and the object's position.

The object's position is also listed in the object attribute metadata linked above, and the agent's position can be found in the agent attributes here: https://ai2thor.allenai.org/ithor/documentation/metadata/#agent-attributes-

**Comment by sushrut3** [comment]
Thank you so much
