### ISSUE TITLE
Object-Object relation Information

### ISSUE THREAD

**Issue by sushrut3** [allenai/ai2thor#513]
I know metadata gives a lot of information about the agent, objects, scenes etc but I'm not sure as how to get the relations between objects. For eg. if a mug is placed on a table, can I get a relation like {mug <- top <- table} or basically something which can tell me that theres a mug on the table ?

**Comment by winthos** [comment]
Objects like tables are classified as `receptacles`. This means they can contain other objects, and will track this information in their metadata. Please refer to this description of what objects with this `receptacle` property involve: https://ai2thor.allenai.org/ithor/documentation/objects/actionable-properties/#receptacle

Both the object that is being contained by the receptacle, and the receptacle object itself will show any "containment" info in their metadata.

Take a look at this example of an object's metadata: https://ai2thor.allenai.org/ithor/documentation/metadata/#object-attributes-

The `receptacleObjectIds` attribute will report all other sim objects contained by a receptacle object. You can also check if any given object has the receptacle property by looking at the `receptacle` attribute. If this is `True`, then the object is a receptacle and can report other objects contained via the `receptacleObjectIds` attribute.

Additionally, any objects that are not themselves a receptacle but are contained by a receptacle will have the `parentReceptacles` attribute populated. The example object in the documentation, the `DeskLamp`, is currently on top of a `Dresser` object.

A more detailed breakdown of each attribute, what they mean, and how they might interact is detailed in the documentation.

**Comment by sushrut3** [comment]
Thank you
