### ISSUE TITLE
Calling `AddThirdPartyCamera` Destroys/Collapses the `event.frame` data in MultiAgent

### ISSUE THREAD

**Issue by thomason-jesse** [allenai/ai2thor#514]
When `AddThirdPartyCamera` is called with N>1 agents, the frame information for the agent events is collapsed such that both show the same image. Subsequent calls to `UpdateThirdPartyCamera`, interestingly, can switch -which- agent frame is represented, but both are no longer available. Reproduce with:

```
> from ai2thor.controller import Controller
> import numpy as np
> controller = Controller(gridSize=0.25, agentCount=2, snapToGrid=True, renderObjectImage=True, visibilityDistance=1.5)
Initialize return: {'cameraNearPlane': 0.1, 'cameraFarPlane': 20.0}
> np.all(controller.last_event.events[1].frame == controller.last_event.events[0].frame)
False
> event = controller.step(dict(action='AddThirdPartyCamera', rotation=dict(x=0, y=0, z=90), position=dict(x=-1.0, z=-2.0, y=1.0)))
> np.all(controller.last_event.events[1].frame == controller.last_event.events[0].frame)
True
```

**Comment by thomason-jesse** [comment]
Bump. This is still true and is super destructive / makes using third party cameras in multiagent mode impossible.

**Comment by thomason-jesse** [comment]
This still appears for me even when replicating the unit test added in the above commit.

```
> import ai2thor.controller
> ai2thor.controller.COMMIT_ID = '520ab0915c6d0bc2a4cf01bf8af0bedd6145426d'
> from ai2thor.controller import Controller
> from ai2thor.fifo_server import FifoServer
> controller = Controller(server_class=FifoServer, agentCount=2, scene='FloorPlan28', local_build=True)
Initialize return: {'cameraNearPlane': 0.10000000149011612, 'cameraFarPlane': 20.0}
> np.all(controller.last_event.events[1].frame == controller.last_event.events[0].frame)
False
> controller.step(dict(action='AddThirdPartyCamera', rotation=dict(x=0, y=0, z=90), position=dict(x=-1.0, z=-2.0, y=1.0)))
> np.all(controller.last_event.events[1].frame == controller.last_event.events[0].frame)
True
```

**Comment by ekolve** [comment]
Could you try with the latest master without localBuild?

I have a test that gets run (and succeeds):

https://github.com/allenai/ai2thor/blob/master/ai2thor/tests/test_unity.py#L52

**Comment by ekolve** [comment]
Ahh, i think the issue might be that you need to update your python code.  The fix didn't occur on the unity side.

**Comment by thomason-jesse** [comment]
That did the trick, thanks.

It's worth noting (either here or in documentation) the location of `third_party_camera_frames` data. In particular, in multiagent mode, it appears:

`controller.last_event.third_party_camera_frames` is an empty list
`controller.last_event.events[0].third_party_camera_frames == controller.last_event.events[1].third_party_camera_frames` is a list of third party camera frames replicated in both event structures.
