### ISSUE TITLE
Bounding boxes for third party camera frames

### ISSUE THREAD

**Issue by sushrut3** [allenai/ai2thor#516]
event = c.step(dict(action='AddThirdPartyCamera', rotation=dict(x=0, y=0, z=90), position=dict(x=-1.0, z=-2.0, y=1.0, renderObjectImage=True)))
p = event.instance_detections2D

I get an empty list. I'm not exactly sure on how to get bounding boxes for my third party camera. Any way which I could achieve this ?

**Comment by mattdeitke** [comment]
Currently accessing instance detections from a 3rd party camera is not supported. But, it's an open discussion that will be supported at some point (along with depth/object segmentation from ThirdPartyCamera's).

I suspect with using the currently unofficial MapFrame in #445, you might be able to access instance detections/bounding boxes. I would try something along the lines of:
```python
from ai2thor.controller import Controller
c = Controller(renderObjectImage=True)

# top looking down
c.step('ToggleMapView')
event = c.step('TeleportFull', rotation=dict(x=0, y=0, z=90), position=dict(x=-1.0, z=-2.0, y=1.0))
event.instance_detections2D

# go back to agent's view
c.step('ToggleMapView')
```
I can't guarantee that this works (especially the teleport part), but using the map frame seems like the current best route.

**Comment by ekolve** [comment]
This is now possible.

```python
from ai2thor.controller import Controller
c = Controller(renderInstanceSegmentation=True)
e = c.step(dict(action='AddThirdPartyCamera', rotation=dict(x=0, y=0, z=90), position=dict(x=-1.0, z=-2.0, y=1.0)))
print(e.third_party_instance_segmentation_frames)
```

**Comment by ekolve** [comment]
Closing - issue appears to be resolved.
