### ISSUE TITLE
`renderObjectImage` slows the `step` function dramatically - can it be its own action?

### ISSUE THREAD

**Issue by thomason-jesse** [allenai/ai2thor#526]
From quick timings on a few machines, `step` with movement actions takes .1 to .15 seconds when `renderObjectImage=False`. This time per step jumps up to .8-.9 seconds with `renderObjectImage=True`. In some applications, we don't need the object segmentation mask at every timestep. Would it be possible to make `renderObjectImage` an _action_ instead, such that we can take a step to render and get the object segmentation frame (a slow step), but have the rest of the steps not bothering generating it so that the simulator runs faster?

**Comment by mattdeitke** [comment]
Hey Jesse, this is supported, but not currently documented, with:
```python
from ai2thor.controller import Controller
c = Controller()
event = c.step(action='MoveAhead', renderObjectImage=True)
event.instance_segmentation_frame  # not empty
```

**Comment by thomason-jesse** [comment]
Very cool! This is exactly what I would need. It seems this functionality is incompatible with `AddThirdPartyCamera`. Minimum code to reproduce:
```
from ai2thor.controller import Controller
c = Controller(width=1250, height=1250)
c.step(action='Pass', agent_id=0, renderObjectImage=True) <--- hangs forever
```

Any idea if this will be officially supported or if there's a way to make it compatible with third party camera views? Here the segmentation frame I'm asking for is `agent_id=0`, the agent, not the camera frame, but clearly there's some conflict.

**Comment by mattdeitke** [comment]
There's near-term plans to depreciate the current third party camera setup and transition that idea into invisible "ghost" agents that can float. Here, the advantage for the "ghost" agent over the current third party cameras are:
1. Inherit all the navigation and interaction actions that the default blue agent possesses. (e.g., teleporting the camera, rotating the camera, and moving the camera all inherit the same functionality and can use the same syntax as is done with the current agent setup.)
2. Inherit the ability to render different features from an image, such as depth and segmentation, without needing to write a bunch of new functionality for stand alone third party cameras.

So, I suspect when this feature is rolled out, it should solve many problems like this, which roughly comes from (2) here.

**Comment by thomason-jesse** [comment]
I see. I'm not sure this issue is tied specifically to 3rdPartyCamera, though. For example, it happens with any multiagent context too:
```
from ai2thor.controller import Controller
c = Controller(agentCount=2)
c.step(action='RotateLeft', agent_id=0, renderObjectImage=True) <--- hangs forever
```

**Comment by ekolve** [comment]
This is now fixed with 1a2bdf51801e72bcc39366d6af00fb801cc5b2ec and 1a2bdf51801e72bcc39366d6af00fb801cc5b2ec

**Comment by thomason-jesse** [comment]
This issue is re-introduced as of https://github.com/allenai/ai2thor/commit/520ab0915c6d0bc2a4cf01bf8af0bedd6145426d

```
import ai2thor.controller
ai2thor.controller.COMMIT_ID = '520ab0915c6d0bc2a4cf01bf8af0bedd6145426d'
from ai2thor.controller import Controller

controller = Controller(agentCount=2)
controller.step(dict(action='AddThirdPartyCamera', rotation=dict(x=0, y=0, z=90), position=dict(x=-1.0, z=-2.0, y=1.0)))

print("Executing pass action with agent_id=0")
controller.step(action='Pass', agent_id=0, renderObjectImage=True)
print('... done')
```

From the above, the output is
```
executing Pass in get_interactable_hotspots, sim_agent_id= 0
```
Followed by the program hanging until manual interrupt.

**Comment by thomason-jesse** [comment]
A related issue, when starting the sim with `renderObjectImage=True`, third party camera adds also hang the simulator.

```
import ai2thor.controller
ai2thor.controller.COMMIT_ID = '520ab0915c6d0bc2a4cf01bf8af0bedd6145426d'
from ai2thor.controller import Controller

controller = Controller(agentCount=2, renderObjectImage=True)
print("Adding third party camera")
controller.step(dict(action='AddThirdPartyCamera', rotation=dict(x=0, y=0, z=90), position=dict(x=-1.0, z=-2.0, y=1.0)))
print("... done")
```

Output
```
Adding third party camera
```
Followed by the program hanging until manual interrupt.

**Comment by thomason-jesse** [comment]
Whatever is causing the above might also/actually be related to the ai2thor version. The above code freezes as described with ai2thor === 2.5.1 but the below code executes fine in ai2thor == 2.4.22
```
import ai2thor.controller
ai2thor.controller.COMMIT_ID = '69aa1198203d69b9b8b2c48962d2ab88e1793b40'
from ai2thor.controller import Controller

controller = Controller(agentCount=1)
print("Adding third party camera")
controller.step(dict(action='AddThirdPartyCamera', rotation=dict(x=0, y=0, z=90), position=dict(x=-1.0, z=-2.0, y=1.0)))
print("... done")

print("Executing pass action with agent_id=0")
controller.step(action='Pass', agent_id=0, renderObjectImage=True)
print('... done')
```
