### ISSUE TITLE
How can I use shortest path and collect expert's kind of state and action pairs ?

### ISSUE THREAD

**Issue by shamanez** [allenai/ai2thor#53]
I read in the paper that framework has a function that we can send the agent from one place to another place in the shortest possible path. I want to know how to use this function. Can you add it to the tutorial?

**Comment by danielgordon10** [comment]
This is done via the Teleport command and computing a shortest path using the networkx. The path is only used to infer the path length, we don't actually navigate through it. See other issues about networkx details. We will probably expose this functionality soon.

**Comment by shamanez** [comment]
So if I start from state 10 in the bathroom and my target is in 26th state and used teleport it should give me the **shortest** Possible path which consists of states and actions right?

**Comment by danielgordon10** [comment]
Not quite. Teleport literally moves the agent, ignoring any obstacle checking, to a desired location. Using a precompute graph of the scene points, we then get the shortest path via Dijkstra's algorithm/A*. See https://github.com/allenai/ai2thor/issues/9 for more on that.

**Comment by shamanez** [comment]
In[ this](https://github.com/longhuei/HulkSmashThor) repo, they got shortest paths by accessing the hdf5 dumps of the states. But I think in this way get the shortest path by also considering the obstacles

**Comment by danielgordon10** [comment]
So what do you actually need? Do you need the actions that take an agent from point A to point B using "MoveAhead" and so on? Or do you just want the cost of the shortest path? I think I misunderstood before that you just wanted the cost, but the answer is still the same. The networkx package can give you a shortest cost path on a weighted or unweighted graph including the cost of the path as well as the nodes and edges of the graph. We have some internal code for running a breadth first search to generate the navigation graph which can be used by networkx to generate shortest paths, but it assumes a static room IE no opened doors or moved around objects. It does still implicitly consider obstacles if they couldn't be navigated through when generating the graph. You can also look into dynamically computing paths on the Unity side via https://docs.unity3d.com/Manual/Navigation.html but that is beyond what we offer currently.

**Comment by danielgordon10** [comment]
[here](https://github.com/danielgordon10/thor-iqa-cvpr-2018/blob/master/graph/graph_obj.py#L166) is a link to an example of using networkx to compute paths on precomputed graphs.

**Comment by mattdeitke** [comment]
Merging a follow-up discussion to #443.
