### ISSUE TITLE
Hide object in robot view when it's been pickedup

### ISSUE THREAD

**Issue by XiaoLiSean** [allenai/ai2thor#537]
Hi, I'm currently working on visual navigation using the iTHOR. I noticed that when the agent picks up the object (e.g. mug) and moves with the object, the object will constantly appear on the frame:

![Screenshot from 2020-12-07 01-45-18](https://user-images.githubusercontent.com/58400416/101318183-e6b16000-382d-11eb-8cc8-8bcba18ca7df.png)

I'm wondering if there is any possible way to hide the object from the robot camera. Just like what we have in this video https://www.youtube.com/watch?v=MvvAhF4HZ8s.
Thanks!

**Comment by mattdeitke** [comment]
Hey, yes, this is currently possible! It's done using `HideObject` and `UnhideObject`, where each of these actions would take in the held object's id. Here is a basic snippet:

```python
from ai2thor.controller import Controller

controller = Controller(scene='FloorPlan1')

# get all pickupable objects
pickupable_objs = [
    obj['objectId'] for obj in controller.last_event.metadata['objects']
    if obj['pickupable']]

# choose an object to pickup (and pick it up)
obj_id_to_pickup = pickupable_objs[0]
pickup_event = controller.step(
    'PickupObject', objectId=obj_id_to_pickup, forceAction=True)

# metadata to determine if objectId was actually picked up
if (inventory := pickup_event.metadata['inventoryObjects']):
    picked_up_id = inventory[0]['objectId']

    # hide and unhide the object
    hide_event = controller.step('HideObject', objectId=picked_up_id)
    unhide_event = controller.step('UnhideObject', objectId=picked_up_id)
```

As a sanity check the results can also be plotted:

![image](https://user-images.githubusercontent.com/28768645/101322021-2884db00-381b-11eb-983a-d81e240d35f0.png)

<details>
<summary>Plotting code</summary>

```python
import matplotlib.pyplot as plt

fig, axs = plt.subplots(1, 3, figsize=(9, 3))
for i in range(3):
    axs[i].axis('off')

axs[0].set_title('After Pickup')
axs[0].imshow(pickup_event.frame)

axs[1].set_title('After Hide')
axs[1].imshow(hide_event.frame)

axs[2].set_title('After Unhide')
axs[2].imshow(unhide_event.frame)
```
</details>

Here,
```python
event.event.metadata['inventoryObjects'][0]['objectId']
```
is particularly helpful as it will track if an object is currently picked up.

---

Also note that the Walrus operator was introduced in Python3.8. For earlier versions, replace
```python
# metadata to determine if objectId was actually picked up
if (inventory := pickup_event.metadata['inventoryObjects']):
    picked_up_id = inventory[0]['objectId']
```
with
```python
# metadata to determine if objectId was actually picked up
inventory = pickup_event.metadata['inventoryObjects']
if inventory:
    picked_up_id = inventory[0]['objectId']

**Comment by XiaoLiSean** [comment]
Thanks very much!
