### ISSUE TITLE
Scene assets redownload after upgrade

### ISSUE THREAD

**Issue by zkytony** [allenai/ai2thor#545]
I upgraded from 2.4.22 to 2.5.0 by
```
pip install --upgrade ai2thor
```
When I tried to run some existing code that launches a controller, the program tries to download new scene assets (about 524MB) into `~/.ai2thor`. Is this expected? Is there a way to use previously downloaded assets and avoid downloading again, or is this not recommended?

Thanks!

**Comment by zkytony** [comment]
It is expected, because the asset file has a commit id matching the release's id.

**Comment by ekolve** [comment]
Sorry for the late reply - when upgrading ai2thor it is expected that a new Unity binary will be downloaded during the first execution.  This binary is cached under `$HOME/.ai2thor/releases`.
