### ISSUE TITLE
potential bug in 2.5.1 not in 2.5.0 : This target object is NOT a receptacle!

### ISSUE THREAD

**Issue by nikepupu** [allenai/ai2thor#554]
When I execute a putObject command in 2.5.1 I got the following error  from the metadata:
This target object is NOT a receptacle!

However, it works fine in 2.5.0.
I checked if this object is a receptacle at the beginning (1st frame)

**Comment by ekolve** [comment]
Are you passing the receptacle as receptacleObjectId or objectId to PutObject? The PutObject action was recently changed to fix the parameter names to match the documentation.

**Comment by nikepupu** [comment]
Thanks. I think that is the issue.
