### ISSUE TITLE
Is that possible to put specific objects in the receptacle through SetObjectPoses Action

### ISSUE THREAD

**Issue by StOnEGiggity** [allenai/ai2thor#563]
Hi, I am trying to initialize the scene and put most objects in the receptacles. I notice there exists a "SetObjectPoses" action and I want to know is that possible to use this action to implement my task? For example, "position" is in one receptacle.

If the answer is yes, how do I know the possible placement position and check objects are placed right as I imagined.

Thanks a lot.

**Comment by winthos** [comment]
Yes! you could try something like using the `PlaceObjectAtPoint` and `GetSpawnCoordinatesAboveReceptacle` actions. `PlaceObjectAtPoint` takes a point in space, and finds a surface below that point where an object can be placed flush against that surface. The `GetSpawnCoordinatesAboveReceptacle` will return a number of potential coordinates above any given receptacle typed object that could be used as potential points for `PlaceObjectAtPoint`.

After placing objects using these two actions, you can then grab their metadata and reset the scene using `SetObjectPoses` to set all the objects at once.

**Comment by StOnEGiggity** [comment]
Thank you very much.
