### ISSUE TITLE
Recovering scene initialization from older THOR version configurations

### ISSUE THREAD

**Issue by shuyanzhou** [allenai/ai2thor#576]
Hi, 

I am trying to initialize the environment with object positions recorded from an out-dated THOR version (0.0.34). While the layouts of each floor plan almost look the same from the images, their position (x, y, z, etc. from the metadata['objects']) changes in the latest version. I am not able to use the position information from the older version to initialize the objects. I am wondering if there is a way to recovering the same scene between these two versions? Thanks!

**Comment by winthos** [comment]
There is not an easy way to recover the exact same scenes and object placements across two versions. There are often minor changes to object positions, or updating scene or object geometry between releases. Additionally, the functionality of certain actions can often change, so the old scenes and objects can also become deprecated in that way.

**Comment by shuyanzhou** [comment]
make sense, thanks for the reply @winthos
