### ISSUE TITLE
Default values of object attributes

### ISSUE THREAD

**Issue by skulkarni322** [allenai/ai2thor#582]
Are object attributes like 'isFilledWithLiquid' , 'isBroken' , 'isSliced'  always set to False by default ? and need to be manipulated to change their values.

**Comment by skulkarni322** [comment]
@mattdeitke can you give any insights?

**Comment by mattdeitke** [comment]
This is mostly the case, with the exception being`WineBottle`s are filled with liuid in many many kitchens.

Here is a Colab notebook that reproduces the results, which checks the state of every starting object in every scene:
https://colab.research.google.com/drive/1XjEEz9Q69Sr8D9KXYXuXvBZpu2x51Z-s?usp=sharing

**Comment by skulkarni322** [comment]
Oh okay, got it. Thanks. The notebook helps a lot
