### ISSUE TITLE
Object state change issue

### ISSUE THREAD

**Issue by Frost-99** [allenai/ai2thor#588]
Hi,

I discovered that in a kitchen scene if I put a sliced bread into the toaster and then toggle on the toaster, the `isCooked ` state of that sliced bread is not changed. But if I turn on the toaster first and then put in the sliced bread, the state changes correctly. I haven't test this with other receptacles that can change object states so I'm not sure if similar issues exist for other things.

I'm using version 2.5.3.

**Comment by winthos** [comment]
Thanks for finding this issue! This has been fixed as of the [new release 2.5.4](https://github.com/allenai/ai2thor/releases/tag/2.5.4)

**Comment by Frost-99** [comment]
Hi,

Thanks for the quick response! Unfortunately, it seems 2.5.4 introduced some other problems because now every time I try to toggle something on (faucet, microwave, etc.) the environment freezes and stops to respond to any command afterwards even stop doesn't work. This problem only shows after 2.5.4.

**Comment by Frost-99** [comment]
Hi,

In 2.6.1, the issue mentioned above has been fixed! However, now if I first toggle something on and then toggle it off, the environment will freeze again like before (e.g. faucet).

**Comment by winthos** [comment]
Hello!

In a quick hotfix, the remaining edge cases should be taken care of as of 2.6.11
