### ISSUE TITLE
Disable rendering

### ISSUE THREAD

**Issue by a7b23** [allenai/ai2thor#6]
How can we disable the rendering of the game during the training phase?

**Comment by roozbehm** [comment]
The scenes change dynamically so they should be rendered. We tried to disable rendering, but we have not found a good way yet.

**Comment by ekolve** [comment]
Do you just want to receive the metadata (object positions, agent position, visible objects, etc) without the corresponding image?  If this is the case I think we should be able to support this, though it may be of limited value unless you have cached all the images ahead of time.

**Comment by a7b23** [comment]
No I wanted the image too. So I would have to do training with the simulator active only then.

**Comment by ekolve** [comment]
I am going to close the issue, because this is a limitation that Unity enforces.
