### ISSUE TITLE
adding more object

### ISSUE THREAD

**Issue by he727425209** [allenai/ai2thor#60]
Hi,

I would like to add more objects into the environment, so how do I do that? (generating unique id for simobj, etc.)

Best

**Comment by winthos** [comment]
We can give you a brief overview of the first steps involved with creating a new sim object, and if you still want to import your own custom object then It would be best to contact us directly so we can give you a much longer, more detailed overview.

Adding more Game Objects to any given scene is an involved process. The API and Unity Editor functions currently don't facilitate users adding in custom objects directly, so you would have to essentially do it from scratch.

First get Unity 2017.1.3 and open up the ai2thor/unity folder. You can navigate to Assets/Scenes and pick out which scene you want to create a new object in, and open that scene up into the editor view.

As for the new object itself, you will need to either make or obtain a Mesh for that object, import that mesh file in, and create a new Game Object with a mesh renderer that uses that mesh. You will additionally need texture files to go with the material on that mesh if you want it to look realistic. From there, you should have a game object with a transform component, and a Mesh renderer with your imported and textured mesh assigned to it. To this object add a rigid body and a box collider.

From here, the way to set up a SimObj varies wildly depending on the type of object you want to make. The best thing to do from this point is to pick a pre-existing simObj and mimic the values that it has if the object is close enough to the new custom object that you have in mind. If your custom object is different in terms of how it should behave (can you pick it up, can you open it, etc) then you will need to dive into the SimObj script itself to set it up.

If you get the object itself setup with the correct scripts, there is another set of steps where you need to edit a number of utility scripts to ensure that your new custom object can report metadata to the end user correctly, and it would be easiest to go through that in more detail separately if you require it.
