### ISSUE TITLE
Sink simobjects not visible in certain cases

### ISSUE THREAD

**Issue by ekolve** [allenai/ai2thor#61]
Review all the scenes with sinks to find any cases where the sink object is not visible when it should be or the simobj is not attached to the correct game object.

**Comment by danielgordon10** [comment]
I think the big problem here (or the one I have) is that the sink simObj will be attached to the faucet rather than the sink basin, or the whole sink unit. Fixing that would solve my problems.

**Comment by ekolve** [comment]
These have been fixed with the most recent release (1.0.1).
