### ISSUE TITLE
Object interaction example from documentation crashes with runtime error

### ISSUE THREAD

**Issue by tomsilver** [allenai/ai2thor#616]
Hi, thanks for making this awesome package available! I am just trying out the examples from the documentation and I'm hitting an error in the Object Interaction example (https://ai2thor.allenai.org/ithor/documentation/overview/examples/#object-interaction).

The error arises on this line:
```
# put the object in the microwave
event = controller.step(
    action='PutObject',
    receptacleObjectId=receptacle_object_id,
    objectId=mug_object_id,
    raise_for_failure=True)
```

Here is the traceback:
```
Traceback (most recent call last):
  File "ai2thor_test.py", line 43, in <module>
    raise_for_failure=True)
  File "/Users/tom/.pyenv/versions/3.6.7/lib/python3.6/site-packages/ai2thor/controller.py", line 874, in step
    self.last_event.metadata.get("errorMessage", f"{action} failed.")
RuntimeError: Mug_c09901d5 cannot be placed in Mug_c09901d5
```

I'm on macOS, Python 3.6.7, installed the package with pip, package version `ai2thor==2.7.2`. Thanks for your help!

**Comment by mattdeitke** [comment]
Sorry. Please use `objectId` instead of `receptacleObjectId`. The documentation is in the process of updating a bit tonight.
```
# put the object in the microwave
event = controller.step(
    action='PutObject',
    objectId=receptacle_object_id,
    objectId=mug_object_id,
    raise_for_failure=True)
```

**Comment by tomsilver** [comment]
No worries, thanks a lot for the quick reply! Just to check, only the first `objectId` should be used, with `receptable_object_id`, right? (So `objectId=mug_object_id` would be removed.) I tried that and it seems to work as expected.

**Comment by mattdeitke** [comment]
Oh, yes. This is true. Nice catch!

**Comment by tomsilver** [comment]
Great, thanks again!
