### ISSUE TITLE
Changing physical state of object in Unity editor

### ISSUE THREAD

**Issue by skulkarni322** [allenai/ai2thor#637]
I want to change the physical state of an object before placing it on my floorplan. For eg. I want to place a "broken bowl" in the room. 
How can I change the state before placing it ?

**Comment by winthos** [comment]
Check out the documentation for "object state changes" here: https://ai2thor.allenai.org/ithor/documentation/object-state-changes/#temporary-redirect

There is a temporary redirect on that page to the old documentation while we build the new page on the current site. All the information in the cached documentation is still the same and still works with the current release.

**Comment by skulkarni322** [comment]
from PIL import Image
from ai2thor.controller import Controller
c = Controller(scene='FloorPlan28')
event = c.step(action='MoveAhead', renderObjectImage=True)
meta = event.metadata['objects']
for i in range(len(meta)):
    if meta[i]['objectType']== 'Mug':
        oid = meta[i]['objectId']
        event1 = c.step('BreakObject', objectId=oid)
        break

meta1 = event1.metadata['objects']
for i in range(len(meta1)):
    if meta1[i]['objectId']==oid:
        print(meta1[i]['isBroken'])

My last print statement returns 'False' even though I've broken the Mug. Is there anything I'm doing wrong?

**Comment by mattdeitke** [comment]
Try passing in `forceAction=True`. By default, the mug is only interactable (i.e., with the default `forceAction=False`) if you are within 1.5 meters of it, and looking at it.

```python
controller.step('BreakObject', objectId=oid, forceAction=True)
```

Here it is in Colab:
https://colab.research.google.com/drive/1bqgs7mz-6z6WTIsDqqdrr1JVe1C0sx-Q?usp=sharing
