### ISSUE TITLE
PutObject 'No valid Receptacle found'

### ISSUE THREAD

**Issue by KaixiangLin** [allenai/ai2thor#650]
FloorPlan17, PutObject return 'No valid Receptacle found' and didn't put the object to target object.
After pick up a fork from dining table: 
```
event = controller.step(action='PickupObject', objectId='Fork|+01.16|+00.96|+02.52')
```
Using command as follows:
```
event = controller.step(action='PutObject', objectId='DiningTable|+01.17|+00.01|+02.57',forceAction=False, placeStationary=True)
```
event.metadata['errorMessage'] return 'No valid Receptacle found'

Tried with multiple target objects (receptacle is True) , tried with forceAction=True.

**Comment by mattdeitke** [comment]
It appears to be working as expected for me when calling `PickupObject` and `PutObject`, each with `forceAction=True` (to ignore the distance from the agent to each object):
https://colab.research.google.com/drive/1vYhcVbXe4G-QX4DJzBOSEcBZOIKFq-La?usp=sharing

**Comment by KaixiangLin** [comment]
Any difference between linux and Mac? I tested it locally on my mac.

**Comment by mattdeitke** [comment]
For something like this, there shouldn't be any differences between mac and linux. However, which version are you using?

Versions are accessible with:

```python
import ai2thor
ai2thor.__version__
```

**Comment by KaixiangLin** [comment]
my bad, was using 2.1.  latest version worked.
