### ISSUE TITLE
[Request] Preserve canonical orientation when putting down objects via `GetSpawnCoordinatesAboveReceptacle` + `PlaceObjectAtPoint` 

### ISSUE THREAD

**Issue by thomason-jesse** [allenai/ai2thor#666]
Currently, placing objects via `GetSpawnCoordinatesAboveReceptacle` + `PlaceObjectAtPoint` often loses the canonical orientation of `Plate`, `Pot`, and other objects, even for large empty receptacles like `CounterTop`. Would it be possible to add a flag for `PlaceObjectAtPoint` that causes the event to return failure if the object falls out of canonical orientation when resolving its position?

<img width="624" alt="Screen Shot 2021-03-18 at 4 14 08 PM" src="https://user-images.githubusercontent.com/842508/111709578-15fc4380-8805-11eb-8292-520361ad54c5.png">

**Comment by winthos** [comment]
Could you provide more details on how the steps taken to get to this state of the environment? The `PlaceObjectAtPoint` action does not alter the rotation of objects at all. It only repositions their positional coordinates, and their rotations remain untouched until physics resolves their final placement.

The only thing that should affect the rotation is if perhaps a previous `PlaceObjectAtPoint` attempt caused the object to land on an uneven surface and fall over. If that happened, subsequent attempts would preserve the orientation of that object.

Additionally, a flag that returns failure may not be helpful for certain object types. For example, an `Apple` has a sphere collider so it can easily roll. If the apple rolls even a little bit, it will be out of "canonical orientation." Additionally defining what a "canonical orientation" is across all objects doesn't really make sense. Some of the default locations of objects in scenes require their local y axis to be oriented in a way that is not straight up. So would the canonical orientation be however the object is defaulted upon episode start, or would it be how the object is oriented if all of its rotation values are zeroed out? Neither of these would account for all objects.

I think if you wanted to be able to detect when an object placed gets flipped over, you can just check and compare the metadata of the specific object and see if the rotation value have changed in an unfavorable way. What "unfavorable" means will likely be specific to that object and that scene.

**Comment by thomason-jesse** [comment]
You're right, my mistake.

The non-preserving was happening because I was first issuing `DropHandObject` on held objects, because `PlaceObjectAtPoint` cannot be called on a held object. Having an API call for `PlaceObjectAtPoint` that could be applied to the held object would resolve this issue.

I was also using `PlaceObjectAtPoint` together with other API calls as a simulacrum for https://github.com/allenai/ai2thor/pull/684, so this issue will be resolved (for me at least) when that PR is finalized.
