### ISSUE TITLE
Setting excludedReceptacles in InitialRandomSpawn no longer works in 2.7.4

### ISSUE THREAD

**Issue by Tushar-N** [allenai/ai2thor#667]
Objects still spawn inside fridges even when there is plenty of counter space available for them. This didn't happen in older THOR versions.

```
controller.step(action="InitialRandomSpawn",
    randomSeed=0,
    forceVisible=False,
    numPlacementAttempts=5,
    placeStationary=True,
    numDuplicatesOfType = [],
    excludedReceptacles=['Fridge']
)
```

Setting `numPlacementAttempts` to 500 does not help.

**Comment by winthos** [comment]
Could you provide a few more details to help investigate this further?

What scene or scenes do you see this happening with? Do all the objects that the fridge starts with stay in the fridge or do some move while others don’t? Does this happen no matter what random seed is used or only for some seeds? Do you only see this behavior with fridges or if you try to exclude other receptacles does this also happen?

**Comment by Tushar-N** [comment]
Oops. I thought I was randomizing seeds for the same scene while debugging but I was not. This happens for a specific scene/seed combination only. Closing this now, my bad!
