### ISSUE TITLE
The object's rotation in metadata is in which coordinates?

### ISSUE THREAD

**Issue by liuhe1305** [allenai/ai2thor#670]
Hi, I used the version of 2.7.2 and I found the event.metadata['objects'] has the attribute 'rotation'. Could anyone tell me the rotation is in which coordinates?

**Comment by winthos** [comment]
Please take a look at our documentation here (https://ai2thor.allenai.org/ithor/documentation/environment-state/#object-metadata-rotation)

The `rotation` attribute is in a Cartesian coordinate system, with keys for x (pitch), y (yaw), and z (roll).

**Comment by liuhe1305** [comment]
> Please take a look at our documentation here (https://ai2thor.allenai.org/ithor/documentation/environment-state/#object-metadata-rotation)
> 
> The `rotation` attribute is in a Cartesian coordinate system, with keys for x (pitch), y (yaw), and z (roll).

If the rotation of y(yaw) is 30°, the rotation is relative to camera coordinate or world coordinate?

**Comment by winthos** [comment]
Rotations are in world coordinates, not relative to the agent.

**Comment by liuhe1305** [comment]
> Rotations are in world coordinates, not relative to the agent or the agent camera.

Got it. Thanks a lot
