### ISSUE TITLE
hierarchy problem

### ISSUE THREAD

**Issue by he727425209** [allenai/ai2thor#71]
Hi, 

Just a quick question about the unity hierarchy problem. So for instance, when I put an object inside the fridge or the microwave, is the object the child of the fridge or microwave?

Best

**Comment by winthos** [comment]
Yes, when a sim object is placed into a valid receptacle it becomes a child of a pivot point which is a child of the receptacle object itself. The hierarchy would be something like Microwave->pivot->object.

**Comment by ekolve** [comment]
@he727425209 can you close the issue if you don't have any further questions about receptacles/pivots?
