### ISSUE TITLE
PositionsFromWhichItemIsInteractable cannot find object

### ISSUE THREAD

**Issue by SamNPowers** [allenai/ai2thor#726]
I just upgraded to ai2thor version 3.0. In this new version, if I run, in some kitchen env:
```
scene_objects = event.objects_by_type("Bowl")
event = controller.step(action='PositionsFromWhichItemIsInteractable',
                                    objectId=scene_objects[0]['objectId'])
```

Not only does event.metadata["errorMessage"] contain "'ArgumentException: objectId: Bowl|-01.85|+00.77|-01.59 is not the objectId on any object in the scene!'", but also running `event.objects_by_type("Bowl")` a second time returns an empty list. (Whereas after the first call above, it returned a list of length 1.) So not only is it not finding valid positions, but also it's removing the bowl from the scene entirely?

**Comment by mattdeitke** [comment]
Hi @SamNPowers,

can you provide the particular scene (event.metadata["sceneName"]). My hunch would be `event` in `event.objects_by_type("Bowl")` is from a different scene, then when the sene is changed `Bowl|-01.85|+00.77|-01.59` no longer exists in the new scene, which is expected.

From the action's source code, the action should never be removing any objects.

**Comment by SamNPowers** [comment]
Ah, I'm sorry, you're right! The event was indeed out of date. (Not a different scene, but not updated after the scene was changed.)

Thanks!
