### ISSUE TITLE
The right way to write out images?

### ISSUE THREAD

**Issue by rui2016** [allenai/ai2thor#73]
Hi,

I'm trying to write out some images using the following code. However, the images I get don't look correct (attached). I also tried it for ```event.frame``` and ```event.depth_frame``` and got the similar results. Am I doing it in the right way, or is there something wrong in the data storage?

```python
import ai2thor.controller
import cv2

img_width = 640
img_height = 320

c = ai2thor.controller.Controller()
c.start(player_screen_width=img_width,
        player_screen_height=img_height)
c.reset('FloorPlan201')
event = c.step(dict(action='Initialize', continuous=True))

cv2.imwrite('test1.png', event.cv2img)
cv2.imwrite('test2.png', event.cv2img.reshape(img_height, img_width, 3))
```
test1.png
![test1](https://user-images.githubusercontent.com/17750293/42746499-eb2d687a-888c-11e8-9970-261aa6dd0cfa.png)

test2.png
![test2](https://user-images.githubusercontent.com/17750293/42746508-f333bea2-888c-11e8-8163-864d8f4023cb.png)

**Comment by danielgordon10** [comment]
@rui2016 If you want to fix it in your own version, I think all you should need to do is edit that line and line 68 in that file to say height, width instead.

**Comment by ekolve** [comment]
Fixed. Please upgrade to version 0.0.37 and close this issue once you have verified.

**Comment by rui2016** [comment]
@danielgordon10 I also found out that it can be fixed by changing the height width oder in the function read_buffer_image(). 

@ekolve Thanks for the fast fix. I will close this issue.
