### ISSUE TITLE
What is the thickness of the agent's body?

### ISSUE THREAD

**Issue by soyeonm** [allenai/ai2thor#732]
Hello,

I realized that even if agent is standing at (x,y,z), it cannot move forward to (x+alpha, y, z) sometimes, because of the thickness of its body.

1. Do you know what is the thickness of the agent's body when its' facing forward?
(thickness in the "forward" direction)

2. Do you know the thickness of the body to the side (Its "shoulder"? Thickness to the right and thickness to the left).

I am using AI2THOR 2.1.0. Thank you!

**Comment by winthos** [comment]
The agent's collider determines the thickness of its body. This collider is a capsule collider with a height of 0.9m and a radius of 0.175m.

Because it is a capsule, the thickness regardless of which direction you are moving is uniform.
