### ISSUE TITLE
Some bugs about the action 'GetReachablePositions'

### ISSUE THREAD

**Issue by liuxz-cs** [allenai/ai2thor#746]
When I perform the action `GetReachablePositions` in scene `FloorPlan429`, I get the list of the reachable positions. However, when I perform the action `TeleportFull` to put the agent in one of the reachable positions, it get the error. 

I use the code `event = controller.step(dict(action = 'Teleport', x = -2.25, y = 0.9004193, z = -1, rotation = 0, horizon = 0))` , and `event.metadata['lastActionSuccess']` is False, `event.metadata['errorMessage']` is `NullReferenceException: Object reference not set to an instance of an object.`  Actually, the position `{'x':-2.25, 'y': 0.9004193544387817, 'z': -1}` is in the list of `controller.step(action="GetReachablePositions").metadata["actionReturn"]`.  So what's the reason for that? How to solve it?

**Comment by liuxz-cs** [comment]
> Hello!
> 
> I believe the issue was that the sink geometry in the `FloorPlan429` scene was not assigned to the correct collision layer. This meant that the `GetReachablePositions` action was returning a false set of positions where it did not detect the sink being in the way correctly. When checking your position of `{'x':-2.25, 'y': 0.9004193544387817, 'z': -1}` the subsequent `Teleport` action is failing because the agent ends up clipping inside of the sink.
> 
> So `Teleport` is working correctly as it fails if the agent is teleported inside some sort of geometry, but the coordinate was erroneously returned due to `GetReachablePositions` missing the collision check.
> 
> I have made a PR that fixes this issue, but we are currently enforcing a code freeze until May 26th to keep the framework stable for Neurips. You will be able to get a pip release with this fix once May 26th comes around.
> 
> If, however, you need to grab this specific fix quickly, you can add this `commit_id` parameter to the agent controller when initializing:
> 
> `Controller(commit_id=<commit_id>)`
> 
> This will allow you to get the changes from the PR that fixes this issue directly until we make the official release.

Okay, thanks a lot.

**Comment by winthos** [comment]
These updates are now live as of [release 3.3.0](https://github.com/allenai/ai2thor/releases/tag/3.3.0)
