### ISSUE TITLE
is it possible to have multiple different version of Ai2Thor on the same machine under different conda environments

### ISSUE THREAD

**Issue by nikepupu** [allenai/ai2thor#752]
I am using Ai2Thor for different projects, and different projects have different requirements. For example, Alfred requires 2.1.0.

**Comment by mattdeitke** [comment]
Hey @nikepupu,

We have been working on adding support for this use case, although I believe it only works from v2.7 onward (i.e., not with ALFRED).

In short, one would install the latest version of AI2-THOR:

```bash
pip install ai2thor
```

and then point to a specific `commit_id` to use an older version of Unity:

```python
from ai2thor.controller import Controller
controller = Controller(commit_id="15031ee14d17c4cb23d1b318ac128b84fd1192d9")
```

We have been doing this in [Rearrangement](https://github.com/allenai/ai2thor-rearrangement) and [ManipulaTHOR](https://github.com/allenai/manipulathor), for instance.

**Comment by ekolve** [comment]
If you are using separate Conda environments then you can simply install the version you need into each environment. So you would have one environment for Alfred and a separate environment for say version 3.1.0. For your case, there is no need to pass a commit_id into the constructor.

**Comment by ekolve** [comment]
Issue appears resolved.
