### ISSUE TITLE
All navigable positions in AI2Thor 2.1.0

### ISSUE THREAD

**Issue by soyeonm** [allenai/ai2thor#755]
Hello

Thanks very much for your kind answers all the time.
How can one get all navigable positions in a scene in AI2Thor 2.1.0?
(since the documentation for this old version is now down)

Thanks always!

**Comment by mattdeitke** [comment]
ALFRED is hosting the 2.1.0 docs here: https://allenai.github.io/ai2thor-v2.1.0-documentation/actions/navigation.

To get the navigable positions, use:
```python
event = controller.step(dict(action='GetReachablePositions'))
```
