### ISSUE TITLE
Stuck with non 90 degree rotations/movements

### ISSUE THREAD

**Issue by zkytony** [allenai/ai2thor#775]
I ran into this issue again, and `continuous=True`, `snapToGrid=False` in #322 and the `rotateStepDegrees` in #370 didn't resolve it for me.

Here's a minimal example (tested with 2.7.2; feel free to try it out in a newer version and see what happens).

First I tried using the `degrees` parameter in the `step(action='RotateLeft')` or `step(action='RotateRight')`  calls, with `continuous=True`:
```python
import ai2thor.controller
import time
import cv2

STEP_COUNT=0
def saveimg(event):
    global STEP_COUNT
    cv2.imwrite("step%d.png" % STEP_COUNT, event.cv2img)
    STEP_COUNT += 1

rotation_degrees = 45

c = ai2thor.controller.Controller(continuous=True, scene='FloorPlan1')
saveimg(c.step(action="Pass"))
# facing the fridge initially
event = c.step(action='RotateLeft', degrees=rotation_degrees); saveimg(event)
event = c.step(action='RotateLeft', degrees=rotation_degrees); saveimg(event)
# now facing stove

event = c.step(action='RotateLeft', degrees=rotation_degrees); saveimg(event)
# now at 45 degree towards the table

event = c.step(action='MoveAhead'); saveimg(event)
# gets stuck

event = c.step(action='RotateRight', degrees=rotation_degrees); saveimg(event)
event = c.step(action='RotateRight', degrees=rotation_degrees); saveimg(event)
# turned away from the table

event = c.step(action='MoveAhead'); saveimg(event)
# stuck, can't actually move away from the table. Unexpected.
```
The last `MoveAhead` didn't actually move the agent, although it wasn't clear what is blocking it. The agent's view before that action is below:

![step7](https://user-images.githubusercontent.com/7720184/120028386-9e941e80-bfc2-11eb-8087-8c857e356ed2.png)

Then, I tried setting `rotateStepDegrees` when initializing the controller instead of passing `degrees`, the result is the same.

**Comment by winthos** [comment]
Can you check if there are any errormessages returned in the metadata? It appears that even moving the default `0.25` meters forward with `MoveAhead` might have the agent colliding with the countertop directly in front of you. That particular part of this kitchen scene is a very narrow area, so unless something else is going on, I predict the agent is just failing to move due to collision.

**Comment by mattdeitke** [comment]
It looks like it works for me: https://colab.research.google.com/drive/1GEYfSw0Mnfw8DsJmDTgiMHLPaPPe5Yem?usp=sharing

Also, perhaps because `degrees` is not a parameter of `MoveAhead`, that is causing the action to fail (silently in v2.7.2)
```python
event = c.step(action='MoveAhead', degrees=rotation_degrees);
# gets stuck
```

**Comment by zkytony** [comment]
> Also, perhaps because degrees is not a parameter of MoveAhead, that may be doing something weird.
Nice catch. I removed that parameter but it's not fixed. Updated my code above. Looks like it indeed works for you on colab. 

>Can you check if there are any errormessages returned in the metadata? 
Yes, there is an error message right before the last `MoveAhead` action:
```
'StandardIslandHeight is blocking Agent 0 from moving 0'
```
But when the agent first moves towards the center table (the first `MoveAhead`), no error message was received.
