### ISSUE TITLE
change the state in convertable.cs instead of python controller

### ISSUE THREAD

**Issue by he727425209** [allenai/ai2thor#78]
Hi,

Is there a way to change the state of an object (apple to apple sliced) in c# code instead of using python code?

Best

**Comment by winthos** [comment]
Yes, all the python script does is externally call a c# script to change the state of an object. This specific function can be found in the BaseFPSAgentController.cs script. Look for closeSimObj() and openSimObj().

The open and close functions only toggle a binary animation state, so if you needed an object with more than two animation states, you would need to write a custom script that grabs the Animator component on a sim object and then sets the animation state integer parameter on that Animator to whatever state is required. 

See this documentation for more information about Animator.SetIngeter(): https://docs.unity3d.com/ScriptReference/Animator.SetInteger.html
