### ISSUE TITLE
Can't set object poses on FloorPlan424

### ISSUE THREAD

**Issue by guhur** [allenai/ai2thor#782]
The action `SetObjectPoses` is handing forever on the scene FloorPlan424. 

This can be shown for example with the following piece of code, that is hanging forever. It does work on FloorPlan1 though.

```
from ai2thor.controller import Controller
scene = "FloorPlan424"
controller = Controller()
controller.reset(scene)
object_poses = [
    {
        "position": o["position"],
        "rotation": o["rotation"],
        "objectName": o["name"],
    }
    for o in controller.last_event.metadata["objects"]
    if o["pickupable"] or o["moveable"] 
]
print(len(object_poses))
event = controller.step(action="SetObjectPoses", objectPoses=object_poses)
```
I have tested this code with versions 3.3.0 and 3.2.0. I am using Ubuntu 18.04.
I have tried this code with the headless mode as well, without more success.
I haven't tested all scenes.

Thanks for your help!

**Comment by guhur** [comment]
I tested all scenes and this is happening only for FloorPlan424.

**Comment by mattdeitke** [comment]
I can confirm the issue. Looks like it just hangs forever:

https://colab.research.google.com/drive/1AJQyO0S_ZTqwkDb781WBt4pHz66hqzVW?usp=sharing

**Comment by mattdeitke** [comment]
In FloorPlan424, also getting this error message:
![image](https://user-images.githubusercontent.com/28768645/121237318-c77ea400-c84b-11eb-9e64-c745ae517982.png)

**Comment by mattdeitke** [comment]
@winthos was able to solve this, and it now works with the latest version (v3.3.1).

It may take a few minutes for release `3.3.1` to be updated by pypi/pip, but in the meantime, it should work to use
```python
controller = Controller(commit_id="d26bb0ef75d95074c39718cf9f1a0890ac2c974f")
```

as is done here:
https://colab.research.google.com/drive/1AJQyO0S_ZTqwkDb781WBt4pHz66hqzVW?usp=sharing

**Comment by guhur** [comment]
Great thanks for your quick answer :)
