### ISSUE TITLE
How to add an object to a certain scene?

### ISSUE THREAD

**Issue by pptrick** [allenai/ai2thor#787]
Hi there, I'm doing some experiments and I need to place an object in different scenes. However, I found that objects in different scenes with the same ObjectType are not exactly the same, e.g. Cups in FloorPlan1 are transparent but Cups in FloorPlan2 are black. Also, I found their ObjectName is different. Cups that exist in FloorPlan1 do not exist in FloorPlan2.
So, is there a way for me to add an object to a certain scene, or to move an object from one scene to another?

**Comment by mattdeitke** [comment]
Currently moving objects between scenes is not supported from the Python side.

We are working on supporting the ability to spawn in any object to any scene, although we don't have a timeline for when this will be supported.

I can update this thread when it is supported :)

---

Additionally, if this is really important, it would be possible to "copy and paste" objects between scenes by opening AI2-THOR in Unity. Although doing this for each scene, and placing the object in a valid pose within the scene (e.g., on a countertop), will be extremely time consuming.

**Comment by pptrick** [comment]
Thanks a lot! BTW, is there a list of object names(or appearance) in each scene?

**Comment by mattdeitke** [comment]
Perhaps the following is what you're looking for?

https://ai2thor.allenai.org/ithor/documentation/objects/object-types

Note that this doesn't cover RoboTHOR (yet!).

But, one can get this information from Python running something like the following:

```python
from ai2thor.controller import Controller
controller = Controller()
names = [obj["name"] for obj in controller.last_event.metadata["objects"]]
ids = [obj["objectId"] for obj in controller.last_event.metadata["objects"]]
types = set([obj["objectType"] for obj in controller.last_event.metadata["objects"]])
```

Here's a demo of that using [AI2-THOR Colab](https://github.com/allenai/ai2thor-colab):

https://colab.research.google.com/drive/1me1GFoau8KbTP0jF1vXLxrXxOcMxZV1Q?usp=sharing

**Comment by pptrick** [comment]
Thank you very much, they are quite helpful!
Still, I found moving objects between scenes is quite necessary, so I decided to edit the scene on Unity Editor. Is it possible for me to modify the scene and build the project on my laptop(Windows or Linux), and then send it to my workstation(Linux server) to run? In addition, I can only find Windows and Mac versions on Unity Hub for me to download, is there a version for Linux?

**Comment by pptrick** [comment]
Hi @mattdeitke, Thanks for your help! I've successfully rebuilt the unity project and I'm able to run with Python. However, I found that once I copy the `egg` from FloorPlan1 to FloorPlan2, the 'ObjectID' item came to empty, and I'm not able to reset the object position with `InitialRandomSpawn`. BTW, the `egg` I moved to FloorPlan2 lays down on the table while in other scenes it stands. Do you have any idea about it?

**Comment by basteran** [comment]
> Currently moving objects between scenes is not supported from the Python side.
> 
> We are working on supporting the ability to spawn in any object to any scene, although we don't have a timeline for when this will be supported.
> 
> I can update this thread when it is supported :)
> 
> Additionally, if this is really important, it would be possible to "copy and paste" objects between scenes by opening AI2-THOR in Unity. Although doing this for each scene, and placing the object in a valid pose within the scene (e.g., on a countertop), will be extremely time consuming.

Hi, do you have any news on this? I can't find any information in the repository about spawning a new object into a scene. I would like to add, for example, a book on the table..

**Comment by Penguin963** [comment]
> > Currently moving objects between scenes is not supported from the Python side.
> > We are working on supporting the ability to spawn in any object to any scene, although we don't have a timeline for when this will be supported.
> > I can update this thread when it is supported :)
> > Additionally, if this is really important, it would be possible to "copy and paste" objects between scenes by opening AI2-THOR in Unity. Although doing this for each scene, and placing the object in a valid pose within the scene (e.g., on a countertop), will be extremely time consuming.
> 
> Hi, do you have any news on this? I can't find any information in the repository about spawning a new object into a scene. I would like to add, for example, a book on the table..

I find a function in [https://github.com/allenai/ai2thor/blob/main/unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs](url) called "CreateObjectAtLocation". However, when I use this in python like this: 
`con.step({"action": "CreateObjectAtLocation", "objectType": "Dresser", "position":pos,"rota
tion":rot, "forceAction": True, "agentId": 1,})`

it turns out:
`'NullReferenceException: Object reference not set to an instance of an object'`
in last_event.metadata["errorMessage"]

So there is still not a solution to solve it?

**Comment by LarsLiden** [comment]
@mattdeitke - Is there still a plan to add the feature of adding objects to scenes?  For example some kitchen contain Plates and others don't.  I'd like to add Plate to the ones that done.

From the suggestion above, I've tried:

result = self.controller.step(
                action="CreateObjectAtLocation",
                objectType="Plate",
                position={
                    "x": -1.25,
                    "y": 1.0,
                    "z": -1.0}
            )

If I look at result.metadata['actionReturn'] I see:

`'Plate|1'`

However there isn't a new plate in the metadata['objects']
