### ISSUE TITLE
Issues with images when created on remote instances

### ISSUE THREAD

**Issue by aishwaryap** [allenai/ai2thor#792]
It looks like there are issues with generated images from `ai2thor` when run on a remote AWS EC2 instance. If the controller screen size has a height > ~766-768 strange artifacts appear at the bottom of the images.   

Machine type: AWS EC2 p3.16xlarge
GPU: Tesla V100 SXM2 16GB
`ai2thor` version: 3.1.0

Script to reproduce:
```
from argparse import ArgumentParser
from ai2thor.controller import Controller
from PIL import Image


def main(size):
    controller = Controller(scene='FloorPlan3_physics',
                            gridSize=0.25, snapToGrid=True,
                            width=size, height=size,
                            agentCount=1,
                            )

    event = controller.step(action='MoveAhead')
    img = Image.fromarray(controller.last_event.frame)
    img.save('temp_' + str(size) + '.png')


if __name__ == '__main__':
    arg_parser = ArgumentParser()
    arg_parser.add_argument('--size', type=int, required=True)
    args = arg_parser.parse_args()
    main(args.size)
```

This script runs fine on a Mac (images look normal and are of the correct size) but when run on the EC2 instance produces images as follows:

600 x 600
![temp_600](https://user-images.githubusercontent.com/6442600/122126993-632d8880-cde7-11eb-9773-a8d252a7474b.png)

700 x 700
![temp_700](https://user-images.githubusercontent.com/6442600/122127005-69236980-cde7-11eb-8bb5-476f2b2c789d.png)

800 x 800
![temp_800](https://user-images.githubusercontent.com/6442600/122127020-6e80b400-cde7-11eb-86d0-c0be1a26655c.png)

900 x 900
![temp_900](https://user-images.githubusercontent.com/6442600/122127034-72143b00-cde7-11eb-8d18-22addf535a5e.png)

1000 x 1000
![temp_1000](https://user-images.githubusercontent.com/6442600/122127059-7cced000-cde7-11eb-82de-52d303e372ee.png)

We have also found these artifacts occur on other AWS instance types and in some (less easily reproducible) cases they can cover the entire image.

**Comment by aishwaryap** [comment]
We were also able to reproduce the same issue with the same script on `ai2thor 3.3.1`

**Comment by mattdeitke** [comment]
Hi @aishwaryap,

Please see https://github.com/allenai/ai2thor/issues/531 and https://github.com/allenai/ai2thor/issues/776. The issue has to do with how you started the xserver, where the window by default is initialed to 1024x768, hence why images > 900 look off.

If you replace each of 1024 and 768 with something like 1500 in the `start_xserver.py` script (assuming this is how you started it), then it should work as expected.

**Comment by aishwaryap** [comment]
Thanks! Yes that resolves the issue.
