### ISSUE TITLE
Systematic collisions when holding ToiletPaper_f2f3ff78

### ISSUE THREAD

**Issue by guhur** [allenai/ai2thor#794]
Hi,

The agent is on the scene 424 holding ToiletPaper_f2f3ff78.
It seems that whatever actions is done, a collision is met.

For example, a slight rotation raises:

> ERROR a held item: ToiletPaper_f2f3ff78 with something if agent rotates Right 1 degrees with something if agent rotates Right 1 degrees

Or putting the ToiletPaper_f2f3ff78 inside a cabinet (for example Cabinet|-00.49|+00.41|+02.06) is also failing.

I can move the agent though, changing the agent looking direction or move the agent hands (as explained [here](https://github.com/allenai/ai2thor/issues/525)), but it didn't allow me to do anything more.

It sounds a bug to me, since PutObject or RotateRight works fine with ToiletPaper|-00.31|+00.07|+02.59 (yeah sure this model is smaller, but come on, you should still be able to RotateRight from 1 degree, right?)

Here is a MRE:

```python
controller = Controller()
controller.reset("FloorPlan424")
toilet_paper = 'ToiletPaper|-00.12|+00.94|+01.63'
controller.step(action='PickupObject', objectId=toilet_paper, forceAction=True)    
event = controller.step(action="RotateRight", degrees=1)
assert event['lastActionSuccess']
```

**Comment by guhur** [comment]
I am using version 3.3.1 on Ubuntu 20.04.

**Comment by mattdeitke** [comment]
Thanks @guhur!

Reproduced here:
https://colab.research.google.com/drive/1ryUbWVX6He72FErXg5pa0c2L6fdA1JX4?usp=sharing

**Comment by mattdeitke** [comment]
This is now solved in https://github.com/allenai/ai2thor/pull/796, and we've just released [v3.3.2](https://github.com/allenai/ai2thor/releases/tag/3.3.2) with this update.

Thanks for opening the issue :)

**Comment by guhur** [comment]
Great thanks :)

**Comment by guhur** [comment]
Great thanks Matt :)
