### ISSUE TITLE
Open all doors

### ISSUE THREAD

**Issue by tim37021** [allenai/ai2thor#80]
Hi,
Is it possible to open all the doors?
I've read that the object need to be in the view to be opened

**Comment by ekolve** [comment]
Do you want to open the cabinet doors? Or the doors for the rooms? The doors for the rooms do not open.

**Comment by ekolve** [comment]
This is a late reply, but it is possible to do this by running the following to open all cabinets:

```python
event = controller.last_event
for o in event.metadata['objects']:
    if o['openable'] and o['objectType'] == 'Cabinet':
        controller.step(action='OpenObject', objectId=o['objectId'], forceAction=True)
```
