### ISSUE TITLE
Access to segmentation and depth buffers of ThirdPartyCamera

### ISSUE THREAD

**Issue by fxia22** [allenai/ai2thor#81]
Thanks for sharing the source code for this great project. I find the recently added third party camera very useful to get flexible camera views. But is it possible to also access the class/instance mask buffer and the depth buffer?

**Comment by HuynhLam** [comment]
@rui2016 Did you extract the camera location and position using 
`event.metadata['thirdPartyCameras'][camera_number]['position']` and
`event.metadata['thirdPartyCameras'][camera_number]['position']` ?

If possible, could you elaborate how you reconstruct the scene using the extracted depth maps and camera poses?

In my case, I can create quite accurate single view point cloud.
![single_view](https://user-images.githubusercontent.com/7226762/54934983-191b0c80-4f28-11e9-8457-541540a72743.png)
However, when reconstructing the scene using the depth and camera poses, it's not working.
![two_views](https://user-images.githubusercontent.com/7226762/54935368-d4dc3c00-4f28-11e9-96ed-8ff68a00bf85.png)
Thank you very much!

**Comment by ekolve** [comment]
depth/segmentation is now available for thirdPartyCameras.  Take a look at http://ai2thor.allenai.org/documentation/event-metadata (search for third_party) for how to access the frames (they must be enabled during the Initialize action the same way the existing depth/segmentation frames are enabled).  This also has been released as version 1.0.2.
