### ISSUE TITLE
ToggleMapView with fixed map orientation

### ISSUE THREAD

**Issue by xubo92** [allenai/ai2thor#812]
Hi there,

I was trying to use ToggleMapView to get a top-down view. it works but with a minor problem. When I rotate the agent, from the top-down view, the agent is actually not rotated but the map rotates. this is kinda counter-intuitive. Is there any way to have a agent rotate and move but the map keep fixed?

Thanks!

**Comment by mattdeitke** [comment]
> When I rotate the agent, from the top-down view, the agent is actually not rotated but the map rotates. this is kinda counter-intuitive.

Yes, this is why its not documented. I'm going to open up a PR which solves this problem using a third party camera. Keeping open for now.
