### ISSUE TITLE
Program stuck in fifo_server.py

### ISSUE THREAD

**Issue by Tangolin** [allenai/ai2thor#817]
I just installed the ai2thor package and tried running the minimal example as suggested in the [Readme.md](https://github.com/allenai/ai2thor/blob/main/README.md). However I run into this problem where the program is trapped in the fifo_server.py file.
```
Traceback (most recent call last):
File "test.py", line 2, in <module>
    controller = Controller(scene="FloorPlan10")
  File "/home/siteng/anaconda3/envs/thor/lib/python3.6/site-packages/ai2thor/controller.py", line 476, in __init__
    host=host,
  File "/home/siteng/anaconda3/envs/thor/lib/python3.6/site-packages/ai2thor/controller.py", line 1237, in start
    self.last_event = self.server.receive()
  File "/home/siteng/anaconda3/envs/thor/lib/python3.6/site-packages/ai2thor/fifo_server.py", line 179, in receive
    metadata, files = self._recv_message()
  File "/home/siteng/anaconda3/envs/thor/lib/python3.6/site-packages/ai2thor/fifo_server.py", line 103, in _recv_message
    self.server_pipe = open(self.server_pipe_path, "rb")
```

I understand that this issue has been brought up before but even after applying the fixed mentioned [here](https://github.com/allenai/ai2thor/issues/543) I simply end up getting another error message.

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    controller = Controller(scene="FloorPlan10", server_class=ai2thor.wsgi_server.WsgiServer)
  File "/home/siteng/anaconda3/envs/thor/lib/python3.6/site-packages/ai2thor/controller.py", line 476, in __init__
    host=host,
  File "/home/siteng/anaconda3/envs/thor/lib/python3.6/site-packages/ai2thor/controller.py", line 1237, in start
    self.last_event = self.server.receive()
  File "/home/siteng/anaconda3/envs/thor/lib/python3.6/site-packages/ai2thor/wsgi_server.py", line 264, in receive
    return queue_get(self.request_queue, unity_proc=self.unity_proc)
  File "/home/siteng/anaconda3/envs/thor/lib/python3.6/site-packages/ai2thor/wsgi_server.py", line 46, in queue_get
    raise Exception("Unity process exited %s" % unity_proc.returncode)
Exception: Unity process exited 1
```

System and program info:
```
ubuntu18.04
ai2thor3.3.4
```

Any help is greatly appreciated!

**Comment by mattdeitke** [comment]
Hi @Tangolin, by chance are you running on a machine without a monitor?

**Comment by Tangolin** [comment]
Hi @mattdeitke, yes I am running it on a remote GPU, with X11 forwarding enabled to my local machine

**Comment by mattdeitke** [comment]
Can you try first running
```bash
sudo ai2thor-xorg start
```
and then running the minimal example?

This starts an xserver, which allows Unity to render images without a display. It will run this script: https://github.com/allenai/ai2thor/blob/e6a72999c667feeb4b158f4bdfcdf66910316785/scripts/ai2thor-xorg

**Comment by Tangolin** [comment]
@mattdeitke okay sure! I will try it out and get back to you on how it goes.

**Comment by Tangolin** [comment]
I am currently trying to run the program in a docker environment since I don't have sudo permission in the system. Has some problem with Xorg but will update when I resolve it.

**Comment by ekolve** [comment]
Have you tried using https://github.com/allenai/ai2thor-docker?

**Comment by Tangolin** [comment]
I tried but it requires sudo when building the docker image as well so I can't do that

**Comment by ekolve** [comment]
Can you request to be added to the docker group (or whichever group is used on your system control access to docker)? If you have permission to run a docker image you may already have the perms to build, so you could comment out the check in build.sh (in ai2thor-docker) that does the check for root or docker group.

**Comment by Tangolin** [comment]
@ekolve I am able to build, but it rans into an error at the line 
```
RUN pip3 install -r requirements.txt && python3 -c "import ai2thor.controller; ai2thor.controller.Controller(download_only=True)"
```
and returns the following message:
```
Exception: The following builds were found, but had missing dependencies. Only one valid platform is required to run AI2-THOR.
Platform Linux64 failed validation with the following errors: No valid X display found
  Linux64 requires a X11 server to be running with GLX. If you have a NVIDIA GPU, please run: sudo ai2thor-xorg start
```
My local machine is operating on windows and I ssh into a remote GPU running on ubuntu, with X11 forwarding enabled via putty(xclock runs fine). So if building from the Dockerfile requires sudo as well then I am unable to build it.

**Comment by Tangolin** [comment]
Update:
What I have done now is that I have ssh from my local machine into the remote GPU, then from remote GPU into the docker container, where I install the AI2THOR package. I ran xclock in the container and it did display on the local machine. It seems like I manage to get pass this issue when there is a display available. However a different error appears
```
X11 connection rejected because of wrong authentication.
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    controller = Controller()
  File "/usr/local/lib/python3.6/dist-packages/ai2thor/controller.py", line 465, in __init__
    self._build = self.find_build(local_build, commit_id, branch)
  File "/usr/local/lib/python3.6/dist-packages/ai2thor/controller.py", line 1130, in find_build
    if build.platform.is_valid(request):
  File "/usr/local/lib/python3.6/dist-packages/ai2thor/platform.py", line 32, in is_valid
    return len(cls.validate(request)) == 0
  File "/usr/local/lib/python3.6/dist-packages/ai2thor/platform.py", line 166, in validate
    request.x_display, request.width, request.height
  File "/usr/local/lib/python3.6/dist-packages/ai2thor/platform.py", line 90, in _validate_screen
    display_screen_str
  File "/usr/local/lib/python3.6/dist-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.6/dist-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python3.6/dist-packages/Xlib/protocol/display.py", line 162, in __init__
    auth_prot_data = auth_data)
  File "/usr/local/lib/python3.6/dist-packages/Xlib/protocol/display.py", line 1075, in __init__
    display.send_and_recv(request = -1)
  File "/usr/local/lib/python3.6/dist-packages/Xlib/protocol/display.py", line 609, in send_and_recv
    raise self.socket_error
Xlib.error.ConnectionClosedError: Display connection closed by server
```
I am not sure if this is still within the ballpark of this package's error so if it isn't I will close this issue.

**Comment by ekolve** [comment]
If you update the requirements.txt file to have the following in ai2thor-docker:
```text
ai2thor==3.3.1
```

The build script should succeed.  I will push a fix/release to resolve the earlier issue you ran into where the docker build failed.

**Comment by ekolve** [comment]
One other thing to try is when you are on the remote machine is to `unset DISPLAY` so that ai2thor does not attempt to use the forwarded X11 server.

**Comment by Tangolin** [comment]
It worked! I was able to get the ai2thor-docker up and running, everything is perfect thank you so much!

**Sum up for any future referecences**
-> If the program was ran on a remote GPU without display `sudo ai2thor-xorg start` should be ran first then followed by the minimal example.
-> Without sudo access, first `unset DISPLAY` , then [ai2thor-docker](https://github.com/allenai/ai2thor-docker) can be used instead by modifying `requirement.txt` with `ai2thor==3.3.1`

**Comment by Penguin963** [comment]
> It worked! I was able to get the ai2thor-docker up and running, everything is perfect thank you so much!
> 
> **Sum up for any future referecences** -> If the program was ran on a remote GPU without display `sudo ai2thor-xorg start` should be ran first then followed by the minimal example. -> Without sudo access, first `unset DISPLAY` , then [ai2thor-docker](https://github.com/allenai/ai2thor-docker) can be used instead by modifying `requirement.txt` with `ai2thor==3.3.1`

Is that only useful with docker？
