### ISSUE TITLE
unit of depth map.

### ISSUE THREAD

**Issue by nikepupu** [allenai/ai2thor#819]
what is the unit of depth map? is it millimeter?

**Comment by mattdeitke** [comment]
Units are reported in meters.

Check out: https://colab.research.google.com/drive/1z5vBXcfSw7SqATvCDgQwLCbfyFv1ZYDG?usp=sharing

**Comment by nikepupu** [comment]
<img width="481" alt="Screen Shot 2021-07-19 at 5 28 21 PM" src="https://user-images.githubusercontent.com/10679688/126244224-4e7fba40-265c-431a-a285-df4dc1127bd2.png">
But here is what I am getting from version 2.1.0

**Comment by mattdeitke** [comment]
It is possible that this was changed at some point, which broke sadly backwards compatibility.

I wasn't aware of this, but pining @Lucaweihs, @winthos, and @AlvaroHG who may know :)

I assume it's (probably) millimeters in v2.1.0 from the looks of your values.

**Comment by Lucaweihs** [comment]
I just checked the ALFRED repository (which I assume is what's being used here due to the use of AI2-THOR v2.1.0) and it looks like they list the max depth as 5000. This is almost certainly in millimeters.
