### ISSUE TITLE
Cabinet opens the wrong way

### ISSUE THREAD

**Issue by danielgordon10** [allenai/ai2thor#82]
Scene 23, cabinet under the sink on the left side.
the reason is in the hierarchy there is cabinet->base->door->door and both doors have a "Cabinet" script attached
this is different from the one right next to it which only the first door has the cabinet script
so when the left one is opened, it calls two transforms which causes the issue (edited)
so you can fix it by removing the script on door->door

![pasted image at 2018_07_23 02_28 pm](https://user-images.githubusercontent.com/7245472/43666221-c7e392c8-9727-11e8-9e82-856e86f35a55.png)

**Comment by ekolve** [comment]
This is fixed with the latest version (Physics enabled).
