### ISSUE TITLE
Rotation of agent in 3D space

### ISSUE THREAD

**Issue by Tangolin** [allenai/ai2thor#828]
Hi, just wanted to clarify for the rotation of the agent in Robothor, is the angle of rotation for yaw relative to the global x-axis?

**Comment by mattdeitke** [comment]
Hi @Tangolin, 

I believe it should relative to the `z` axis.

Consider the following images, where the arrows:
- `z` is the blue axis arrow
- `x` is the red axis arrow
- `y` is the green axis arrow (i.e., the vertical axis)

Here is the agent's rotation at `y=0`, where it is facing the `z` direction:
![image](https://user-images.githubusercontent.com/28768645/127115122-0e6ee3b0-0967-491a-9533-aa8df5051e90.png)

Here is a rotation at `y=90`, where it is facing the `x` direction, meaning it starts in the `z` direction, then adds `90`:
![image](https://user-images.githubusercontent.com/28768645/127115508-5172dea2-6a58-4999-9f9a-01d44e21ee3e.png)

**Comment by Tangolin** [comment]
@mattdeitke thanks a lot! Sorry for the troubles
