### ISSUE TITLE
Put down object does not match picked up object's renderer

### ISSUE THREAD

**Issue by danielgordon10** [allenai/ai2thor#83]
Example below. The mug is picked up and put down, when it is put down it seems to use a different renderer. I think this also causes it to not be in the detected objects list because the renderer is not listed in the ImageSynthesis class

![pasted image at 2018_07_20 03_55 pm](https://user-images.githubusercontent.com/7245472/43666262-f9ebe900-9727-11e8-910b-d1ffa346264e.png)

![pasted image at 2018_07_20 03_55 pm 1](https://user-images.githubusercontent.com/7245472/43666263-fb7049f6-9727-11e8-85e7-7d35675a577d.png)

**Comment by ekolve** [comment]
Fixed with version 0.0.42.  Please confirm and and close the issue if everything looks good.

**Comment by danielgordon10** [comment]
For documentation purposes: https://github.com/allenai/ai2thor/commit/ba9c4046d308ccf789a35001a13a0f7cfe0e7e7f

Do you have a test case for this?

**Comment by ekolve** [comment]
Are you asking whether there is a unit test or test case? To test this you can repeat the process you used to find the bug.  An automated unit test might be possible if we compare pixel-wise after putting the object down back in the exact same place where it was found.

**Comment by danielgordon10** [comment]
I was asking if there was a unit test. I will do a manual test and close the issue if it looks good.

**Comment by danielgordon10** [comment]
An imperfect but simple test is to check the instance_detections2D before and after, because that was broken as a consequence of this, but it doesn't test the original cause.
It does look to be fixed though, so I'll close the issue for now.

**Comment by danielgordon10** [comment]
Sample test I used.
```python
    event = env.reset('FloorPlan1')
    env.step(dict(action='Initialize', gridSize=0.25, cameraY=0.75, qualitySetting='High', renderObjectImage=True))
    event = env.random_initialize(random_seed=4, remove_prob=0.5)
    event = env.step({'action' : 'RotateRight'})
    event = env.step({'action' : 'RotateRight'})
    event = assert_successful_action(env,
            {'action' : 'OpenObject', 'objectId' : 'Microwave|-00.25|+01.71|-02.65'})
    visible_objects = {obj['objectId'] for obj in event.metadata['objects'] if obj['visible']}
    assert(visible_objects ==
        {
            'Microwave|-00.25|+01.71|-02.65',
            'Mug|-02.00|+01.65|+00.06_copy_0',
            'Cabinet|+00.68|+02.02|-02.46'
        })
    event = env.step({'action': 'PickupObject', 'objectId': 'Mug|-02.00|+01.65|+00.06_copy_0'})
    import pdb
    pdb.set_trace()
    visible_rendered_objects = set(event.instance_detections2D.keys())
    assert(visible_rendered_objects ==
        {
            'Microwave|-00.25|+01.71|-02.65',
            'Cabinet|+00.68|+02.02|-02.46'
        })
    event = env.step({
        'action': 'PutObject',
        'objectId': 'Mug|-02.00|+01.65|+00.06_copy_0',
        'receptacleObjectId': 'Microwave|-00.25|+01.71|-02.65',
        })
    visible_rendered_objects = set(event.instance_detections2D.keys())
    assert(visible_rendered_objects ==
        {
            'Microwave|-00.25|+01.71|-02.65',
            'Mug|-02.00|+01.65|+00.06_copy_0',
            'Cabinet|+00.68|+02.02|-02.46'
        })
```
