### ISSUE TITLE
Source code for v2.1.0

### ISSUE THREAD

**Issue by xfgao** [allenai/ai2thor#836]
I was wondering where we can find the source code for v2.1.0? It is not in the releases and there isn't a tag for this version.

**Comment by mattdeitke** [comment]
Will these work?: https://pypi.org/project/ai2thor/2.1.0/#files

**Comment by xfgao** [comment]
Not really since I also need the Unity part. Thanks anyway!

**Comment by mattdeitke** [comment]
Got it. Can you clone the repo locally and then go back to a commit that was on the day of the release:

Using the git history here: https://github.com/allenai/ai2thor/commits/main?after=d79028c881dd753ab7234b34dcde4af77a81fa48+2504&branch=main, I'd recommend using commit id `91414d266cfc752df01c33b6a279b33eb0d6981c`.

So, run:

```bash
git clone https://github.com/allenai/ai2thor.git
cd ai2thor
git checkout 91414d266cfc752df01c33b6a279b33eb0d6981c
```

**Comment by xfgao** [comment]
Thanks again! That was really helpful.
