### ISSUE TITLE
animate state

### ISSUE THREAD

**Issue by he727425209** [allenai/ai2thor#84]
Hi,

I notice that in the BaseFPSAgentController.cs, there are dictonaries of animate state:
protected Dictionary<SimObjType, Dictionary<string, int>> OPEN_CLOSE_STATES = new Dictionary<SimObjType, Dictionary<string, int>>{
			{SimObjType.Microwave, new Dictionary<string, int>{{"open", 2}, {"close", 1}}},
			{SimObjType.Laptop, new Dictionary<string, int>{{"open", 2}, {"close", 1}}},
			{SimObjType.Book, new Dictionary<string, int>{{"open", 1}, {"close", 2}}},
			{SimObjType.Toilet, new Dictionary<string, int>{{"open", 2}, {"close", 3}}},
			{SimObjType.Sink, new Dictionary<string, int>{{"open", 2}, {"close", 1}}}
        };

I am just wondering how did you guys figure out the animated state and the integer, like how do you guys know open is correspond to integer 2 not 1, etc.

Best

**Comment by mattdeitke** [comment]
Closing as this appears solved :)
