### ISSUE TITLE
Determining StoveBurner-StoveKnob correlations

### ISSUE THREAD

**Issue by qazwini** [allenai/ai2thor#849]
Is there a way to determine which knob correlates to which burner? Currently, the only way I could find is to place a potato on a pan on one of the burners while having nothing else on the other burners, then toggling on and off each of the knobs until the potato is cooked. Is there an easier way of finding out? Or at least is there a list that specifies them?

**Comment by mattdeitke** [comment]
Hi @qazwini,

This is a good suggestion. This currently is not specified in the metadata, but probably should be.

**Comment by winthos** [comment]
There is a helper function that is currently not exposed to metadata but does exist that we could use for this. All toggleable objects that control other objects (stove knobs, light switches, etc.) all have access to this on the Unity side. I can make a push that exposes this to metadata first thing tomorrow.

**Comment by qazwini** [comment]
Thanks for all the help!

**Comment by roymatza** [comment]
> There is a helper function that is currently not exposed to metadata but does exist that we could use for this. All toggleable objects that control other objects (stove knobs, light switches, etc.) all have access to this on the Unity side. I can make a push that exposes this to metadata first thing tomorrow.

Hello @winthos ,
Is there a relevant branch for this issue? Couldn't find any.
Thank you.

**Comment by winthos** [comment]
This has been merged onto the `main` branch as of [this commit](https://github.com/allenai/ai2thor/commit/79daca3ad220831cc9332c48fea3bfe83331c8a3). It will be part of the next version release which should be soon, estimated sometime this coming week.

In the meantime, you can make a build specifically with this commit id by using the `commit_id` parameter in your controller initialization:
```
Controller(commit_id="79daca3ad220831cc9332c48fea3bfe83331c8a3")
```

**Comment by mattdeitke** [comment]
Alternatively, so one doesn't have to specify an exact commit id, one may run
```python
from ai2thor.controller import Controller
controller = Controller(branch="main")
```
to use the latest commit from the `main` branch.
