### ISSUE TITLE
Randomize initial position

### ISSUE THREAD

**Issue by eridgd** [allenai/ai2thor#85]
Hi,

I would like to randomly initialize the starting position of the agent. I am able to Teleport to a position that is close to the initial location, but larger offsets can place the agent outside the bounds of the floorplan, and I'm not seeing anything in the metadata to indicate failure when that happens. How would you suggest going about this?

Thanks

**Comment by danielgordon10** [comment]
The way I do this for the IQA paper is to precompute valid points for each room, and then select from those points to randomly initialize https://github.com/danielgordon10/thor-iqa-cvpr-2018/blob/master/game_state.py#L484
You can find precomputed layouts at a granularity of 0.25 meters here https://github.com/danielgordon10/thor-iqa-cvpr-2018/tree/master/layouts or you can compute your own maps via a BFS.

**Comment by eridgd** [comment]
Thanks for the info. I ended up resorting to a similar approach, but I was hoping there might be a more elegant option to use with the custom floor plans I'm building. Please consider this as a future feature.

**Comment by ekolve** [comment]
The best way to do this now is to use [GetReachablePositions](https://ai2thor.allenai.org/ithor/documentation/actions/agent-navigation/#get-reachable-positions).  This will give you all the positions that the agent can navigate to.  You can then select one of these points Teleport to it.
