### ISSUE TITLE
There is no 'TableTop' in 'detections2D'

### ISSUE THREAD

**Issue by ksw9446** [allenai/ai2thor#86]
Hi,

I found that there is no 'TableTop' object in 'instance_detections2D' or 'class_detections2D'.

Would you help me to get 'TableTop's 2D bounding box?
Thank you.

**Comment by danielgordon10** [comment]
The issue with tables, and to a lesser extent sinks, is that their unity object mesh does not always correspond with the unity SimObj for TableTop. One thing you can do is go into every scene individually and rename all the tables and sinks, and then add this code to your server.py at line 164: https://github.com/allenai/ai2thor/blob/master/ai2thor/server.py#L164

```python
            elif 'SinkRenamed' in cls:
                cls = 'Sink'
                simObj = True
                color_name = [obj['objectId'] for obj in self.metadata['objects'] if obj['objectType'] == 'Sink'][0]
            elif 'TableRenamed' in cls:
                import pdb
                cls = 'TableTop'
                simObj = True
                color_name = [obj['objectId'] for obj in self.metadata['objects'] if obj['objectType'] == 'TableTop'][0]
```

Many of the tables are currently named things like Cube.001, so they are not added to the instance_detections2D list.

**Comment by ksw9446** [comment]
Thank you very much.
