### ISSUE TITLE
Add support for >300x300 screen resolution

### ISSUE THREAD

**Issue by danielgordon10** [allenai/ai2thor#87]
It seems this is not a Unity limitation based on playing around with Chalet which also uses Unity but can do smaller than 300x300.
Benefits of adding lower resolution: Faster, supports network architectures trained on 224x224 imagenet size or 84x84 Atari size
Drawbacks: You don't get all the pretty pixels we worked so hard to make.

I remember we had some weird problems before with calling this function causing renderers to not show up and getting big red patches, but I think that may have been fixed by a Unity update.
https://docs.unity3d.com/ScriptReference/Screen.SetResolution.html

**Comment by mattdeitke** [comment]
Late follow-up to this issue, but use `ChangeResolution`
```
from ai2thor.controller import Controller
c = Controller()
---
c.step('ChangeResolution', x=<width>, y=<height>)
```
to support super small screens.
