### ISSUE TITLE
Object Mesh Model Diversity per FloorPlan

### ISSUE THREAD

**Issue by ruinianxu** [allenai/ai2thor#876]
Hi all,

I want to confirm whether for the same floorplan, no matter how many times I call `InitialRandomSpawn` or `RandomizeMaterials`, the mesh model for certain object type will stay the same and the only difference is the texture.

Best,
Ruinian Xu

**Comment by mattdeitke** [comment]
Yes. Both `InitialRandomSpawn` and `RandomizeMaterials` do not affect the mesh of any objects.
