### ISSUE TITLE
Depth shader loading problem

### ISSUE THREAD

**Issue by fxia22** [allenai/ai2thor#88]
In image synthesis it is trying to find `Hidden/depths` 
https://github.com/allenai/ai2thor/blob/7b3e168c8f0a3e56a7212d4154012fb23d2c369b/unity/Assets/ImageSynthesis/ImageSynthesis.cs#L89
but the depth shader is named as:
https://github.com/allenai/ai2thor/blob/7b3e168c8f0a3e56a7212d4154012fb23d2c369b/unity/Assets/ImageSynthesis/Shaders/Depth.shader#L3

This seems to cause depth shader not loaded sometimes. This could help #81.

**Comment by ekolve** [comment]
Is there an error message that I can look for to see if the shader doesn't get loaded?

**Comment by fxia22** [comment]
I am not familiar C#, but in C++ you can do the following to check if shaders are loaded correctly:
```cpp
GLint success = 0;
glGetShaderiv(shader, GL_COMPILE_STATUS, &success);
```

You can also check the log using `glGetShaderInfoLog`.

**Comment by ekolve** [comment]
How did you observe that the shader was not getting loaded? I can change the Shader.Find() line, but I have no way of verifying that this fixes anything if we can't reproduce the loading issue.

**Comment by ekolve** [comment]
I think the reason why the code works currently, is that we don't depend on that line.  The DepthShader component is set on FirstPersonCharacter, so I don't think we ever hit that line.

**Comment by fxia22** [comment]
That makes sense. I only have this issue when using ThirdPartyCamera. I changed `Shader.Find()` and that fixes depth shader loading problem. Before changing that line the depth camera renders a black and white texture image (I guess that's one channel from the color shader), not depth. After changing that line it is able to render depth image correctly.

**Comment by ekolve** [comment]
Got it, that makes sense.  I'll push a new build out shortly with the change.

**Comment by fxia22** [comment]
thanks!
