### ISSUE TITLE
Graph representation of scenes

### ISSUE THREAD

**Issue by JunhongXu** [allenai/ai2thor#9]
Hello

How can I get the graph representation of each scene? I see there is a class BFSController that has a find shortest path method. It needs a NetworkX graph as input. Can I have a working example on how to construct such graph on these scenes?

Thank you!

**Comment by ekolve** [comment]
We currently use those methods internally, but I can document them and clean the interface up a bit.  We use that to compute a plan (navigation, rotation and azimuth) between where the agent is located and the point where the target is visible.  Is this what you are interested in?

**Comment by JunhongXu** [comment]
Yes. This is useful when we want to do imitation learning in this environment. I currently use the shortest path solution given by NetworkX to navigate to the the node that is closest to the target object and do a brute force search in rotation angle and camera horizon to make the target visible. I am not sure whether there are better ways to do this.

**Comment by shamanez** [comment]
How can I use NetworkX? What is the command
