### ISSUE TITLE
Program stuck in fifo_server.py (& ai2thor-xorg start not working)

### ISSUE THREAD

**Issue by 1996srikesh** [allenai/ai2thor#934]
Hi, 

I'm trying to run your minimal example from your Readme.md and found the Controller stuck in the receive() call. I am running this on Google colab GPU by the way (i.e. w/ no display). After looking at:
https://github.com/allenai/ai2thor/issues/837
https://github.com/allenai/ai2thor/issues/817
https://github.com/allenai/ai2thor/issues/543

I tried running sudo ai2thor-xorg start which gave me the following output: 

Error: error with command 'Xorg -quiet -maxclients 1024 -noreset +extension GLX +extension RANDR +extension RENDER -logfile /var/log/ai2thor-xorg.0.log -config /tmp/ai2thor-xorg.conf :0'
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/ai2thor-xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.

Also, If I try running the minimal example with the server_class=ai2thor.wsgi_server.WsgiServer argument i get this error (as mentioned in the previous three posts): 

---------------------------------------------------------------------------
Empty                                     Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/ai2thor/wsgi_server.py in queue_get(que, unity_proc)
     36         try:
---> 37             res = que.get(block=True, timeout=0.5)
     38             break

5 frames
Empty: 

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/ai2thor/wsgi_server.py in queue_get(que, unity_proc)
     54                     raise Exception(
     55                         "Could not get a message from the queue after %s attempts "
---> 56                         % attempts
     57                     )
     58     return res

Exception: Could not get a message from the queue after 200 attempts

**Comment by 1996srikesh** [comment]
@ekolve May I please have an update on this?

**Comment by ekolve** [comment]
Google Colab does not allow you to launch an Xorg server within the container that the notebook is running. The easiest way to run ai2thor on Colab is to use the CloudRendering platform:

```python
import ai2thor.controller
from ai2thor.platform import CloudRendering
c = ai2thor.controller.Controller(platform=CloudRendering)
```
This doesn't require running a Xorg server, so you won't get the error you posted originall.

**Comment by 1996srikesh** [comment]
@ekolve I am getting a "ModuleNotFoundError: No module named 'ai2thor.platform'" error, even though i  pip installed ai2thor==3.1.0; i d/l the repo but it cannot follow the directory tree to the platform.py file.

**Comment by 1996srikesh** [comment]
Thank You!
