### ISSUE TITLE
Can we add a semantic third party camera ?

### ISSUE THREAD

**Issue by guhur** [allenai/ai2thor#938]
Hi,

I am looking for a map view with a semantic frame. 

The version 3.3.4 added a new GetMapViewCameraProperties. Great!

But, I am not sure we can add a semantic frame with third party cameras.

Am I missing something?
If not, is that something complicated to implement? I guess I would just need to patch the backend and copy the semantic frame into the third party cameras, but I never been over the backend code, and I might be quite naive about it.

Thanks for your answer,

PL

**Comment by mattdeitke** [comment]
Hi @guhur,

Try setting `renderSemanticSegmenation=True` and then accessing `third_party_semantic_segmentation_frames`?

The minimal example is:
```python
from ai2thor.controller import Controller
controller = Controller(renderSemanticSegmentation=True)
event = controller.step(action="GetMapViewCameraProperties")
event = controller.step(
    action="AddThirdPartyCamera",
    **event.metadata["actionReturn"]
)
event.third_party_semantic_segmentation_frames
```

**Comment by guhur** [comment]
Oh right sorry I forgot this point!

**Comment by mlodel** [comment]
@mattdeitke I tried your minimal example, for me `event.third_party_semantic_segmentation_frames` is an empty list. Has something changed in `ai2thor` since and how could I make the top-down semantic segmentation work? Thanks for the help.
