### ISSUE TITLE
Teleport sends the agent to a different location despite successful action

### ISSUE THREAD

**Issue by Tangolin** [allenai/ai2thor#956]
I first ran the line 

```p1 = controller.step(action="GetReachablePositions").metadata["actionReturn"]```

and thereafter chose a valid position from the list, teleported the agent to that location.

```event = controller.step(action='Teleport', position=dict(x=2.0, y=0.9009997248649597, z=-2.8000001907348633), rotation=dict(x=0,y=90, z=0), horizon=0)```

 However the agent landed at a different location with ```lastActionSuccess``` returning True.

```
{'x': 2.0, 'y': 0.9009993076324463, 'z': -2.8000001907348633}
True
```

And somehow this operation also changed the values returned from the ```GetReachablePositions``` operation. How can I resolve this and make sure the reachablePositions are consistent after teleporting? My full code snippet is as follows:
```
startx()

controller = Controller(
                agentMode="default",
                visibilityDistance=100,
                scene="FloorPlan_Train1_1",
                gridSize=0.4,
                snapToGrid=True,
                movementGaussianSigma=0,
                rotateStepDegrees=90,
                rotateGaussianSigma=0,
                renderDepthImage=True,
                renderInstanceSegmentation=True,
                width=640,
                height=480,
                fieldOfView=90
                )

p1 = controller.step(action="GetReachablePositions").metadata["actionReturn"]

event = controller.step(action='Teleport', position=dict(x=2.0, y=0.9009997248649597, z=-2.8000001907348633), rotation=dict(x=0,y=90, z=0), horizon=0)

print(event.metadata['agent']['position'])
print(event.metadata['lastActionSuccess'])

p2 = controller.step(action="GetReachablePositions").metadata["actionReturn"] 

with open('tester.json', 'w') as f:
    json.dump(p1, f, indent=4)

with open('tester1.json', 'w') as f:
    json.dump(p2, f, indent=4)

# p2 and p1 are different
```

**Comment by mattdeitke** [comment]
Hi @Tangolin,

This seems to be an expected floating point issue. Check out this notebook for some visualizations:
https://colab.research.google.com/drive/1L7uXC4307hNXbtUSLEcn9cxeBrQ6E4kp?usp=sharing

Specifically:
- When creating a plot overlaying the two sets of returned reachable positions (in xz space), the plots appear identical:
![image](https://user-images.githubusercontent.com/28768645/146084808-43def4d3-cf6c-4f0e-9962-8d5fa6932f96.png)

- When printing out the closest points between `p1` and `p2`, we see the floating point differences, but the positions are the same (to some degree of precision).
![image](https://user-images.githubusercontent.com/28768645/146084919-58dfe60d-7640-49ca-b204-0772408577fd.png)

**Comment by Tangolin** [comment]
@mattdeitke I see! Thanks for the clarification.
