### ISSUE TITLE
Better documentation for development 

### ISSUE THREAD

**Issue by aleSuglia** [allenai/ai2thor#96]
Hi,

Thanks for your effort in maintaining this amazing project. I've recently started playing with it and I would like to know in detail what is the workflow that I should follow in order to extend your project. 

The current documentation is really minimal and unfortunately I would like to do something more than just adding a new scene. In particular, I would appreciate to see how I can debug the "game" using the Unity editor so that I can use it to create a new game and then re-use it via the Python controller. At the moment when I press the command "play" in Unity, there is a debug message saying "Unable to establish the connection with host". I have the feeling that the AI2Thor server should be running in the background. I tried to start it using the following code but it didn't work:
```
import os
import ai2thor.controller
import argparse

def releases_dir(self):
	releases_dir_path = os.getenv("RELEASES_DIR")
	if releases_dir_path:
		return os.path.normpath(releases_dir_path)

	return os.path.normpath(os.path.join(os.path.abspath(__file__), "..", "..", "..", "unity", "builds"))


def main(args):
	controller = ai2thor.controller.Controller()
	controller.releases_dir = releases_dir.__get__(controller, ai2thor.controller.Controller)
	print("trying to start unity")
	controller.start(player_screen_width=800, player_screen_height=800)
	print("Controller started")
	print("Intialised environment with scene {}".format(args.scene_id))

	while True:
              try: 
                     pass
              except KeyboardInterrupt:
                     controller.stop()
                     break

parser = argparse.ArgumentParser()

parser.add_argument("-s", "--scene_id", type=str, help="Scene identifier", default="FloorPlan28")

if __name__ == "__main__":
	args = parser.parse_args()
	main(args)
``` 

Could you please provide me with more information about the development process? 

Thanks,

Alessandro

**Comment by ekolve** [comment]
Hi Alessandro,

Could you try running the following:

```python
        controller = ai2thor.controller.Controller()
	print("trying to start unity")
	controller.start(port=8200, start_unity=False, player_screen_width=800, player_screen_height=800)
	print("Controller started")
	print("Intialised environment with scene {}".format(args.scene_id))

	while True:
              try: 
                     pass
              except KeyboardInterrupt:
                     controller.stop()
                     break
```

Make the above changes to your script and start it before hitting the Play button in the Unity Editor.  What the two additional parameters to start() do is *not* attempt to launch the Thor executable (start_unity=False) and listen on port 8200.  By default, if no port is specified (normally passed in via an environment variable), then Thor on the Unity side will attempt to connect on port 8200.

--eric

**Comment by aleSuglia** [comment]
@ekolve: that worked like a charm. Thanks a lot!

In my use case I need to completely design a new "game" and use ai2thor "infrastructure" to allow my agent to communicate with the Unity engine. As a starting point, I copied one of your scenes and I was thinking to start implementing my game from it. In this way I should be able to reuse all your components that are already defined. For example if I define the new scene with the id "Scene_Example", I must specify it in the Python script above as well and in this way it will automatically connect to the running Unity engine.  

Do you think that it's an optimal way to design a completely new game from the material provided by your framework?

Thanks,

Alessandro

**Comment by ekolve** [comment]
Closing issue as it appears to be resolved.  @aleSuglia sorry for the extremely late reply.  Using our infrastructure is a reasonable approach as well you could look at this: https://github.com/Unity-Technologies/ml-agents

**Comment by KaixiangLin** [comment]
Hi, @ekolve , 

the above instruction seems doesn't work with the current python wrapper. It throws error no matter I use fifo server of wsgi server. Could you please provide a workable example for developing with unity editor? 

Thanks.

**Comment by mattdeitke** [comment]
Hey @KaixiangLin,

Perhaps [discussion#551](https://github.com/allenai/ai2thor/discussions/551#discussioncomment-218183) would be of interest. It should contain the updated initialization and basic setup.

**Comment by KaixiangLin** [comment]
Hi, @mattdeitke  

Thanks for the prompt reply. I have set up unity with AI2THOR and the python wrapper can work with executable build smoothly. 

What I am looking for is how to use python wrapper interact (control robot movement) with unity editor after I hit "play" button. The  discussion#551 seems didn't provide this information.  

Byw, If I run the build exe the ai2thor, the robot was automatically added to the scene. But in unity editor, robot was not added after hitting play. Is there a way to change this? 


Thanks.

**Comment by mattdeitke** [comment]
> What I am looking for is how to use python wrapper interact (control robot movement) with unity editor after I hit "play" button. The discussion#551 seems didn't provide this information.

I see. Can you try passing in `port=8200, start_unity=False` upon initialization of the Controller; as in:
```python
from ai2thor.controller import Controller
c = Controller(start_unity=False, port=8200)
```
Manually calling `start` is deprecated.

- - -

> Btw, If I run the build exe the ai2thor, the robot was automatically added to the scene. But in unity editor, robot was not added after hitting play. Is there a way to change this?

Will follow up on this with a more complete answer, but roughly:

* To show the robot from the Unity editor, it should be possible by clicking on the robot capsule from the hierarchy, then toggling on the visibility within the inspector. This is definitely tedious, since one has to keep manually toggling the visibility upon reset. A simpler local solution may just be to comment out a few lines of code that hide the agent.

* To hide the robot from the Python side, I believe somebody mentioned that there’s a parameter that can be passed in upon initialization, but it doesn’t appear to be documented and also doesn’t look to have a particularly easily searchable name.

If you’re interested in the latter, it might be best to move this to a new issue.

**Comment by KaixiangLin** [comment]
Using the above code, with fifo server 
it stuck at self.server_pipe = open(self.server_pipe_path, "rb" )
with wsgi server: 
```
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
```
With different port value 
```
c = Controller(start_unity=False, port=0,server_class=wsgi_server.WsgiServer)
```
It throws 
```AttributeError: 'WsgiServer' object has no attribute 'unity_proc'```

**Comment by KaixiangLin** [comment]
> * To show the robot from the Unity editor, it should be possible by clicking on the robot capsule from the hierarchy, then toggling on the visibility within the inspector. This is definitely tedious, since one has to keep manually toggling the visibility upon reset. A simpler local solution may just be to comment out a few lines of code that hide the agent.

The robot FPSController is checked before hitting play button in the unity editor. I think it is somewhere in the unity code all robots are deactivated. I am not sure what are the couple of lines you mentioned. I only found comment this [line](https://github.com/allenai/ai2thor/blob/5b7a32f47bb6417113045926957ea5cd857e5dd3/unity/Assets/Scripts/BaseFPSAgentController.cs#L213) give "half of robot" showing up.
