### ISSUE TITLE
'GetSpawnCoordinatesAboveReceptacle' only works when the receptacle is visible

### ISSUE THREAD

**Issue by LWJ312** [allenai/ai2thor#962]
Hi~ I have done some tests to find that the action **_GetSpawnCoordinatesAboveReceptacle_** only returns results when the passed receptacle is visible. Is there some way to place specific objects at specific receptacles in the scene initialization? (different from the action **_InitialRandomSpawn_** which is in the random). Thanks a lot~

**Comment by winthos** [comment]
Pass “anywhere = True” as a parameter to allow coordinates outside of the agent’s current visibility to be returned.

**Comment by LWJ312** [comment]
Thanks for the timely reply!
