### ISSUE TITLE
objectId isn't updated after successful PlaceObjectAtPoint

### ISSUE THREAD

**Issue by LWJ312** [allenai/ai2thor#967]
Sorry to disturb you again. I use the `ai2thor 4.0.0` to find that after successful `GetSpawnCoordinatesAboveReceptacle` and `PlaceObjectAtPoint`, the re-positioned objectId is not updated.

```
import random
from ai2thor.controller import Controller

controller = Controller(scene='FloorPlan1')
bread = controller.last_event.objects_by_type('Bread')[0]
print(f"find Bread position: {bread['position']} \n objectId: {bread['objectId']} \n parentReceptacles: {bread['parentReceptacles']}")

bread_receptacle = bread['parentReceptacles'][0]
spawn_positions = controller.step(action='GetSpawnCoordinatesAboveReceptacle',
                objectId=bread_receptacle,
                anywhere = True).metadata['actionReturn']
while(True):
    seed = random.randint(0,len(spawn_positions))
    print(f"Place with seed {seed}")
    controller.step(action='PlaceObjectAtPoint',
                    objectId = bread['objectId'],
                    position = spawn_positions[seed]
                    )
    print(controller.last_event.metadata['errorMessage'])
    if controller.last_event.metadata['lastActionSuccess']:
        bread_new = controller.last_event.objects_by_type('Bread')[0]
        print(f"after spawn Bread position: {bread_new['position']} \n objectId: {bread_new['objectId']} \n parentReceptacles: {bread_new['parentReceptacles']}")
        break
```

The output results are here and the newly placed Bread's objectId is not updated.
```
find Bread position: {'x': -0.5223836302757263, 'y': 1.1704490184783936, 'z': -0.028279857710003853} 
 objectId: Bread|-00.52|+01.17|-00.03 
 parentReceptacles: ['CounterTop|-00.08|+01.15|00.00']
Place with seed 228

after spawn Bread position: {'x': -0.059099819511175156, 'y': 1.1704508066177368, 'z': -0.8098763823509216} 
 objectId: Bread|-00.52|+01.17|-00.03 
 parentReceptacles: ['CounterTop|-00.08|+01.15|00.00']
```

**Comment by winthos** [comment]
The `objectId` of a sim object is not updated unless you explicitly use the `InitialRandomSpawn` or `SetObjectPoses` actions. The `PlaceObjectAtPoint` action is repositioning a single object, sort of like a more specific `PutObject` action, which does not require the `objectId` to be updated to include the new position. Note that the `objectId` is meant to be a unique identifier for a given object in a given scene, so to help with this we automatically append the "starting" position coordinates of an object to the id. 

`InitialRandomSpawn` is meant to be used as a setup function, meaning you run it after initializing your controller but before you actually run around and start doing experiments in the environment. `PlaceObjectAtPoint` is not a setup action, and is meant to be used after the scene has been set up and ready to use. 

If you want to track a change in an object's position after using `PlaceObjectAtPoint`, the object's position metadata does update as it is repositioned into a new receptacle.

**Comment by LWJ312** [comment]
Really appreciate it! Thanks~
