### ISSUE TITLE
Map of the scene

### ISSUE THREAD

**Issue by Zhendong-Wang** [allenai/ai2thor#98]
Hi,
Your AI2-Thor is really good. I wanna to know if I can get each map of each scene, like where the object is, where the agent can go. It is like we like a god, from the roof of the scene, to see the action of the agent. Can we see the animation like taking actions in a grid world. 
Thanks

**Comment by Zhendong-Wang** [comment]
Can we have the x, y and z coordinates of each agent in the map of each scene? like a 2D map

**Comment by roozbehm** [comment]
You can get position information for each object from metadata. Please refer to [metadata for objects](https://ai2thor.allenai.org/tutorials/event-metadata#objects).

**Comment by rkruegs123** [comment]
How do the object coordinates correspond to screen size?

**Comment by GELIELEO** [comment]
@Zhendong-Wang  Did you solve it?

**Comment by winthos** [comment]
@rkruegs123  The screen size is basically just a window that looks into the world the objects are in. Changing the window will have no affect on the coordinates of objects. If, for example, you change the screen to be very small, some objects might not appear on screen, but their coordinates will remain the same.

**Comment by mattdeitke** [comment]
Merging with #445. Accessing all the positional data should already be available with the metadata :)
