### ISSUE TITLE
Place slice of object in a physically realistic way  

### ISSUE THREAD

**Issue by 594zyc** [allenai/ai2thor#991]
Hi,

When place a slice of bread/apple/lettuce/potato using the built-in `PlaceObejct` action, it will stand on the receptacle in a unrealistic way (see the attached image of a "sandwich" we made). Is there any way to make the placed object lie in a more realistic pose? 

Thanks!

![driver frame end](https://user-images.githubusercontent.com/19399624/155571314-1f90f6c9-bc21-4af8-a756-838309164ebb.jpeg)

**Comment by winthos** [comment]
The “PutObject” action snaps objects into free position based on calculations using the object bounds and the receptacle zones defined by receptacle objects, this can lead to this more unrealistic positioning.

the best way to place an object more realistically is to position the object above a receptacle and then drop it onto the receptacle, allowing the physics engine to resolve the final position. You can you something like a series of “MoveHand” actions and then “DropObject” to achieve this.

**Comment by 594zyc** [comment]
Thanks for your quick response! I'll try it out.
